<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>РЎРѕР·РґР°РЅРёРµ РјРѕРґРµР»РµР№ Р»РёРЅРµР№РЅРѕР№ СЂРµРіСЂРµСЃСЃРёРё</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
<link rel="icon" type="image/png" href="images/favicon.png" />

<script type="text/javascript" src="js/rmarkdown.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="css\envmodel.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->




<!--<div id="rStudioHeader" class="alwaysShrunk">
  <div class="innards bandContent">

      <a class="productName" href="index.html">Математическое моделирование в экологии
</a>


    <div id="menu">
      <div id="menuToggler"></div>
      <div id="menuItems">
        <a class="menuItem" href="Part-1-topic-1.html">Занятия</a>
        <a class="menuItem" href="Tests.html">Задания</a>
        <a class="menuItem" href="presentations/Introduction_R.html">Презентации</a>
        <a class="menuItem" href="materials.html">Материалы</a>
        <a class="menuItem gitHub" href="https://github.com/environemental-modelling/environemental-modelling.github.io"></a>
        <a class="menuItem gitHubText" href="https://github.com/environemental-modelling/environemental-modelling.github.io">Source on GitHub</a>
      </div>
    </div>
  </div>
</div>
-->

<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="index.html" class="navbar-brand">Математическое моделирование в экологии</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Занятия<span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="themes">

                <li><a href="Part-1-topic-1.html">Введение в R</a></li>
                <li><a href="Part-2-topic-2.html">Физические модели</a></li>
                <li><a href="Part-3-topic-1.html">Манипуляции над данными</a></li>
                <li><a href="Part-4-topic-1.html">Линейная регрессия</a></li>
                <li><a href="Part-4-topic-2.html">Логистическая регрессия</a></li>
                <li><a href="Part-5-topic-1.html">Рандомизация и бутстреп</a></li>
                
              </ul>
            </li>
            <li><a href="Tests.html" target="_blank">Задания</a></li>
            <li><a href="presentations/Introduction_R.html" target="_blank">Презентации</a></li>
            <li><a href="materials.html" target="_blank">Материалы</a></li>
            <li><a class="menuItem gitHub" href="https://github.com/environemental-modelling/environemental-modelling.github.io"></a>
                <a class="menuItem gitHubText" href="https://github.com/environemental-modelling/environemental-modelling.github.io">Исходники в GitHub</a></li>
          </ul>
    </div>
  </div>
</div>


<style type="text/css">
#TOC {
  margin-left: 35px;
  margin-top: 90px;
}
</style>

<script type="text/javascript">
$(".main-container").removeClass("main-container").removeClass("container-fluid").addClass("footerPushDown");
</script>


<div id="pageContent" class="standardPadding">
  <div class="articleBandContent">
<div class="lessonPage">
  <div class="lessonsNav">
    <a id="nav-lesson-1" href="Part-1-topic-1.html">Введение в программирование на языке R</a>
    <a id="nav-lesson-15" href="Part-2-topic-2.html">Физические модели. Формализация и численные решения.</a>
    <a id="nav-lesson-2" href="Part-3-topic-1.html">Манипуляции над данными</a>
    <a id="nav-lesson-3" href="Part-4-topic-1.html">Создание моделей линейной регрессии</a>
    <a id="nav-lesson-4" href="Part-4-topic-2.html">Модели логистической регрессии</a>
    <a id="nav-lesson-5" href="Part-5-topic-1.html">Дополнительные методы</a>

    <!--<a id="nav-lesson-5" href="lesson-5.html">Multiple regression modelling</a>
        <a id="nav-lesson-5" href="lesson-5.html">Всякое новое</a>
    <a id="nav-lesson-6" href="lesson-6.html">Parameters</a>
    <a id="nav-lesson-7" href="lesson-7.html">Tables</a>
    <a id="nav-lesson-8" href="lesson-8.html">Markdown Basics</a>
    <a id="nav-lesson-9" href="lesson-9.html">Output Formats</a>
    <a id="nav-lesson-10" href="lesson-10.html">Notebooks</a>
    <a id="nav-lesson-11" href="lesson-11.html">Slide Presentations</a>
    <a id="nav-lesson-12" href="lesson-12.html">Dashboards</a>
    <a id="nav-lesson-13" href="lesson-13.html">Websites</a>
    <a id="nav-lesson-14" href="lesson-14.html">Interactive Documents</a>
    <a id="nav-lesson-15" href="lesson-15.html">Cheatsheets</a>-->
  </div>
  <div class="lessonContent">

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">РЎРѕР·РґР°РЅРёРµ РјРѕРґРµР»РµР№ Р»РёРЅРµР№РЅРѕР№ СЂРµРіСЂРµСЃСЃРёРё</h1>

</div>


<div id="section" class="section level1">
<h1>РЎРµРјРёРЅР°СЂ 4 - РџРѕСЃС‚СЂРѕРµРЅРёРµ РјРѕРґРµР»РµР№</h1>
<div id="section-1" class="section level2">
<h2>РљРѕСЂРµР»Р»СЏС†РёСЏ</h2>
<p>Р”Р°РІР°Р№С‚Рµ СЃРѕР·РґР°РґРёРј РґРІР° РІРµРєС‚РѕСЂР°, РєРѕРІР°СЂРёР°С†РёСЋ РјРµР¶РґСѓ РєРѕС‚РѕСЂС‹РјРё РјС‹ Рё РїРѕРїС‹С‚Р°РµРјСЃСЏ РїРѕСЃС‡РёС‚Р°С‚СЊ</p>
<pre class="r"><code>A=1:3
B=c(3,6,7)</code></pre>
<p>РћР±С‰Р°СЏ РёРґРµСЏ РєРѕРІР°СЂРёР°С†РёРё СЃРѕСЃС‚РѕРёС‚ РІ РѕРїСЂРµРґРµР»РµРЅРёРё СЃС‚РµРїРµРЅРё РІР·Р°РёРјРЅРѕРёР·РјРµРЅРµРЅРёСЏ РґРІСѓС… РіСЂСѓРїРї РґР°РЅРЅС‹С…, С‚.Рµ. РЅР° СЃРєРѕР»СЊРєРѕ С‡Р°СЃС‚Рѕ РёР·РјРµРЅРµРЅРёРµ РѕРґРЅРѕР№ РІРµР»РёС‡РёРЅС‹ Р±СѓРґРµ СЃРѕРІРїР°РґР°С‚СЊ СЃРѕ СЃС…РѕРґРЅС‹Рј РёР·РјРµРЅРµРЅРёРµРј РґСЂСѓРіРѕР№ РІРµР»РёС‡РёРЅС‹. Р’ РєР°С‡РµСЃС‚РІРµ РїРѕРєР°Р·Р°С‚РµР»СЏ РёР·РјРµРЅРµРЅРёСЏ РІРµР»РёС‡РёРЅС‹ РјС‹ Р±СѓРґРµРј РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РѕС‚РєР»РѕРЅРµРЅРёРµ РѕС‚ СЃСЂРµРґРЅРµРіРѕ. РџРѕСЃС‡РёС‚Р°РµРј РѕС‚РєР»РѕРЅРµРЅРёРµ РѕС‚ СЃСЂРµРґРЅРµРіРѕ РґР»СЏ РєР°Р¶РґРѕРіРѕ РёР· РЅР°С€РёС… РІРµРєС‚РѕСЂРѕРІ.</p>
<pre class="r"><code>diff_A &lt;- A - mean(A)
diff_B &lt;- B - mean(B)</code></pre>
<p>Р”Р»СЏ РѕРїСЂРµРґРµР»РµРЅРёСЏ РІР·Р°РёРјРЅРѕСЃС‚Рё РёР·РјРµРЅРµРЅРёСЏ РІРµР»РёС‡РёРЅ РјС‹ РїРµСЂРµРјРЅРѕР¶РёРј РёС… РѕС‚РєР»РѕРЅРµРЅРёСЏ РѕС‚ СЃСЂРµРґРЅРµРіРѕ Рё РїСЂРѕСЃСѓРјРёСЂСѓРµРј СЂРµР·СѓР»СЊС‚Р°С‚С‹. РћС‡РµРІРёРґРЅРѕ, С‡С‚Рѕ РєРѕРІР°СЂРёР°С†РёСЏ Р±СѓРґРµС‚ С‚РµРј Р±РѕР»СЊС€Рµ, С‡РµРј С‡Р°С‰Рµ Сѓ РЅР°СЃ СЃРѕРІРїР°РґР°Р»Рё Р·РЅР°РєРё РѕС‚РєР»РѕРЅРµРЅРёР№ РѕС‚ СЃСЂРµРґРЅРµРіРѕ, Р° Р·РЅР°С‡РёС‚ Рё РёС… “РЅР°РїСЂР°РІР»РµРЅРёРµ”. РўР°Рє Р¶Рµ РѕС‡РµРІРёРґРЅРѕ, С‡С‚Рѕ РґР»СЏ С‚РѕРіРѕ С‡С‚РѕР±С‹ РєРѕРІР°СЂРёР°С†РёРё РІС‹Р±РѕСЂРѕРє СЂР°Р·РЅС‹С… СЂР°Р·РјРµСЂРѕРІ Р±С‹Р»Рё СЃСЂР°РІРЅРёРјС‹, РјС‹ РґРѕР»Р¶РЅС‹ СЂР°Р·РґРµР»РёС‚СЊ РїРѕР»СѓС‡РµРЅРЅСѓСЋ СЃСѓРјРјСѓ РЅР° РѕР±СЉРµРј РІС‹Р±РѕСЂРєРё:</p>
<pre class="r"><code>cov &lt;- sum(diff_A*diff_B)/ (length(A)-1)</code></pre>
<p>РћС‚РґРµР»СЊРЅРѕ РґР»СЏ РІС‹С‡РёСЃР»РµРЅРёСЏ СЃС‚Р°РЅРґР°СЂС‚РЅРѕРіРѕ РѕС‚РєР»РѕРЅРµРЅРёСЏ СЂР°СЃС‡РёС‚Р°РµРј РєРІР°РґСЂР°С‚С‹ РѕС‚РєР»РѕРЅРµРЅРёР№ РѕС‚ СЃСЂРµРґРЅРµРіРѕ РґР»СЏ РєР°Р¶РґРѕРіРѕ РІРµРєС‚РѕСЂР°</p>
<pre class="r"><code>sq_diff_A &lt;- diff_A^2
sq_diff_B &lt;- diff_B^2</code></pre>
<p>РџСЂРѕСЃСѓРјРјРёСЂРѕРІР°РІ РєРІР°РґСЂР°С‚С‹ РѕС‚РєР»РѕРЅРµРЅРёР№, СЂР°Р·РґРµР»РёРІ РёС… РЅР° РѕР±СЉРµРј РІС‹Р±РѕСЂРєРё РјРёРЅСѓСЃ 1 Рё РІР·СЏРІ РёР· РїРѕР»СѓС‡РµРЅРЅРѕРіРѕ РєРІР°РґСЂР°С‚РЅС‹Р№ РєРѕСЂРµРЅСЊ, РјС‹ РїРѕР»СѓС‡РёРј СЃС‚Р°РЅРґР°СЂС‚РЅРѕРµ РѕС‚РєР»РѕРЅРµРЅРёРµ.</p>
<pre class="r"><code>sd_A &lt;- sqrt(sum(sq_diff_A)/(length(A)-1))
sd_B &lt;- sqrt(sum(sq_diff_B)/(length(B)-1))</code></pre>
<p>РўРѕРіРґР° РєРѕСЌС„С„РёС†РёРµРЅС‚РѕРј РєРѕСЂСЂРµР»СЏС†РёРё РґРІСѓС… РІРµР»РёС‡РёРЅ Р±СѓРґРµС‚ РЅР°Р·С‹РІР°С‚СЊСЃСЏ РѕС‚РЅРѕС€РµРЅРёРµ РІРµР»РёС‡РёРЅС‹ РёС… РєРѕРІР°СЂРёР°С†РёРё Рє РїСЂРѕРёР·РІРµРґРµРЅРёСЋ СЃС‚Р°РЅРґР°СЂС‚РЅС‹С… РѕС‚РєР»РѕРЅРµРЅРёР№ РєР°Р¶РґРѕР№ РёР· СЌС‚РёС… РІРµР»РёС‡РёРЅ.</p>
<pre class="r"><code>correlation &lt;- cov/(sd_A*sd_B)
correlation</code></pre>
<pre><code>## [1] 0.9607689</code></pre>
<p>Р’ РїСЂР°РІРёР»СЊРЅРѕСЃС‚Рё РЅР°С€РёС… РІС‹С‡РёСЃР»РµРЅРёР№ РјРѕР¶РЅРѕ СѓР±РµРґРёС‚СЊСЃСЏ РІРѕСЃРїРѕР»СЊР·РѕРІР°РІС€РёСЃСЊ С„СѓРЅРєС†РёРµР№ cor() СЏР·С‹РєР° R</p>
<pre class="r"><code>cor(A,B)</code></pre>
<pre><code>## [1] 0.9607689</code></pre>
<p>РЎС‚Р°РЅРґР°СЂС‚РЅР°СЏ РєРѕРјР°РЅРґР° РїРѕ РѕС‚РєСЂС‹С‚РёСЋ С„Р°Р№Р»РѕРІ РїРѕР·РІРѕР»СЏРµС‚ С‚РѕС‡РЅРѕ С‚Р°Рє Р¶Рµ РѕС‚РєСЂС‹РІР°С‚СЊ Рё URL РћС‚РєСЂРѕРµРј РґР°РЅРЅС‹Рµ РїРѕ С„РёР·РёС‡РµСЃРєРѕР№ СЃС‚РѕР№РєРѕСЃС‚Рё РІ РїРµСЂРµРјРµРЅРЅСѓСЋ PE</p>
<pre class="r"><code>PE &lt;- read.table(&quot;http://assets.datacamp.com/course/Conway/Lab_Data/Stats1.13.Lab.04.txt&quot;, header=TRUE)</code></pre>
<p>Р’РѕСЃРїРѕР»СЊР·СѓРµРјСЃСЏ С„СѓРЅРєС†РёРµР№ describe РёР· РїР°РєРµС‚Р° psych, РєРѕС‚РѕСЂР°СЏ РґР°РµС‚ РЅР°Рј Р±РѕР»РµРµ РїРѕРґСЂРѕР±РЅСѓСЋ РѕРїРёСЃР°С‚РµР»СЊРЅСѓСЋ СЃС‚Р°С‚РёСЃС‚РёРєСѓ РґР»СЏ РІСЃРµС… РєРѕР»РѕРЅРѕРє С‚Р°Р±Р»РёС†С‹, С‡РµРј СЃС‚Р°РЅРґР°СЂС‚РЅС‹Рµ СЃСЂРµРґСЃС‚РІР°.</p>
<pre class="r"><code>library(&quot;psych&quot;)
describe(PE)</code></pre>
<pre><code>##             vars   n   mean    sd median trimmed   mad min max range skew
## pid            1 200 101.81 58.85  101.5  101.71 74.87   1 204   203 0.01
## age            2 200  49.41 10.48   48.0   49.46 10.38  20  82    62 0.06
## activeyears    3 200  10.68  4.69   11.0   10.57  4.45   0  26    26 0.30
## endurance      4 200  26.50 10.84   27.0   26.22 10.38   3  55    52 0.22
##             kurtosis   se
## pid            -1.21 4.16
## age            -0.14 0.74
## activeyears     0.46 0.33
## endurance      -0.44 0.77</code></pre>
<p>РџРѕСЃС‚СЂРѕРёРј РіСЂР°С„РёРєРё РІР·Р°РёРјРЅРѕР№ Р·Р°РІРёСЃРёРјРѕСЃС‚Рё РїРµСЂРµРјРµРЅРЅС‹С… РІРѕР·СЂР°СЃС‚(age), РєРѕР»РёС‡РµСЃС‚РІРѕ Р»РµС‚ РІ СЃРїРѕСЂС‚Рµ (activeyears) Рё С„РёР·РёС‡РµСЃРєР°СЏ СЃС‚РѕРєР№РѕСЃС‚СЊ(endurance).</p>
<pre class="r"><code>plot(PE$age~PE$activeyears)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>plot(PE$endurance~PE$activeyears)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>plot(PE$endurance~PE$age)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>РџСЂРѕРІРµРґРµРј Р±Р°Р·РѕРІС‹Рµ С‚РµСЃС‚С‹ РєРѕСЂСЂРµР»СЏС†РёРё РґР»СЏ РІСЃРµС… РїРµСЂРµРјРµРЅРЅС‹С…</p>
<pre class="r"><code>round(cor(PE[,-1]), 2)  </code></pre>
<pre><code>##               age activeyears endurance
## age          1.00        0.33     -0.08
## activeyears  0.33        1.00      0.33
## endurance   -0.08        0.33      1.00</code></pre>
<p>РЎРґРµР»Р°РµРј РґРѕРїРѕР»РЅРёС‚РµР»СЊРЅС‹Рµ С‚РµСЃС‚С‹. Р•СЃР»Рё РЅСѓР»РµРІР°СЏ РіРёРїРѕС‚РµР·Р° РѕР± РѕС‚СЃСѓС‚СЃС‚РІРёРё РєРѕСЂРµР»Р»СЏС†РёРё РјРѕР¶РµС‚ Р±С‹С‚СЊ РѕС‚РІРµСЂРіРЅСѓС‚Р° СЃ СѓСЂРѕРІРЅРµРј Р·РЅР°С‡РёРјРѕСЃС‚Рё РІ 5%, С‚Рѕ СЃРІСЏР·СЊ РјРµР¶РґСѓ РїРµСЂРµРјРµРЅРЅС‹РјРё Р·РЅР°С‡РёРјРѕ РѕС‚Р»РёС‡Р°РµС‚СЃСЏ РѕС‚ РЅСѓР»СЏ СЃ 95% РґРѕРІРµСЂРёС‚РµР»СЊРЅС‹Рј РёРЅС‚РµСЂРІР°Р»РѕРј.</p>
<pre class="r"><code>cor.test(PE$age, PE$activeyears)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  PE$age and PE$activeyears
## t = 4.9022, df = 198, p-value = 1.969e-06
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1993491 0.4473145
## sample estimates:
##       cor 
## 0.3289909</code></pre>
<pre class="r"><code>cor.test(PE$age, PE$endurance)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  PE$age and PE$endurance
## t = -1.1981, df = 198, p-value = 0.2323
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.22097811  0.05454491
## sample estimates:
##         cor 
## -0.08483813</code></pre>
<pre class="r"><code>cor.test(PE$endurance, PE$activeyears)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  PE$endurance and PE$activeyears
## t = 4.8613, df = 198, p-value = 2.37e-06
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1967110 0.4451154
## sample estimates:
##       cor 
## 0.3265402</code></pre>
<p>Р’С‹ РґРѕР»Р¶РЅС‹ Р±С‹С‚СЊ РѕСЃС‚РѕСЂРѕР¶РЅС‹ СЃ РёРЅС‚РµСЂРїСЂРµС‚Р°С†РёРµР№ РєРѕСЌС„С„РёС†РёРµРЅС‚РѕРІ РєРѕСЂСЂРµР»СЏС†РёРё РїСЂРё Р°РЅР°Р»РёР·Рµ РЅРµСЂРµРїСЂРµР·РµРЅС‚Р°С‚РёРІРЅРѕРіРѕ РѕР±СЂР°Р·С†РѕРІ. Р’ СЌС‚РѕРј СѓРїСЂР°Р¶РЅРµРЅРёРё РІС‹ СѓР·РЅР°РµС‚Рµ, РєР°Рє СЂР°Р·РґРµР»РёС‚СЊ РЅР°Р±РѕСЂ РґР°РЅРЅС‹С… РЅР° РїРѕРґРјРЅРѕР¶РµСЃС‚РІР° Рё РїРѕСЃРјРѕС‚СЂРµС‚СЊ, РІ РєР°РєРѕР№ СЃС‚РµРїРµРЅРё СЌС‚Рѕ РјРѕР¶РµС‚ РёР·РјРµРЅРёС‚СЊ РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РєРѕСЂСЂРµР»СЏС†РёРё.</p>
<p>Р—Р°РіСЂСѓР·РёРј РґР°РЅРЅС‹Рµ РїРѕ РёСЃСЃР»РµРґРІР°РЅРёСЋ РїРѕСЃР»РµРґСЃС‚РІРёР№ СЃРѕС‚СЂСЏСЃРµРЅРёРµ РіРѕР»РѕРІРЅРѕРіРѕ РјРѕР·РіР°, РІС‹Р·РІС‹РЅРЅС‹С… СЃРІСЏР·Р°РЅРЅС‹РјРё СЃРѕ СЃРїРѕСЂС‚РѕРј С‚СЂР°РІРјР°РјРё, РєРѕС‚РѕСЂРѕРµ РІРєР»СЋС‡Р°РµС‚ РІ СЃРµР±СЏ РґР°РЅРЅС‹Рµ РѕРїСЂРѕСЃР° РєР°Рє РєРѕРЅС‚СЂРѕР»СЊРЅРѕР№ РіСЂСѓРїРїРѕС‹, С‚Р°Рє Рё РіСЂСѓРїРїС‹ СЃРїРѕСЂС‚СЃРјРµРЅРѕРІ, РєРѕС‚РѕСЂС‹Рµ РїРѕСЃС‚СЂР°РґР°Р»Рё РѕС‚ СЃРѕС‚СЂСЏСЃРµРЅРёСЏ.</p>
<pre class="r"><code>impact=read.csv(&quot;https://dl.dropboxusercontent.com/s/7ubjig9z5hmv858/impact.csv?dl=0&quot;)
describe(impact)</code></pre>
<pre><code>## Warning in describe(impact): NAs introduced by coercion</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf</code></pre>
<pre><code>##            vars  n  mean    sd median trimmed   mad   min   max range
## subject       1 40 20.50 11.69  20.50   20.50 14.83  1.00 40.00 39.00
## condition*    2 40   NaN    NA     NA     NaN    NA   Inf  -Inf  -Inf
## vermem1       3 40 89.75  6.44  91.00   90.44  6.67 75.00 98.00 23.00
## vismem1       4 40 74.88  8.60  75.00   74.97  9.64 59.00 91.00 32.00
## vms1          5 40 34.03  3.90  33.50   34.02  3.62 26.29 41.87 15.58
## rt1           6 40  0.67  0.15   0.65    0.66  0.13  0.42  1.20  0.78
## ic1           7 40  8.28  2.05   8.50    8.38  2.22  2.00 12.00 10.00
## sym1          8 40  0.05  0.22   0.00    0.00  0.00  0.00  1.00  1.00
## vermem2       9 40 82.00 11.02  85.00   82.97  9.64 59.00 97.00 38.00
## vismem2      10 40 71.90  8.42  72.00   72.19 10.38 54.00 86.00 32.00
## vms2         11 40 35.83  8.66  35.15   34.98  6.89 20.15 60.77 40.62
## rt2          12 40  0.67  0.22   0.65    0.65  0.13  0.19  1.30  1.11
## ic2          13 40  6.75  2.98   7.00    6.81  2.97  1.00 12.00 11.00
## sym2         14 40 13.88 15.32   7.00   12.38 10.38  0.00 43.00 43.00
##             skew kurtosis   se
## subject     0.00    -1.29 1.85
## condition*    NA       NA   NA
## vermem1    -0.70    -0.51 1.02
## vismem1    -0.11    -0.96 1.36
## vms1        0.08    -0.75 0.62
## rt1         1.14     2.21 0.02
## ic1        -0.57     0.36 0.32
## sym1        3.98    14.16 0.03
## vermem2    -0.65    -0.81 1.74
## vismem2    -0.28    -0.87 1.33
## vms2        0.86     0.65 1.37
## rt2         0.93     1.29 0.03
## ic2        -0.16    -1.06 0.47
## sym2        0.44    -1.47 2.42</code></pre>
<p>РџРѕСЃС‡РёС‚Р°РµРј РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РєРѕСЂРµР»Р»СЏС†РёРё РјРµР¶РґСѓ РєРѕСЌС„С„РёС†РёРµРЅС‚РІРјРё РІРёР·СѓР°Р»СЊРЅРѕР№ Рё РІРµСЂР±Р°Р»СЊРЅРѕР№ РїР°РјСЏС‚Рё РїР°С†РёРµРЅС‚РѕРІ.</p>
<pre class="r"><code>entirecorr &lt;- round(cor(impact$vismem2,impact$vermem2),2)</code></pre>
<p>РЎ РїРѕРјРѕС‰СЊСЋ РєРѕРјР°РЅРґС‹ describeBy РёР· РїР°РєРµС‚Р° psych РїРѕСЃРѕРјС‚СЂРёРј РѕРїРёСЃР°С‚РµР»СЊРЅС‹Рµ СЃС‚Р°С‚РёСЃС‚РёРєРё РґР»СЏ РїРµСЂРµРјРµРЅРЅС‹С… РґР°РЅРЅРѕР№ С‚Р°Р±Р»РёС†С‹, СЃРіСЂСѓРїРїРёСЂРѕРІР°РЅРЅС‹Рµ РїРѕ РєР°С‚РµРіРѕСЂРёСЏРј РїРµСЂРµРјРµРЅРЅРѕР№ condition - СЃРѕСЃС‚РѕСЏРЅРёРµ РѕРїСЂРѕС€РµРЅРЅС‹С…. Рў.Рµ. РїРѕСЃРјРѕС‚СЂРёРј РѕРїРёСЃР°С‚РµР»СЊРЅС‹Рµ СЃС‚Р°С‚РёСЃС‚РёРєРё РґР»СЏ РєРѕРЅС‚СЂРѕР»СЊРЅРѕР№ Рё С†РµР»РµРІРѕР№ РіСЂСѓРїРїС‹.</p>
<pre class="r"><code>describeBy(impact, impact$condition)</code></pre>
<pre><code>## Warning in FUN(data[x, , drop = FALSE], ...): NAs introduced by coercion</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf</code></pre>
<pre><code>## Warning in FUN(data[x, , drop = FALSE], ...): NAs introduced by coercion</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to min; returning
## Inf</code></pre>
<pre><code>## Warning in FUN(newX[, i], ...): no non-missing arguments to max; returning
## -Inf</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: concussed
##            vars  n  mean    sd median trimmed   mad   min   max range
## subject       1 20 30.50  5.92  30.50   30.50  7.41 21.00 40.00 19.00
## condition*    2 20   NaN    NA     NA     NaN    NA   Inf  -Inf  -Inf
## vermem1       3 20 89.65  7.17  92.50   90.56  5.93 75.00 97.00 22.00
## vismem1       4 20 74.75  8.03  74.00   74.25  8.15 63.00 91.00 28.00
## vms1          5 20 33.20  3.62  33.09   33.27  3.32 26.29 39.18 12.89
## rt1           6 20  0.66  0.17   0.63    0.64  0.13  0.42  1.20  0.78
## ic1           7 20  8.55  1.64   9.00    8.62  1.48  5.00 11.00  6.00
## sym1          8 20  0.05  0.22   0.00    0.00  0.00  0.00  1.00  1.00
## vermem2       9 20 74.05  9.86  74.00   73.88 11.86 59.00 91.00 32.00
## vismem2      10 20 69.20  8.38  69.50   69.62 10.38 54.00 80.00 26.00
## vms2         11 20 38.27 10.01  35.15   37.32  7.73 25.70 60.77 35.07
## rt2          12 20  0.78  0.23   0.70    0.74  0.11  0.51  1.30  0.79
## ic2          13 20  5.00  2.53   5.00    4.88  2.97  1.00 11.00 10.00
## sym2         14 20 27.65  9.07  27.00   27.75 11.12 13.00 43.00 30.00
##             skew kurtosis   se
## subject     0.00    -1.38 1.32
## condition*    NA       NA   NA
## vermem1    -0.79    -0.70 1.60
## vismem1     0.45    -0.72 1.80
## vms1       -0.13    -0.78 0.81
## rt1         1.38     2.41 0.04
## ic1        -0.39    -0.81 0.37
## sym1        3.82    13.29 0.05
## vermem2     0.07    -1.24 2.21
## vismem2    -0.27    -1.26 1.87
## vms2        0.77    -0.57 2.24
## rt2         1.09    -0.10 0.05
## ic2         0.39    -0.28 0.57
## sym2       -0.11    -1.25 2.03
## -------------------------------------------------------- 
## group: control
##            vars  n  mean   sd median trimmed  mad   min   max range  skew
## subject       1 20 10.50 5.92  10.50   10.50 7.41  1.00 20.00 19.00  0.00
## condition*    2 20   NaN   NA     NA     NaN   NA   Inf  -Inf  -Inf    NA
## vermem1       3 20 89.85 5.82  90.00   90.31 7.41 78.00 98.00 20.00 -0.41
## vismem1       4 20 75.00 9.34  77.00   75.50 9.64 59.00 88.00 29.00 -0.46
## vms1          5 20 34.86 4.09  34.39   34.85 4.92 27.36 41.87 14.51  0.09
## rt1           6 20  0.67 0.13   0.66    0.67 0.13  0.42  1.00  0.58  0.47
## ic1           7 20  8.00 2.41   7.50    8.12 2.22  2.00 12.00 10.00 -0.41
## sym1          8 20  0.05 0.22   0.00    0.00 0.00  0.00  1.00  1.00  3.82
## vermem2       9 20 89.95 4.36  90.50   90.06 5.19 81.00 97.00 16.00 -0.25
## vismem2      10 20 74.60 7.76  74.50   75.00 8.15 60.00 86.00 26.00 -0.23
## vms2         11 20 33.40 6.44  34.54   33.52 6.30 20.15 44.28 24.13 -0.25
## rt2          12 20  0.57 0.16   0.56    0.57 0.13  0.19  0.90  0.71 -0.16
## ic2          13 20  8.50 2.31   9.00    8.69 1.48  3.00 12.00  9.00 -0.73
## sym2         14 20  0.10 0.31   0.00    0.00 0.00  0.00  1.00  1.00  2.47
##            kurtosis   se
## subject       -1.38 1.32
## condition*       NA   NA
## vermem1       -0.87 1.30
## vismem1       -1.27 2.09
## vms1          -1.19 0.91
## rt1           -0.02 0.03
## ic1           -0.17 0.54
## sym1          13.29 0.05
## vermem2       -1.02 0.97
## vismem2       -1.11 1.73
## vms2          -0.77 1.44
## rt2            0.06 0.04
## ic2           -0.32 0.52
## sym2           4.32 0.07</code></pre>
<p>РЎРґРµР»Р°РµРј 2 РїРѕРґРІС‹Р±РѕСЂРєРё: РєРѕРЅС‚СЂРѕР»СЊ(control) Рё РєРѕРЅС‚СѓР¶РµРЅРЅС‹Рµ(concussed)</p>
<pre class="r"><code>control &lt;- subset(impact, condition==&quot;control&quot;)
concussed &lt;- subset(impact, condition==&quot;concussed&quot;)</code></pre>
<p>РџРѕСЃС‡РёС‚Р°РµРј РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РєРѕСЂСЂРµР»Р»СЏС†РёРё РґР»СЏ РєР°Р¶РґРѕР№ РїРѕРґРІС‹Р±РѕСЂРєРё.</p>
<pre class="r"><code>controlcorr &lt;- round(cor(control$vismem2,control$vermem2),2)
concussedcorr &lt;- round(cor(concussed$vismem2,concussed$vermem2),2)</code></pre>
<p>Р’С‹РІРµРґРµРј РІСЃРµ Р·РЅР°С‡РµРЅРёСЏ РєРѕСЌС„С„РёС†РёРµРЅС‚РѕРІ РєРѕСЂРµР»Р»СЏС†РёРё РѕРґРЅРѕРІСЂРµРјРµРЅРЅРѕ</p>
<pre class="r"><code>correlations &lt;- cbind(entirecorr, controlcorr, concussedcorr)
correlations</code></pre>
<pre><code>##      entirecorr controlcorr concussedcorr
## [1,]       0.45        0.37          0.35</code></pre>
</div>
<div id="section-2" class="section level2">
<h2>Р›РёРЅРµР№РЅР°СЏ СЂРµРіСЂРµСЃСЃРёСЏ. РўРµРѕСЂРёСЏ</h2>
<p>Р’ РєР°С‡РµСЃС‚РІРµ РїСЂРёРјРµСЂР° СЂР°СЃСЃРјРѕС‚СЂРёРј СЃРёСЃС‚РѕР»РёС‡РµСЃРєРѕРµ РєСЂРѕРІСЏРЅРѕРµ РґР°РІР»РµРЅРёРµ Сѓ Р»СЋРґРµР№ (РІС‹СЂР°Р¶Р°РµС‚СЃСЏ РІ РјРј СЂС‚СѓС‚РЅРѕРіРѕ СЃС‚РѕР»Р±Р°). РћС‡РµРІРёРґРЅРѕ, С‡С‚Рѕ СѓСЂРѕРІРµРЅСЊ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ РЅРµ РјРѕР¶РµС‚ Р±С‹С‚СЊ РѕРґРёРЅР°РєРѕРІС‹Рј Сѓ РІСЃРµС… Р»СЋРґРµР№ вЂ“ РїСЂРё РѕР±СЃР»РµРґРѕРІР°РЅРёРё СЃР»СѓС‡Р°Р№РЅРѕ СЃС„РѕСЂРјРёСЂРѕРІР°РЅРЅРѕР№ РІС‹Р±РѕСЂРєРё РјС‹ РїРѕС‡С‚Рё РІСЃРµРіРґР° Р±СѓРґРµРј РЅР°Р±Р»СЋРґР°С‚СЊ РѕРїСЂРµРґРµР»РµРЅРЅС‹Р№ СЂР°Р·Р±СЂРѕСЃ Р·РЅР°С‡РµРЅРёР№ СЌС‚РѕР№ РїРµСЂРµРјРµРЅРЅРѕР№, С…РѕС‚СЏ РЅРµРєРѕС‚РѕСЂС‹Рµ Р·РЅР°С‡РµРЅРёСЏ Р±СѓРґСѓС‚ РІСЃС‚СЂРµС‡Р°С‚СЊСЃСЏ С‡Р°С€Рµ РґСЂСѓРіРёС…. РЎС„РѕСЂРјРёСЂСѓРµРј РІС‹Р±РѕСЂРєСѓ РІРѕР·РјРѕР¶РЅРѕРіРѕ СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ 100 Р·РЅР°С‡РµРЅРёР№ РґР°РІР»РµРЅРёСЏ РєСЂРѕРІРё, (РЅРµ Р±СѓРґРµРј РїРѕРєР° СѓС‚РѕС‡РЅСЏС‚СЊ РјРµС…Р°РЅРёР·Рј РїРѕР»СѓС‡РµРЅРёСЏ РґР°РЅРЅС‹С… Рё РїСЂРµРґРїРѕР»РѕР¶РёРј, С‡С‚Рѕ СЌС‚Рѕ вЂ“ СЂРµР°Р»СЊРЅС‹Рµ РёР·РјРµСЂРµРЅРёСЏ Сѓ СЂРµР°Р»СЊРЅС‹С… СЃР»СѓС‡Р°Р№РЅРѕ РѕС‚РѕР±СЂР°РЅРЅС‹С… Р»СЋРґРµР№, СЂР°Р·Р»РёС‡Р°СЋС‰РёС…СЃСЏ РїРѕ РІРѕР·СЂР°СЃС‚Сѓ, РїРѕР»Сѓ, РјР°СЃСЃРµ С‚РµР»Р° Рё, РІРѕР·РјРѕР¶РЅРѕ, РєР°РєРёРј-С‚Рѕ РґСЂСѓРіРёРј С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРєР°Рј):</p>
<pre class="r"><code>y &lt;- c( 109.14, 117.55, 106.76, 115.26, 117.13, 125.39, 121.03, 114.03, 124.83, 113.92, 122.04, 109.41, 131.61, 103.93, 116.64, 117.06, 111.73, 120.41, 112.98, 101.20, 120.19, 128.53, 120.14, 108.70, 130.77, 110.16, 129.07, 123.46, 130.02, 130.31, 135.06, 129.17, 137.08, 107.62, 139.77, 121.47, 130.95, 138.15, 114.31, 134.58, 135.86, 138.49, 110.01, 127.80, 122.57, 136.99, 139.53, 127.34, 132.26, 120.85, 124.99, 133.36, 142.46, 123.58, 145.05, 127.83, 140.42, 149.64, 151.01, 135.69, 138.25, 127.24, 135.55, 142.76, 146.67, 146.33, 137.00, 145.00, 143.98, 143.81, 159.92, 160.97, 157.45, 145.68, 129.98, 137.45, 151.22, 136.10, 150.60, 148.79, 167.93, 160.85, 146.28, 145.97, 135.59, 156.62, 153.12, 165.96, 160.94, 168.87, 167.64, 154.64, 152.46, 149.03, 159.56, 149.31, 153.56, 170.87, 163.52, 150.97)

c(mean(y), sd(y)) # СЃСЂРµРґРЅРµРµ Р·РЅР°С‡РµРЅРёРµ Рё СЃС‚Р°РЅРґ. РѕС‚РєР»РѕРЅРµРЅРёРµ</code></pre>
<pre><code>## [1] 135.15730  16.96017</code></pre>
<pre class="r"><code>shapiro.test(y)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  y
## W = 0.98263, p-value = 0.2121</code></pre>
<pre class="r"><code>library(ggplot2) # РіСЂР°С„РёС‡РµСЃРєРѕРµ РёР·РѕР±СЂР°Р¶РµРЅРёРµ СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ РґР°РЅРЅС‹С…</code></pre>
<pre class="r"><code>ggplot(data = data.frame(y), aes(x = y)) + geom_histogram() +
ylab(&quot;Р§Р°СЃС‚РѕС‚Р°&quot;) + xlab(&quot;Р”Р°РІР»РµРЅРёРµ, РјРј СЂС‚. СЃС‚.&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Р“СЂРµС‡РµСЃРєРёРµ Р±СѓРєРІС‹ Ој Рё Пѓ РѕР±РѕР·РЅР°С‡Р°СЋС‚ РёСЃС‚РёРЅРЅС‹Рµ (С‚Р°РєР¶Рµ”РіРµРЅРµСЂР°Р»СЊРЅС‹Рµ“) РїР°СЂР°РјРµС‚СЂС‹ РјРѕРґРµР»Рё, РєРѕС‚РѕСЂС‹Рµ, РєР°Рє РїСЂР°РІРёР»Рѕ, РЅР°Рј РЅРµРёР·РІРµСЃС‚РЅС‹. РўРµРј РЅРµ РјРµРЅРµРµ, РјС‹ РјРѕР¶РµРј РѕС†РµРЅРёС‚СЊ Р·РЅР°С‡РµРЅРёСЏ РїР°СЂР°РјРµС‚СЂРѕРІ РїРѕ СЃРѕРѕС‚РІРµС‚СЃС‚РІСѓСЋС‰РёРј РІС‹Р±РѕСЂРѕС‡РЅС‹Рј СЃС‚Р°С‚РёСЃС‚РёРєР°Рј. РўР°Рє, РІ СЃР»СѓС‡Р°Рµ РїСЂРµРґСЃС‚Р°РІР»РµРЅРЅС‹С… РІС‹С€Рµ 100 Р·РЅР°С‡РµРЅРёР№ СЃРёСЃС‚РѕР»РёС‡РµСЃРєРѕРіРѕ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ РІС‹Р±РѕСЂРѕС‡РЅС‹Рµ СЃСЂРµРґРЅРµРµ Р·РЅР°С‡РµРЅРёРµ Рё СЃС‚Р°РЅРґР°СЂС‚РЅРѕРµ РѕС‚РєР»РѕРЅРµРЅРёРµ СЃРѕСЃС‚Р°РІР»СЏСЋС‚ 135.16 РјРј СЂС‚. СЃС‚. Рё 16.96 РјРј СЂС‚. СЃС‚. СЃРѕРѕС‚РІРµС‚СЃС‚РІРµРЅРЅРѕ. Р”РѕРїСѓСЃРєР°СЏ, С‡С‚Рѕ РґР°РЅРЅС‹Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅРѕ РїСЂРѕРёСЃС…РѕРґСЏС‚ РёР· РЅРѕСЂРјР°Р»СЊРЅРѕ СЂР°СЃРїСЂРµРґРµР»РµРЅРЅРѕР№ РіРµРЅРµСЂР°Р»СЊРЅРѕР№ СЃРѕРІРѕРєСѓРїРЅРѕСЃС‚Рё, РјС‹ РјРѕР¶РµРј Р·Р°РїРёСЃР°С‚СЊ РЅР°С€Сѓ РјРѕРґРµР»СЊ РІ РІРёРґРµ yi ~ N(135.16, 16.96). Р­С‚Сѓ РјРѕРґРµР»СЊ РјРѕР¶РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РґР»СЏ РїСЂРµРґСЃРєР°Р·Р°РЅРёСЏ РґР°РІР»РµРЅРёСЏ РєСЂРѕРІРё, РѕРґРЅР°РєРѕ РґР»СЏ РІСЃРµС… Р»СЋРґРµР№ РїСЂРµРґСЃРєР°Р·Р°РЅРЅРѕРµ Р·РЅР°С‡РµРЅРёРµ РѕРєР°Р¶РµС‚СЃСЏ РѕРґРёРЅР°РєРѕРІС‹Рј Рё Р±СѓРґРµС‚ СЂР°РІРЅРѕ Ој.РћР±С‹С‡РЅС‹Рј СЃРїРѕСЃРѕР±РѕРј Р·Р°РїРёСЃРё СЌС‚РѕР№ РјРѕРґРµР»Рё СЏРІР»СЏРµС‚СЃСЏ СЃР»РµРґСѓСЋС‰РёР№: <span class="math inline">\(y{i} = 135.16 + \epsilon{i}\)</span> , РіРґРµ ei вЂ“ СЌС‚Рѕ РѕСЃС‚Р°С‚РєРё РјРѕРґРµР»Рё, РёРјРµСЋС‰РёРµ РЅРѕСЂРјР°Р»СЊРЅРѕРµ СЂР°СЃРїСЂРµРґРµР»РµРЅРёРµ СЃРѕ СЃСЂРµРґРЅРёРј Р·РЅР°С‡РµРЅРёРµРј 0 Рё СЃС‚Р°РЅРґР°СЂС‚РЅС‹Рј РѕС‚РєР»РѕРЅРµРЅРёРµРј 16.96: ei ~ N(0, 16.96). РћСЃС‚Р°С‚РєРё СЂР°СЃСЃС‡РёС‚С‹РІР°СЋС‚СЃСЏ РєР°Рє СЂР°Р·РЅРёС†Р° РјРµР¶РґСѓ СЂРµР°Р»СЊРЅРѕ РЅР°Р±Р»СЋРґР°РµРјС‹РјРё Р·РЅР°С‡РµРЅРёСЏРјРё РїРµСЂРµРјРµРЅРЅРѕР№ Y Рё Р·РЅР°С‡РµРЅРёСЏРјРё, РїСЂРµРґСЃРєР°Р·Р°РЅРЅС‹РјРё РјРѕРґРµР»СЊСЋ (РІ СЂР°СЃСЃРјР°С‚СЂРёРІР°РµРјРѕРј РїСЂРёРјРµСЂРµ ei = yi - 135.16). РЎ РґСЂСѓРіРѕР№ СЃС‚РѕСЂРѕРЅС‹ СЌС‚Р° Р·Р°РїРёСЃСЊ РїСЂРµРґСЃС‚Р°РІР»СЏРµС‚ СЃРѕР±РѕР№ РЅРё С‡С‚Рѕ РёРЅРѕРµ, РєР°Рє Р»РёРЅРµР№РЅСѓСЋ СЂРµРіСЂРµСЃСЃРёРѕРЅРЅСѓСЋ РјРѕРґРµР»СЊ, Сѓ РєРѕС‚РѕСЂРѕР№ РЅРµС‚ РЅРё РѕРґРЅРѕРіРѕ РїСЂРµРґРёРєС‚РѕСЂР°, Рё РєРѕС‚РѕСЂСѓСЋ С‡Р°СЃС‚Рѕ РЅР°Р·С‹РІР°СЋС‚ В«РЅСѓР»СЊ-РјРѕРґРµР»СЊСЋВ» РёР»Рё В«РЅСѓР»РµРІРѕР№ РјРѕРґРµР»СЊСЋВ» (Р°РЅРіР». null models).</p>
<div id="simulation--..-----------------------." class="section level4">
<h4>Р’ СЃСѓС‰РЅРѕСЃС‚Рё, СЃС‚Р°С‚РёСЃС‚РёС‡РµСЃРєР°СЏ РјРѕРґРµР»СЊ вЂ“ СЌС‚Рѕ СѓРїСЂРѕС‰РµРЅРЅРѕРµ РјР°С‚РµРјР°С‚РёС‡РµСЃРєРѕРµ РїСЂРµРґСЃС‚Р°РІР»РµРЅРёРµ РїСЂРѕС†РµСЃСЃР°, РєРѕС‚РѕСЂС‹Р№, РєР°Рє РјС‹ РїРѕР»Р°РіР°РµРј, РїСЂРёРІРµР» Рє РіРµРЅРµСЂР°С†РёРё РЅР°Р±Р»СЋРґР°РµРјС‹С… Р·РЅР°С‡РµРЅРёР№ РёР·СѓС‡Р°РµРјРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№. Р­С‚Рѕ Р·РЅР°С‡РёС‚, С‡С‚Рѕ РјС‹ РјРѕР¶РµРј РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РјРѕРґРµР»СЊ РґР»СЏ СЃРёРјСѓР»СЏС†РёРё (simulation) вЂ“ С‚.Рµ. РїСЂРѕС†РµРґСѓСЂС‹, РёРјРёС‚РёСЂСѓСЋС‰РµР№ РјРѕРґРµР»РёСЂСѓРµРјС‹Р№ РїСЂРѕС†РµСЃСЃ Рё РїРѕР·РІРѕР»СЏСЋС‰РµР№ С‚РµРј СЃР°РјС‹Рј РёСЃРєСѓСЃСЃС‚РІРµРЅРЅРѕ РіРµРЅРµСЂРёСЂРѕРІР°С‚СЊ РЅРѕРІС‹Рµ Р·РЅР°С‡РµРЅРёСЏ РёР·СѓС‡Р°РµРјРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№, РєРѕС‚РѕСЂС‹Рµ, РєР°Рє РјС‹ РЅР°РґРµРµРјСЃСЏ, Р±СѓРґСѓС‚ РѕР±Р»Р°РґР°С‚СЊ СЃРІРѕР№СЃС‚РІР°РјРё СЂРµР°Р»СЊРЅС‹С… РґР°РЅРЅС‹С….</h4>
<p>РќРѕРІС‹Рµ РґР°РЅРЅС‹Рµ РЅР° РѕСЃРЅРѕРІРµ СЌС‚РѕР№ РїСЂРѕСЃС‚РѕР№ РјРѕРґРµР»Рё РјРѕР¶РЅРѕ Р»РµРіРєРѕ СЃРіРµРЅРµСЂРёСЂРѕРІР°С‚СЊ РІ R РїСЂРё РїРѕРјРѕС‰Рё С„СѓРЅРєС†РёРё rnorm():</p>
<pre class="r"><code>set.seed(101) # РґР»СЏ РІРѕСЃРїСЂРѕРёР·РІРѕРґРёРјРѕСЃС‚Рё СЂРµР·СѓР»СЊС‚Р°С‚Р°
y.new.1 &lt;- rnorm(n = 100, mean = 135.16, sd = 16.96)

set.seed(101)
y.new.2 &lt;- 135.16 + rnorm(n = 100, mean = 0, sd = 16.96)</code></pre>
<p>РџСЂРѕРІРµСЂРёРј, РёРґРµРЅС‚РёС‡РЅС‹ Р»Рё РѕР±Р° РІРµРєС‚РѕСЂР°?</p>
<pre class="r"><code>all(y.new.1 == y.new.2)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>РўРµРїРµСЂСЊ РЅРµРѕР±С…РѕРґРёРјРѕ РІСЃРїРѕРјРЅРёС‚СЊ Рѕ С‚РѕРј, С‡С‚Рѕ РїР°СЂР°РјРµС‚СЂС‹ РЅР°С€РµР№ РЅСѓР»РµРІРѕР№ РјРѕРґРµР»Рё СЏРІР»СЏСЋС‚СЃСЏ Р»РёС€СЊ С‚РѕС‡РµС‡РЅС‹РјРё РѕС†РµРЅРєР°РјРё РёСЃС‚РёРЅРЅС‹С… РїР°СЂР°РјРµС‚СЂРѕРІ, Рё С‡С‚Рѕ РІСЃРµРіРґР° Р±СѓРґРµС‚ РїСЂРёСЃСѓС‚СЃС‚РІРѕРІР°С‚СЊ РЅРµРѕРїСЂРµРґРµР»РµРЅРЅРѕСЃС‚СЊ РІ РѕС‚РЅРѕС€РµРЅРёРё С‚РѕРіРѕ, РЅР°СЃРєРѕР»СЊРєРѕ С‚РѕС‡РЅС‹ СЌС‚Рё С‚РѕС‡РµС‡РЅС‹Рµ РІС‹Р±РѕСЂРѕС‡РЅС‹Рµ РѕС†РµРЅРєРё. Р’ РїСЂРёРІРµРґРµРЅРЅС‹С… РІС‹С€Рµ РєРѕРјР°РЅРґР°С… СЌС‚Р° РЅРµРѕРїСЂРµРґРµР»РµРЅРЅРѕСЃС‚СЊ РЅРµ Р±С‹Р»Р° СѓС‡С‚РµРЅР°: РїСЂРё СЃРѕР·РґР°РЅРёРё РІРµРєС‚РѕСЂРѕРІ y.new.1 Рё y.new.2 РІС‹Р±РѕСЂРѕС‡РЅС‹Рµ РѕС†РµРЅРєРё СЃСЂРµРґРЅРµРіРѕ Р·РЅР°С‡РµРЅРёСЏ Рё СЃС‚Р°РЅРґР°СЂС‚РЅРѕРіРѕ РѕС‚РєР»РѕРЅРµРЅРёСЏ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ СЂР°СЃСЃРјР°С‚СЂРёРІР°Р»РёСЃСЊ РєР°Рє РїР°СЂР°РјРµС‚СЂС‹ РіРµРЅРµСЂР°Р»СЊРЅРѕР№ СЃРѕРІРѕРєСѓРїРЅРѕСЃС‚Рё. Р’ Р·Р°РІРёСЃРёРјРѕСЃС‚Рё РѕС‚ РїРѕСЃС‚Р°РІР»РµРЅРЅРѕР№ Р·Р°РґР°С‡Рё, С‚Р°РєРѕР№ РїРѕРґС…РѕРґ РјРѕР¶РµС‚ РѕРєР°Р·Р°С‚СЊСЃСЏ РґРѕСЃС‚Р°С‚РѕС‡РЅС‹Рј. РћРґРЅР°РєРѕ РјС‹ СЃРґРµР»Р°РµРј РµС‰Рµ РѕРґРёРЅ С€Р°Рі Рё РїРѕСЃС‚Р°СЂР°РµРјСЃСЏ СѓС‡РµСЃС‚СЊ РЅРµРѕРїСЂРµРґРµР»РµРЅРЅРѕСЃС‚СЊ РІ РѕС‚РЅРѕС€РµРЅРёРё С‚РѕС‡РµС‡РЅС‹С… РѕС†РµРЅРѕРє РїР°СЂР°РјРµС‚СЂРѕРІ РјРѕРґРµР»Рё. РџСЂРё РїСЂРѕРІРµРґРµРЅРёРё РёРјРёС‚Р°С†РёР№ РІРѕСЃРїРѕР»СЊР·СѓРµРјСЃСЏ С„СѓРЅРєС†РёРµР№ lm(), РєРѕС‚РѕСЂР°СЏ РїСЂРµРґРЅР°Р·РЅР°С‡РµРЅР° РґР»СЏ РїРѕРґРіРѕРЅРєРё Р»РёРЅРµР№РЅС‹С… СЂРµРіСЂРµСЃСЃРёРѕРЅРЅС‹С… РјРѕРґРµР»РµР№. РќРёС‡РµРіРѕ СѓРґРёРІРёС‚РµР»СЊРЅРѕРіРѕ Р·РґРµСЃСЊ РЅРµС‚ вЂ“ РІРµРґСЊ РјС‹ СѓР¶Рµ Р·РЅР°РµРј, С‡С‚Рѕ РЅР°С€Сѓ РїСЂРѕСЃС‚СѓСЋ РјРѕРґРµР»СЊ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ РјРѕР¶РЅРѕ СЂР°СЃСЃРјР°С‚СЂРёРІР°С‚СЊ РєР°Рє Р»РёРЅРµР№РЅСѓСЋ СЂРµРіСЂРµСЃСЃРёРѕРЅРЅСѓСЋ РјРѕРґРµР»СЊ, Сѓ РєРѕС‚РѕСЂРѕР№ РЅРµС‚ РЅРё РѕРґРЅРѕРіРѕ РїСЂРµРґРёРєС‚РѕСЂР°:</p>
<pre class="r"><code>y.lm &lt;- lm(y ~ 1) # С„РѕСЂРјСѓР»Р° РґР»СЏ РѕС†РµРЅРєРё С‚РѕР»СЊРєРѕ СЃРІРѕР±РѕРґРЅРѕРіРѕ С‡Р»РµРЅР°
summary(y.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = y ~ 1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.957 -13.260   0.413  12.043  35.713 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  135.157      1.696   79.69   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.96 on 99 degrees of freedom</code></pre>
<p>РљР°Рє СЃР»РµРґСѓРµС‚ РёР· РїСЂРёРІРµРґРµРЅРЅС‹С… СЂРµР·СѓР»СЊС‚Р°С‚РѕРІ, СЃРІРѕР±РѕРґРЅС‹Р№ С‡Р»РµРЅ РїРѕРґРѕРіРЅР°РЅРЅРѕР№ РјРѕРґРµР»Рё (Intercept) РІ С‚РѕС‡РЅРѕСЃС‚Рё СЃРѕРІРїР°РґР°РµС‚ СЃРѕ СЃСЂРµРґРЅРёРј Р·РЅР°С‡РµРЅРёРµРј РґР°РЅРЅС‹С… (135.16 РјРј СЂС‚. СЃС‚.), Р° СЃС‚Р°РЅРґР°СЂС‚РЅРѕРµ РѕС‚РєР»РѕРЅРµРЅРёРµ РѕСЃС‚Р°С‚РєРѕРІ РјРѕРґРµР»Рё (Residual standard error) СЃРѕРІРїР°РґР°РµС‚ СЃРѕ СЃС‚Р°РЅРґР°СЂС‚РЅС‹Рј РѕС‚РєР»РѕРЅРµРЅРёРµРј СЌС‚РёС… РґР°РЅРЅС‹С… (16.96 РјРј СЂС‚. СЃС‚.). Р’Р°Р¶РЅРѕ, РѕРґРЅР°РєРѕ, С‡С‚Рѕ РјС‹ РїСЂРё СЌС‚РѕРј РІС‹С‡РёСЃР»РёР»Рё С‚Р°РєР¶Рµ РѕС†РµРЅРєСѓ СЃС‚Р°РЅРґР°СЂС‚РЅРѕР№ РѕС€РёР±РєРё СЃСЂРµРґРЅРµРіРѕ Р·РЅР°С‡РµРЅРёСЏ, СЂР°РІРЅСѓСЋ 1.696 (СЃРј. СЃС‚РѕР»Р±РµС† Std. Error РЅР° РїРµСЂРµСЃРµС‡РµРЅРёРё СЃРѕ СЃС‚СЂРѕРєРѕР№ (Intercept)). РџРѕ РѕРїСЂРµРґРµР»РµРЅРёСЋ, СЃС‚Р°РЅРґР°СЂС‚РЅР°СЏ РѕС€РёР±РєР° РїР°СЂР°РјРµС‚СЂР° вЂ“ СЌС‚Рѕ СЃС‚Р°РЅРґР°СЂС‚РЅРѕРµ РѕС‚РєР»РѕРЅРµРЅРёРµ <span class="math display">\[РЅРѕСЂРјР°Р»СЊРЅРѕРіРѕ\]</span> СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ Р·РЅР°С‡РµРЅРёР№ СЌС‚РѕРіРѕ РїР°СЂР°РјРµС‚СЂР°, СЂР°СЃСЃС‡РёС‚Р°РЅРЅС‹С… РїРѕ РІС‹Р±РѕСЂРєР°Рј РѕРґРёРЅР°РєРѕРІРѕРіРѕ СЂР°Р·РјРµСЂР° РёР· С‚РѕР№ Р¶Рµ РіРµРЅРµСЂР°Р»СЊРЅРѕР№ СЃРѕРІРѕРєСѓРїРЅРѕСЃС‚Рё. РњС‹ РјРѕР¶РµРј РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ СЌС‚Рѕ РѕР±СЃС‚РѕСЏС‚РµР»СЊСЃС‚РІРѕ РґР»СЏ СѓС‡РµС‚Р° РЅРµРѕРїСЂРµРґРµР»РµРЅРЅРѕСЃС‚Рё РІ РѕС‚РЅРѕС€РµРЅРёРё С‚РѕС‡РµС‡РЅС‹С… РѕС†РµРЅРѕРє РїР°СЂР°РјРµС‚СЂРѕРІ РјРѕРґРµР»Рё РїСЂРё РїРѕСЂРѕР¶РґРµРЅРёРё РЅРѕРІС‹С… РґР°РЅРЅС‹С…. РўР°Рє, Р·РЅР°СЏ РІС‹Р±РѕСЂРѕС‡РЅС‹Рµ РѕС†РµРЅРєРё РїР°СЂР°РјРµС‚СЂРѕРІ Рё РёС… СЃС‚Р°РЅРґР°СЂС‚РЅС‹Рµ РѕС€РёР±РєРё, РјС‹ РјРѕР¶РµРј: Р°) СЃРіРµРЅРµСЂРёСЂРѕРІР°С‚СЊ РЅРµСЃРєРѕР»СЊРєРѕ РІРѕР·РјРѕР¶РЅС‹С… Р·РЅР°С‡РµРЅРёР№ СЌС‚РёС… РїР°СЂР°РјРµС‚СЂРѕРІ (С‚.Рµ. СЃРѕСЃС‚Р°РІРёС‚СЊ РЅРµСЃРєРѕР»СЊРєРѕ СЂРµР°Р»РёР·Р°С†РёР№ С‚РѕР№ Р¶Рµ РјРѕРґРµР»Рё, РІР°СЂСЊРёСЂСѓСЏ Р·РЅР°С‡РµРЅРёСЏ РїР°СЂР°РјРµС‚СЂРѕРІ) Рё Р±) СЃРіРµРЅРµСЂРёСЂРѕРІР°С‚СЊ РЅРѕРІС‹Рµ РґР°РЅРЅС‹Рµ РЅР° РѕСЃРЅРѕРІРµ РєР°Р¶РґРѕР№ РёР· СЌС‚РёС… Р°Р»СЊС‚РµСЂРЅР°С‚РёРІРЅС‹С… СЂРµР°Р»РёР·Р°С†РёР№ РјРѕРґРµР»Рё.</p>
<pre class="r"><code>library(arm)</code></pre>
<pre class="r"><code>set.seed(102) # РґР»СЏ РІРѕСЃРїСЂРѕРёР·РІРѕРґРёРјРѕСЃС‚Рё СЂРµР·СѓР»СЊС‚Р°С‚Р°
y.sim &lt;- sim(y.lm, 5)</code></pre>
<p>y.sim - РѕР±СЉРµРєС‚ РєР»Р°СЃСЃР° S4, РєРѕС‚РѕСЂС‹Р№ СЃРѕРґРµСЂР¶РёС‚ СЃР»РѕС‚С‹ coef (РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РјРѕРґРµР»Рё) Рё sigma (СЃС‚Р°РЅРґ. РѕС‚РєР»РѕРЅРµРЅРёСЏ РѕСЃС‚Р°С‚РєРѕРІ РјРѕРґРµР»Рё):</p>
<pre class="r"><code>str(y.sim)</code></pre>
<pre><code>## Formal class &#39;sim&#39; [package &quot;arm&quot;] with 2 slots
##   ..@ coef : num [1:5, 1] 136 134 137 136 137
##   .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. ..$ : NULL
##   .. .. ..$ : chr &quot;(Intercept)&quot;
##   ..@ sigma: num [1:5] 16.8 18.9 17.3 16.7 15</code></pre>
<p>РР·РІР»РµРєР°РµРј Р°Р»СЊС‚РµСЂРЅР°С‚РёРІРЅС‹Рµ СЂРµР°Р»РёР·Р°С†РёРё СЃСЂРµРґРЅРµРіРѕ РёР· y.sim:</p>
<pre class="r"><code>y.sim@coef</code></pre>
<pre><code>##      (Intercept)
## [1,]    136.4780
## [2,]    134.3288
## [3,]    136.7079
## [4,]    136.0775
## [5,]    137.3250</code></pre>
<p>РР·РІР»РµРєР°РµРј Р°Р»СЊС‚РµСЂРЅР°С‚РёРІРЅС‹Рµ СЂРµР°Р»РёР·Р°С†РёРё СЃС‚.РѕС‚РєР»РѕРЅРµРЅРёР№ РѕСЃС‚Р°С‚РєРѕРІ:</p>
<pre class="r"><code>y.sim@sigma</code></pre>
<pre><code>## [1] 16.82947 18.87039 17.30262 16.74308 15.00630</code></pre>
<p>РљРѕРЅРµС‡РЅРѕ, 5 СЂРµР°Р»РёР·Р°С†РёР№ РјРѕРґРµР»Рё вЂ“ СЌС‚Рѕ СЃРѕРІРµСЂС€РµРЅРЅРѕ РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ, С‡С‚РѕР±С‹ СЃРґРµР»Р°С‚СЊ РєР°РєРёРµ-Р»РёР±Рѕ СѓР±РµРґРёС‚РµР»СЊРЅС‹Рµ РІС‹РІРѕРґС‹. РЈРІРµР»РёС‡РёРј СЌС‚Рѕ С‡РёСЃР»Рѕ РґРѕ 1000:</p>
<pre class="r"><code>set.seed(102) # РґР»СЏ РІРѕСЃРїСЂРѕРёР·РІРѕРґРёРјРѕСЃС‚Рё СЂРµР·СѓР»СЊС‚Р°С‚Р°
y.sim &lt;- sim(y.lm, 1000)</code></pre>
<p>РРЅРёС†РёР°Р»РёР·Р°С†РёСЏ РїСѓСЃС‚РѕР№ РјР°С‚СЂРёС†С‹, РІ РєРѕС‚РѕСЂРѕР№ РјС‹ Р±СѓРґРµРј СЃРѕС…СЂР°РЅСЏС‚СЊ РґР°РЅРЅС‹Рµ, СЃРіРµРЅРµСЂРёСЂРѕРІР°РЅРЅС‹Рµ РЅР° РѕСЃРЅРѕРІРµ 1000 Р°Р»СЊС‚РµСЂРЅР°С‚РёРІРЅС‹С… СЂРµР°Р»РёР·Р°С†РёР№ РјРѕРґРµР»Рё:</p>
<pre class="r"><code>y.rep &lt;- array(NA, c(1000, 100))
# Р—Р°РїРѕР»РЅСЏРµРј РјР°С‚СЂРёС†Сѓ y.rep РёРјРёС‚РёСЂРѕРІР°РЅРЅС‹РјРё РґР°РЅРЅС‹РјРё:
for(s in 1:1000){
y.rep[s, ] &lt;- rnorm(100, y.sim@coef[s], y.sim@sigma[s])
}</code></pre>
<p>Р§С‚РѕР±С‹ Р»СѓС‡С€Рµ РїРѕРЅСЏС‚СЊ, С‡С‚Рѕ РјС‹ С‚РѕР»СЊРєРѕ С‡С‚Рѕ СЃРґРµР»Р°Р»Рё, РёР·РѕР±СЂР°Р·РёРј РіРёСЃС‚РѕРіСЂР°РјРјС‹ РІС‹Р±РѕСЂРѕС‡РЅС‹С… СЂР°СЃРїСЂРµРґРµР»РµРЅРёР№ Р·РЅР°С‡РµРЅРёР№ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ, СЃРіРµРЅРµСЂРёСЂРѕРІР°РЅРЅС‹С… РЅР° РѕСЃРЅРѕРІРµ, РЅР°РїСЂРёРјРµСЂ, РїРµСЂРІС‹С… 12 СЂРµР°Р»РёР·Р°С†РёР№ РЅСѓР»РµРІРѕР№ РјРѕРґРµР»Рё:</p>
<pre class="r"><code>par(mfrow = c(5, 4), mar = c(2, 2, 1, 1))
for(s in 1: 12){ hist(y.rep[s, ], xlab = &quot;&quot;, ylab = &quot;&quot;,
breaks = 20, main = &quot;&quot;)}</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Р Р°СЃСЃС‡РёС‚Р°РµРј РёРЅС‚РµСЂРєРІР°СЂС‚РёР»СЊРЅС‹Р№ СЂР°Р·РјР°С… (РРљР ) РґР»СЏ РєР°Р¶РґРѕРіРѕ РёРјРёС‚РёСЂРѕРІР°РЅРЅРѕРіРѕ РЅР°Р±РѕСЂР° РґР°РЅРЅС‹С… Рё СЃСЂР°РІРЅРёРј РїРѕР»СѓС‡РµРЅРЅРѕРµ СЂР°СЃРїСЂРµРґРµР»РµРЅРёРµ РёР· 1000 Р·РЅР°С‡РµРЅРёР№ СЃ РРљР  СЂРµР°Р»СЊРЅС‹С… РґР°РЅРЅС‹С…. Р”Р»СЏ СЂР°СЃС‡РµС‚Р° РРљР  РІ R СЃР»СѓР¶РёС‚ С„СѓРЅРєС†РёСЏ IQR():</p>
<pre class="r"><code>test.IQR &lt;- apply(y.rep, MARGIN = 1, FUN = IQR)</code></pre>
<p>Р’С‹РІРµРґРµРј РіРёСЃС‚РѕРіСЂР°РјРјСѓ Р·РЅР°С‡РµРЅРёР№ РРљР , СЂР°СЃСЃС‡РёС‚Р°РЅРЅС‹С… РґР»СЏ РєР°Р¶РґРѕРіРѕ РёР· 1000 РёРјРёС‚РёСЂРѕРІР°РЅРЅС‹С… СЂР°СЃРїСЂРµРґРµР»РµРЅРёР№ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ. Р’РµСЂС‚РёРєР°Р»СЊРЅРѕР№ СЃРёРЅРµР№ Р»РёРЅРёРµР№ РїРѕРєР°Р¶РµРј РРљР  РґР»СЏ СЂРµР°Р»СЊРЅРѕ РЅР°Р±Р»СЋРґР°РµРјС‹С… Р·РЅР°С‡РµРЅРёР№ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ:</p>
<pre class="r"><code>hist(test.IQR, xlim = range(IQR(y), test.IQR), main = &quot;РРљР &quot;, xlab = &quot;&quot;, ylab = &quot;Р§Р°СЃС‚РѕС‚Р°&quot;, breaks = 20) 
lines(rep(IQR(y), 2), c(0, 100), col = &quot;blue&quot;, lwd = 4)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>РќР° РїСЂРёРІРµРґРµРЅРЅРѕРј СЂРёСЃСѓРЅРєРµ С…РѕСЂРѕС€Рѕ РІРёРґРЅРѕ, С‡С‚Рѕ Р·РЅР°С‡РµРЅРёСЏ РРљР  РґР»СЏ РёРјРёС‚РёСЂРѕРІР°РЅРЅС‹С… РґР°РЅРЅС‹С… СЃРёСЃС‚РµРјР°С‚РёС‡РµСЃРєРё Р·Р°РЅРёР¶РµРЅС‹ РїРѕ СЃСЂР°РІРЅРµРЅРёСЋ СЃ СЂРµР°Р»СЊРЅС‹РјРё РґР°РЅРЅС‹РјРё. Р­С‚Рѕ СЃРІРёРґРµС‚РµР»СЊСЃС‚РІСѓРµС‚ Рѕ С‚РѕРј, С‡С‚Рѕ РЅСѓР»РµРІР°СЏ РјРѕРґРµР»СЊ РІ С†РµР»РѕРј РЅРµРґРѕРѕС†РµРЅРёРІР°РµС‚ СѓСЂРѕРІРµРЅСЊ РІР°СЂРёР°С†РёРё СЂРµР°Р»СЊРЅС‹С… Р·РЅР°С‡РµРЅРёР№ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ. РџСЂРёС‡РёРЅРѕР№ СЌС‚РѕРјСѓ РјРѕР¶РµС‚ Р±С‹С‚СЊ С‚Рѕ, С‡С‚Рѕ РјС‹ РЅРµ СѓС‡РёС‚С‹РІР°РµРј РІРѕР·РґРµР№СЃС‚РІРёРµ РЅР° РєСЂРѕРІСЏРЅРѕРµ РґР°РІР»РµРЅРёРµ РєР°РєРёС…-Р»РёР±Рѕ РІР°Р¶РЅС‹С… С„Р°РєС‚РѕСЂРѕРІ (РЅР°РїСЂРёРјРµСЂ, РІРѕР·СЂР°СЃС‚, РїРѕР», РґРёРµС‚Р°, СЃРѕСЃС‚РѕСЏРЅРёРµ Р·РґРѕСЂРѕРІСЊСЏ, Рё С‚.Рї.). Р Р°СЃСЃРјРѕС‚СЂРёРј, РєР°Рє РјРѕР¶РЅРѕ СЂР°СЃС€РёСЂРёС‚СЊ РЅР°С€Сѓ РЅСѓР»РµРІСѓСЋ РјРѕРґРµР»СЊ, РґРѕР±Р°РІРёРІ РІ РЅРµРµ РѕРґРёРЅ РёР· С‚Р°РєРёС… С„Р°РєС‚РѕСЂРѕРІ.</p>
<p>РџСЂРµРґРїРѕР»РѕР¶РёРј, С‡С‚Рѕ РїРѕРјРёРјРѕ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ РјС‹ С‚Р°РєР¶Рµ РёР·РјРµСЂСЏР»Рё Сѓ РєР°Р¶РґРѕРіРѕ РёСЃРїС‹С‚СѓРµРјРѕРіРѕ РµРіРѕ/РµРµ РІРѕР·СЂР°СЃС‚ (РІ РіРѕРґР°С…). РџРѕРєР°Р¶РµРј РіСЂР°С„РёС‡РµСЃРєРё СЃРІСЏР·СЊ РјРµР¶РґСѓ РІРѕР·СЂР°СЃС‚РѕРј Рё СЃРёСЃС‚РѕР»РёС‡РµСЃРєРёРј РєСЂРѕРІСЏРЅС‹Рј РґР°РІР»РµРЅРёРµРј. Р”Р»СЏ РІРёР·СѓР°Р»РёР·Р°С†РёРё С‚СЂРµРЅРґР° РІ РґР°РЅРЅС‹С… РґРѕР±Р°РІРёРј Р»РёРЅРёСЋ СЂРµРіСЂРµСЃСЃРёРё СЃРёРЅРµРіРѕ С†РІРµС‚Р°:</p>
<pre class="r"><code># Р—РЅР°С‡РµРЅРёСЏ РІРѕР·СЂР°СЃС‚Р°:
x &lt;- rep(seq(16, 65, 1), each = 2)
# РћР±СЉРµРґРёРЅСЏРµРј Р·РЅР°С‡РµРЅРёСЏ РІРѕР·СЂР°СЃС‚Р° Рё РґР°РІР»РµРЅРёСЏ РєСЂРѕРІРё РІ РѕРґРЅСѓ С‚Р°Р±Р»РёС†Сѓ
Data &lt;- data.frame(Age = x, BP = y)
ggplot(data = Data, aes(x = Age, BP)) + geom_point() +
geom_smooth(method = &quot;lm&quot;, se = FALSE) +
geom_rug(color = &quot;gray70&quot;, sides = &quot;tr&quot;) +
ylab(&quot;Р§Р°СЃС‚РѕС‚Р°&quot;) + xlab(&quot;Р’РѕР·СЂР°СЃС‚, Р»РµС‚&quot;)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p>РР· РіСЂР°С„РёРєР° РІРёРґРЅРѕ, С‡С‚Рѕ РјРµР¶РґСѓ РґР°РІР»РµРЅРёРµРј РєСЂРѕРІРё Рё РІРѕР·СЂР°СЃС‚РѕРј СЃСѓС‰РµСЃС‚РІСѓРµС‚ РІС‹СЂР°Р¶РµРЅРЅР°СЏ Р»РёРЅРµР№РЅР°СЏ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ: РЅРµСЃРјРѕС‚СЂСЏ РЅР° РѕРїСЂРµРґРµР»РµРЅРЅСѓСЋ РІР°СЂРёР°С†РёСЋ РЅР°Р±Р»СЋРґРµРЅРёР№, РїРѕ РјРµСЂРµ СѓРІРµР»РёС‡РµРЅРёСЏ РІРѕР·СЂР°СЃС‚Р° РґР°РІР»РµРЅРёРµ РІ СЃСЂРµРґРЅРµРј С‚Р°РєР¶Рµ РІРѕР·СЂР°СЃС‚Р°РµС‚. РњС‹ РјРѕР¶РµРј СѓС‡РµСЃС‚СЊ СЌС‚Рѕ СЃРёСЃС‚РµРјР°С‚РёС‡РµСЃРєРѕРµ РёР·РјРµРЅРµРЅРёРµ СЃСЂРµРґРЅРµРіРѕ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ, РґРѕР±Р°РІРёРІ РІРѕР·СЂР°СЃС‚ (Age) РІ РЅР°С€Сѓ РЅСѓР»РµРІСѓСЋ РјРѕРґРµР»СЊ: <span class="math inline">\(y{i}=N\big(\beta+\beta{i}\times Age{i},\sigma\big)\)</span>,</p>
<pre class="r"><code>summary(lm(BP ~ Age, data = Data))</code></pre>
<pre><code>## 
## Call:
## lm(formula = BP ~ Age, data = Data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -21.6644  -6.2491   0.0072   6.3101  17.3484 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 94.85498    2.66731   35.56   &lt;2e-16 ***
## Age          0.99512    0.06204   16.04   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.953 on 98 degrees of freedom
## Multiple R-squared:  0.7242, Adjusted R-squared:  0.7214 
## F-statistic: 257.3 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>РЎРѕРіР»Р°СЃРЅРѕ РїРѕР»СѓС‡РµРЅРЅС‹Рј СЂРµР·СѓР»СЊС‚Р°С‚Р°Рј, РјРѕРґРµР»СЊ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ РјРѕР¶РЅРѕ Р·Р°РїРёСЃР°С‚СЊ РєР°Рє <span class="math inline">\(y{i}=N\big(94.853+0.995\times Age{i}, 8.953\big)\)</span> РёР»Рё <span class="math inline">\(y{i}=94.853+0.995\times Age{i} + \epsilon{i}, \epsilon{i} = N\big(0,8.953\big)\)</span></p>
<p>Р“СЂР°С„РёС‡РµСЃРєРё СЌС‚Р° РјРѕРґРµР»СЊ РёР·РѕР±СЂР°Р¶РµРЅР° РІС‹С€Рµ РЅР° СЂРёСЃСѓРЅРєРµ РІ РІРёРґРµ Р»РёРЅРёРё С‚СЂРµРЅРґР°. РћР±СЂР°С‚РёС‚Рµ РІРЅРёРјР°РЅРёРµ: РїРѕРјРёРјРѕ РІС‹СЃРѕРєРѕР№ Р·РЅР°С‡РёРјРѕСЃС‚Рё РїР°СЂР°РјРµС‚СЂРѕРІ РїРѕРґРѕРіРЅР°РЅРЅРѕР№ РјРѕРґРµР»Рё (СЂ &lt;&lt; 0.001 РІ РѕР±РѕРёС… СЃР»СѓС‡Р°СЏС…), СЃС‚Р°РЅРґР°СЂС‚РЅРѕРµ РѕС‚РєР»РѕРЅРµРЅРёРµ РѕСЃС‚Р°С‚РєРѕРІ СЃРѕСЃС‚Р°РІР»СЏРµС‚ 8.853, С‡С‚Рѕ РїРѕС‡С‚Рё РІ 2 СЂР°Р·Р° РјРµРЅСЊС€Рµ, С‡РµРј Сѓ РЅСѓР»РµРІРѕР№ РјРѕРґРµР»Рё (16.96). Р­С‚Рѕ СѓРєР°Р·С‹РІР°РµС‚ РЅР° С‚Рѕ, С‡С‚Рѕ РјРѕРґРµР»СЊ, РІРєР»СЋС‡Р°СЋС‰Р°СЏ РІРѕР·СЂР°СЃС‚ РєР°Рє РїСЂРµРґРёРєС‚РѕСЂ, РіРѕСЂР°Р·РґРѕ Р»СѓС‡С€Рµ РѕРїРёСЃС‹РІР°РµС‚ РІР°СЂРёР°С†РёСЋ Р·РЅР°С‡РµРЅРёР№ РєСЂРѕРІСЏРЅРѕРіРѕ РґР°РІР»РµРЅРёСЏ Сѓ 100 РѕР±СЃР»РµРґРѕРІР°РЅРЅС‹С… РёСЃРїС‹С‚СѓРµРјС‹С…, С‡РµРј РЅР°С€Р° РёСЃС…РѕРґРЅР°СЏ РјРѕРґРµР»СЊ Р±РµР· РїР°СЂР°РјРµС‚СЂР°.</p>
<p>Р­С‚Рѕ Р·Р°РєР»СЋС‡РµРЅРёРµ РїРѕРґС‚РІРµСЂР¶РґР°РµС‚СЃСЏ С‚РµРј, С‡С‚Рѕ РІ СЂРµР·СѓР»СЊС‚Р°С‚Рµ РІС‹РїРѕР»РЅРµРЅРёСЏ РёРјРёС‚Р°С†РёР№, Р°РЅР°Р»РѕРіРёС‡РЅС‹С… РѕРїРёСЃР°РЅРЅС‹Рј РІС‹С€Рµ, Р·РЅР°С‡РµРЅРёРµ РёРЅС‚РµСЂРєРІР°СЂС‚РёР»СЊРЅРѕРіРѕ СЂР°Р·РјР°С…Р° РґР»СЏ РёСЃС…РѕРґРЅС‹С… РґР°РЅРЅС‹С… СЂР°СЃРїРѕР»Р°РіР°РµС‚СЃСЏ РІ С†РµРЅС‚СЂРµ СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ РёРјРёС‚РёСЂРѕРІР°РЅРЅС‹С… Р·РЅР°С‡РµРЅРёР№ РРљР , СѓРєР°Р·С‹РІР°СЏ РЅР° РѕС‚СЃСѓС‚СЃС‚РІРёРµ СЃРёСЃС‚РµРјР°С‚РёС‡РµСЃРєРёС… СЂР°Р·Р»РёС‡РёР№ РјРµР¶РґСѓ РёРјРёС‚РёСЂРѕРІР°РЅРЅС‹РјРё Рё РЅР°Р±Р»СЋРґР°РµРјС‹РјРё РґР°РЅРЅС‹РјРё. РљРѕРґ РЅР° СЏР·С‹РєРµ R Рё РїРѕР»СѓС‡РµРЅРЅСѓСЋ РіРёСЃС‚РѕРіСЂР°РјРјСѓ РјС‹ Р·РґРµСЃСЊ РЅРµ РїСЂРёРІРѕРґРёРј, СЂРµРєРѕРјРµРЅРґСѓСЏ РїСЂРѕРґРµР»Р°С‚СЊ РІС‹С‡РёСЃР»РµРЅРёСЏ СЃР°РјРѕРјСѓ С‡РёС‚Р°С‚РµР»СЋ.</p>
<p>РўРµРїРµСЂСЊ РЅР°СЃС‚Р°Р»Рѕ РІСЂРµРјСЏ СЂР°СЃРєСЂС‹С‚СЊ РЅРµР±РѕР»СЊС€РѕР№ СЃРµРєСЂРµС‚: С‚РѕС‚ С„Р°РєС‚, С‡С‚Рѕ РјРѕРґРµР»СЊ, РІРєР»СЋС‡Р°СЋС‰Р°СЏ РІРѕР·СЂР°СЃС‚, РіРѕСЂР°Р·РґРѕ Р»СѓС‡С€Рµ РѕРїРёСЃС‹РІР°РµС‚ РёСЃС…РѕРґРЅС‹Рµ РґР°РЅРЅС‹Рµ, РЅРµСѓРґРёРІРёС‚РµР»РµРЅ, РїРѕСЃРєРѕР»СЊРєСѓ СЌС‚Рё РЅР°Р±Р»СЋРґРµРЅРёСЏ Р±С‹Р»Рё… СЃРіРµРЅРµСЂРёСЂРѕРІР°РЅС‹ РЅР° РѕСЃРЅРѕРІРµ РјРѕРґРµР»Рё <span class="math inline">\(y{i}=97.078+0.949\times Age{i} + \epsilon{i}, \epsilon{i} = N\big(0,9.563\big)\)</span> СЃР»РµРґСѓСЋС‰РёРј РѕР±СЂР°Р·РѕРј:</p>
<pre class="r"><code>set.seed(101)
y &lt;- rnorm(100, mean = 97.078 + 0.949*x, 9.563)</code></pre>
<p>РџРѕСЃР»РµРґРЅСЏСЏ РјРѕРґРµР»СЊ, РїСЂРёРґСѓРјР°РЅРЅР°СЏ РІ С†РµР»СЏС… РґРµРјРѕРЅСЃС‚СЂР°С†РёРё РѕР±СЃСѓР¶РґР°РµРјС‹С… РїСЂРёРЅС†РёРїРѕРІ, Р±С‹Р»Р° РёСЃРїРѕР»СЊР·РѕРІР°РЅР° РІ РєР°С‡РµСЃС‚РІРµ “РёСЃС‚РёРЅРЅРѕР№” (Р°РЅРіР». true model) РІ С‚РѕРј СЃРјС‹СЃР»Рµ, С‡С‚Рѕ РѕРЅР° РѕРїРёСЃС‹РІР°Р»Р° РіРµРЅРµСЂР°Р»СЊРЅСѓСЋ СЃРѕРІРѕРєСѓРїРЅРѕСЃС‚СЊ. Р”СЂСѓРіРёРјРё СЃР»РѕРІР°РјРё, РјС‹ РїСЂРµРґРїРѕР»РѕР¶РёР»Рё, С‡С‚Рѕ Сѓ РЅР°СЃ Р±С‹Р»Р° РІРѕР·РјРѕР¶РЅРѕСЃС‚СЊ РѕРґРЅРѕРјРѕРјРµРЅС‚РЅРѕ РёР·РјРµСЂРёС‚СЊ РґР°РІР»РµРЅРёРµ Сѓ РІСЃРµС… СЃСѓС‰РµСЃС‚РІСѓСЋС‰РёС… Р»СЋРґРµР№ Рё РїРѕР»СѓС‡РµРЅРЅС‹Рµ РґР°РЅРЅС‹Рµ РѕРїРёСЃС‹РІР°Р»РёСЃСЊ Р±С‹ РёРјРµРЅРЅРѕ СЌС‚РѕР№ “РёСЃС‚РёРЅРЅРѕР№” РјРѕРґРµР»СЊСЋ. Р’ СЂРµР°Р»СЊРЅРѕР№ СЃРёС‚СѓР°С†РёРё РЅРё СЃС‚СЂСѓРєС‚СѓСЂР° (СЃРёСЃС‚РµРјР°С‚РёС‡РµСЃРєР°СЏ С‡Р°СЃС‚СЊ + РѕСЃС‚Р°С‚РєРё), РЅРё Р·РЅР°С‡РµРЅРёСЏ РїР°СЂР°РјРµС‚СЂРѕРІ РёСЃС‚РёРЅРЅРѕР№ РјРѕРґРµР»Рё РёСЃСЃР»РµРґРѕРІР°С‚РµР»СЋ, РєР°Рє РїСЂР°РІРёР»Рѕ, РЅРµРёР·РІРµСЃС‚РЅС‹.</p>
<p>Р’СЃРµ, С‡РµРј РѕРЅ СЂР°СЃРїРѕР»Р°РіР°РµС‚ вЂ“ СЌС‚Рѕ РЅР°Р±РѕСЂС‹ СЌРєСЃРїРµСЂРёРјРµРЅС‚Р°Р»СЊРЅС‹С… РґР°РЅРЅС‹С…, С‡Р°СЃС‚Рѕ РЅРµРґРѕСЃС‚Р°С‚РѕС‡РЅРѕ СЂРµРїСЂРµР·РµРЅС‚Р°С‚РёРІРЅС‹С… Рё СЃРёР»СЊРЅРѕ “Р·Р°С€СѓРјР»РµРЅРЅС‹С…”. РРјРµСЏ СЌС‚Рё РґР°РЅРЅС‹Рµ Рё С…РѕСЂРѕС€РµРµ РїРѕРЅРёРјР°РЅРёРµ РёР·СѓС‡Р°РµРјРѕРіРѕ СЏРІР»РµРЅРёСЏ (РІ СЃРјС‹СЃР»Рµ С‚РѕРіРѕ, РєР°РєРёРµ РїСЂРµРґРёРєС‚РѕСЂС‹ СЃС‡РёС‚Р°С‚СЊ РґРѕСЃС‚Р°С‚РѕС‡РЅРѕ РІР°Р¶РЅС‹РјРё РґР»СЏ СЂР°СЃСЃРјРѕС‚СЂРµРЅРёСЏ), РёСЃСЃР»РµРґРѕРІР°С‚РµР»СЊ РјРѕР¶РµС‚ С‚РѕР»СЊРєРѕ РЅР°РґРµСЏС‚СЊСЃСЏ РїСЂРёР±Р»РёР·РёС‚СЊСЃСЏ Рє СЃС‚СЂСѓРєС‚СѓСЂРµ РёСЃС‚РёРЅРЅРѕР№ РјРѕРґРµР»Рё Рё РѕС†РµРЅРёС‚СЊ РµРµ РїР°СЂР°РјРµС‚СЂС‹ СЃ РѕРїСЂРµРґРµР»РµРЅРЅРѕР№ С‚РѕС‡РЅРѕСЃС‚СЊСЋ. Рљ СЃРѕР¶Р°Р»РµРЅРёСЋ, С‚Р°РєРѕР№ СѓСЃРїРµС… РіР°СЂР°РЅС‚РёСЂРѕРІР°РЅ РґР°Р»РµРєРѕ РЅРµ РІСЃРµРіРґР°.</p>
</div>
</div>
<div id="section-3" class="section level2">
<h2>Р›РёРЅРµР№РЅР°СЏ СЂРµРіСЂРµСЃСЃРёСЏ. РџСЂР°РєС‚РёРєР°</h2>
<pre class="r"><code>library(ggplot2)
library(dplyr)</code></pre>
<pre class="r"><code>options(stringsAsFactors = FALSE)</code></pre>
<p>Р—Р°РіСЂСѓР·РёРј РґР°РЅРЅС‹Рµ СЃСЂР°РІРЅРµРЅРёСЏ РґРѕСЃС‚Р°С‚РєР° Рё СЂРѕСЃС‚Р° С‡РµР»РѕРІРµРєР° Рё СЂСЏРґР° РґСЂСѓРіРёС… РґРµРјРѕРіСЂР°С„РёС‡РµСЃРєРёС… С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРє РѕС‚ 1379 С‡РµР»РѕРІРµРє, РєРѕС‚РѕСЂС‹Рµ Р±С‹Р»Рё СЃРѕР±СЂР°РЅРЅС‹ РІ 1994 РіРѕРґСѓ. Р­С‚Рѕ СЃРёРјСѓР»РёСЂРѕРІР°РЅРЅС‹Рµ РґР°РЅРЅС‹Рµ, РѕСЃРЅРѕРІР°РЅРЅС‹Рµ РЅР° СЂРµР°Р»СЊРЅС‹С… РґР°РЅРЅС‹С…, СЃРѕР±СЂР°РЅРЅС‹С… Р“РµР»СЊРјР°РЅРѕРј Рё РҐРёР»Р»РѕРј.</p>
<pre class="r"><code>wages &lt;- read.csv(&quot;https://dl.dropboxusercontent.com/s/oq4dc134y8xdyce/wages.csv?dl=0&quot;)

tbl_df(wages)</code></pre>
<pre><code>## # A tibble: 1,379 x 6
##      earn height sex    race        ed   age
##     &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;int&gt; &lt;int&gt;
##  1 79571.   73.9 male   white       16    49
##  2 96397.   66.2 female white       16    62
##  3 48711.   63.8 female white       16    33
##  4 80478.   63.2 female other       16    95
##  5 82089.   63.1 female white       17    43
##  6 15313.   64.5 female white       15    30
##  7 47104.   61.5 female white       12    53
##  8 50960.   73.3 male   white       17    50
##  9  3213.   72.2 male   hispanic    15    25
## 10 42997.   72.4 male   white       12    30
## # ... with 1,369 more rows</code></pre>
<p>Р•С‰Рµ РѕРґРёРЅ РЅР°Р±РѕСЂ РґР°РЅРЅС‹С… РїС‹С‚Р°РµС‚СЃСЏ РїСЂРѕРІРµСЂРёС‚СЊ РЅР°Р»РёС‡РёРµ СЃРІСЏР·Рё РјРµР¶РґСѓ РєР»РёРјР°С‚РѕРј Рё РїСЂРµСЃС‚СѓРїРЅРѕСЃС‚СЊСЋ РІ СЂР°Р·Р»РёС‡РЅС‹С… С€С‚Р°С‚Р°С… РЎРЁРђ.</p>
<pre class="r"><code>crime &lt;- read.csv(&quot;https://dl.dropboxusercontent.com/s/cecck1nuo217zy1/crime.csv?dl=0&quot;)

tbl_df(crime)</code></pre>
<pre><code>## # A tibble: 48 x 5
##    state       abbr    low murder tc2009
##    &lt;chr&gt;       &lt;chr&gt; &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 Alabama     AL      -27    7.1  4338.
##  2 Alaska      AK      -80    3.2  3567.
##  3 Arizona     AZ      -40    5.5  3725.
##  4 Arkansas    AR      -29    6.3  4415.
##  5 California  CA      -45    5.4  3202.
##  6 Colorado    CO      -61    3.2  3024.
##  7 Connecticut CT      -32    3    2646.
##  8 Delaware    DE      -17    4.6  3997.
##  9 Florida     FL       -2    5.5  4454.
## 10 Georgia     GA      -17    6    4181.
## # ... with 38 more rows</code></pre>
<p>Р’С‹ СѓР¶Рµ РёРјРµРµС‚Рµ РѕР±С‰РµРµ РїСЂРµРґСЃС‚Р°РІР»РµРЅРёРµ Рѕ СЂРµРіСЂРµСЃРёРё Рё Рѕ РЅРµРєРѕС‚РѕСЂРѕРј СѓСЂР°РІРЅРµРЅРёРё <span class="math inline">\(y{i}=N\big(\alpha+\beta{i}x{i}+\sigma\big)\)</span>, РєРѕС‚РѕСЂРѕРµ РµРіРѕ РІ РѕР±С‰РµРј РІРёРґРµ РѕРїРёСЃС‹РІР°РµС‚. РќР° СЃР°РјРѕРј РґРµР»Рµ, С‡С‚Рѕ РЅРµ СЃР»РѕР¶РЅРѕ Р·Р°РјРµС‚РёС‚СЊ РёР· С‚РѕРіРѕ, С‡С‚Рѕ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ Р»РёРЅРµР№РЅР°СЏ, СЌС‚Рѕ СѓСЂР°РІРЅРµРЅРёРµ Р»РёРЅРµР№РЅРѕР№ СЂРµРіСЂРµСЃСЃРёРё. Р­С‚Рѕ СЃР°РјС‹Р№ РїСЂРѕСЃС‚РѕР№ РёР· РІСЃРµС… РІРѕР·РјРѕР¶РЅС‹С… РІР°СЂРёР°РЅС‚РѕРІ, РЅРѕ РїРѕС‚РѕРјСѓ Рё СЃР°РјС‹Р№ РїРѕРЅСЏС‚РЅС‹Р№. РџРѕСЌС‚РѕРјСѓ РјС‹ РЅР°С‡РЅРµРј СЃ РЅРµРіРѕ.</p>
<p>Р’ РґР°Р»СЊРЅРµР№С€РµРј РјС‹ СЂР°Р·Р±РµСЂРµРј РґСЂСѓРіРёРµ РІР°СЂРёР°РЅС‚С‹ СЂРµРіСЂРµСЃРёРё, Рё РґР°Р¶Рµ РµСЃР»Рё РІР°Рј РІ РІР°С€РµРј РёСЃСЃР»РµРґРѕРІР°РЅРёРё СЃСЂР°Р·Сѓ СЏСЃРЅРѕ, С‡С‚Рѕ РІР°С€Рё РґР°РЅРЅС‹Рµ РЅРµ РѕРїРёСЃС‹РІР°СЋС‚СЃСЏ Р»РёРЅРµР№РЅРѕР№ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊСЋ,РЅР°СЃС‚РѕСЏС‚РµР»СЊРЅРѕ СЂРµРєРѕРјРµРЅРґСѓРµС‚СЃСЏ РЅР°С‡РёРЅР°РµС‚СЊ СЃРІРѕРµ РёСЃСЃР»РµРґРѕРІР°РЅРёРµ РёРјРµРЅРЅРѕ СЃ Р»РёРЅРµР№РЅС‹С… Р·Р°РІРёСЃРёРјРѕСЃС‚РµР№.</p>
<p>Рў.Рє. Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ Р»РёРЅРµР№РЅР°СЏ, С‚Рѕ РµРµ РіСЂР°С„РёС‡РµСЃРєРѕРµ РѕС‚РѕР±СЂР°Р¶РµРЅРёРµ РЅР° РіСЂР°С„РёРєРµ РґР°РЅРЅС‹С… РґРѕР»Р¶РЅРѕ Р±С‹С‚СЊ РїСЂСЏРјРѕР№, РїСЂРё С‡РµРј СЌС‚Р° РїСЂСЏРјР°СЏ РґРѕР»Р¶РЅР° РїСЂРѕС…РѕРґРёС‚СЊ С‡РµСЂРµР· РѕСЃРЅРѕРІРЅРѕР№ РјР°СЃСЃРёРІ РґР°РЅРЅС‹С…. Р”РѕРІРѕР»СЊРЅРѕ РѕС‡РµРІРёРґРЅРѕ, С‡С‚Рѕ С‡РµСЂРµР· РїСЂР°РєС‚РёС‡РµСЃРєРё Р»СЋР±РѕР№ Р±РѕР»СЊС€РѕР№ РЅР°Р±РѕСЂ РґР°РЅРЅС‹С… РїРѕРјРµС‰РµРЅРЅС‹С… РЅР° РіСЂР°С„РёРє РјРѕР¶РЅРѕ РїСЂРѕРІРµСЃС‚Рё РјРЅРѕР¶РµСЃС‚РІРѕ РїСЂСЏРјС‹С…, РєРѕС‚РѕСЂС‹Рµ Р±СѓРґСѓС‚ РІ С‚РѕР№ РёР»Рё РёРЅРѕР№ РјРµСЂРµ РѕРїРёСЃС‹РІР°С‚СЊ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ РІРµР»РёС‡РёРЅ РґСЂСѓРі РѕС‚ РґСЂСѓРіР°. Р РІСЃС‚Р°РµС‚ РІРѕРїСЂРѕСЃ РєР°РєРёРј РѕР±СЂР°Р·РѕРј РІС‹Р±СЂР°С‚СЊ С‚Сѓ СЃР°РјСѓСЋ РїСЂСЏРјСѓСЋ, РєРѕС‚РѕСЂР°СЏ Р±СѓРґРµС‚ РѕРїРёСЃС‹РІР°С‚СЊ РЅР°С€Рё РґР°РЅРЅС‹Рµ РЅР°РёР»СѓС‡С€РёРј РѕР±СЂР°Р·РѕРј.</p>
<p>Р’ СЃС‚Р°С‚РёСЃС‚РёРєРµ РїСЂРёСЏРЅС‚Рѕ СЃС‡РёС‚Р°С‚СЊ РЅР°РёР±РѕР»РµРµ РїРѕРґС…РѕРґСЏС‰РµР№ С‚Р°РєСѓСЋ РїСЂСЏРјСѓСЋ, СЃСѓРјРјР° РєРІР°РґСЂР°С‚РѕРІ РѕСЃС‚Р°С‚РєРѕРІ(residuals) РєРѕС‚РѕСЂРѕР№ Р±СѓРґРµС‚ РјРёРЅРёРјР°Р»СЊРЅРѕР№. РџРѕРґ РѕСЃС‚Р°С‚РєР°РјРё РїРѕРЅРёРјР°СЋС‚ СЂР°СЃСЃС‚РѕСЏРЅРёРµ РїРѕ РІРµСЂС‚РёРєР°Р»Рё РѕС‚ РєР°Р¶РґРѕР№ С‚РѕС‡РєРё РґР°РЅРЅС‹С… РґРѕ Р±Р»РёР¶Р°Р№С€РµР№ С‚РѕС‡РєРё РїСЂСЏРјРѕР№ РёР»Рё <span class="math inline">\(Residuals=y{i}-f\big(x{i}\big)\)</span>, РґСЂСѓРіРѕРµ РёС… РЅР°Р·РІР°РЅРёРµ - РѕС‚РєР»РѕРЅРµРЅРёСЏ. Рў.Рє. РєР°Р¶РґС‹Р№ РѕСЃС‚Р°С‚РѕРє РјРѕР¶РµС‚ Р±С‹С‚СЊ РѕС‚Р»РёС‡РЅС‹Рј РїРѕ Р·РЅР°РєСѓ, Р° РЅР°СЃ РёРЅС‚РµСЂРµСЃСѓРµС‚ Р°Р±СЃРѕР»СЋС‚РЅРѕРµ Р·РЅР°С‡РµРЅРёРµ РІСЃРµС… РѕСЃС‚Р°С‚РєРѕРІ, С‚.Рє. РєР°Р¶РґС‹Р№ РёР· РЅРёС… РїРѕ СЃСѓС‚Рё С…Р°СЂР°РєС‚РµСЂРёР·СѓРµС‚ С‚РѕС‡РЅРѕСЃС‚СЊ РјРѕРґРµР»Рё, С‚Рѕ СЃСѓРјРјРёСЂСѓСЋС‚СЃСЏ РЅРµ СЃР°РјРё РѕСЃС‚Р°С‚РєРё Р° РёС… РєРІР°РґСЂР°С‚С‹. РўР°РєРёРј РѕР±СЂР°Р·РѕРј РёС‚РѕРіРѕРІР°СЏ СЂРµР·СѓР»СЊС‚РёСЂСѓСЋС‰Р°СЏ РєР°С‡РµСЃС‚РІРѕ РјРѕРґРµР»Рё РІРµР»РёС‡РёРЅР°СЏ Р±СѓРґРµС‚ РЅР°Р·С‹РІР°С‚СЊСЃСЏ СЃСѓРјРјР° РєРІР°РґСЂР°С‚РѕРІ РѕС‚РєР»РѕРЅРµРЅРёР№(RSS) Рё Р±СѓРґРµС‚ РёРјРµС‚СЊ РІРёРґ <span class="math inline">\(RSS=\Sigma\big(y{i}-f\big(x{i}\big)\big)^{2}\)</span></p>
<p>РћС‡РµРІРёРґРЅРѕ, С‡С‚Рѕ РІ R СѓР¶Рµ СЃСѓС‰РµСЃС‚РІСѓРµС‚ РіРѕС‚РѕРІРѕРµ СЂРµС€РµРЅРёСЏ РґР»СЏ РїРѕРґР±РѕСЂР° РєРѕСЌС„С„РёС†РёРµРЅС‚РѕРІ РїСЂСЏРјРѕР№, РєРѕС‚РѕСЂС‹Рµ РґР»СЏ РїСЂРёРІРµРґРµРЅРЅС‹С… РґР°РЅРЅС‹С… РґР°РґСѓС‚ РјРёРЅРёРјР°Р»СЊРЅСѓСЋ СЃСѓРјРјСѓ РєРІР°РґСЂР°С‚РѕРІ РѕС‚РєР»РѕРЅРµРЅРёР№. РњРµР¶ С‚РµРј, РєР°Рє Рё РІ Р»СЋР±РѕР№ РґСЂСѓРіРѕР№ Р·Р°РґР°С‡Рµ РїРѕ РїСЂРѕРіСЂР°РјРјРёСЂРѕРІР°РЅРёСЋ, РІР°С€Р° СЂРѕР»СЊ РЅР°РёР±РѕР»РµРµ С‚РѕС‡РЅРѕ “РѕР±СЉСЏСЃРЅРёС‚СЊ” СЏР·С‹РєСѓ, С‡С‚Рѕ РІС‹ РѕС‚ РЅРµРіРѕ С…РѕС‚РёС‚Рµ.</p>
<p>Р”Р»СЏ РїРѕР»СѓС‡РµРЅРёСЏ Р»РёРЅРµР№РЅС‹С… СЂРµРіСЂРµСЃСЃРёРѕРЅРЅС‹С… СѓСЂР°РІРЅРµРЅРёР№ РІ R СЃСѓС‰РµСЃС‚РІСѓРµС‚ С„СѓРЅРєС†РёСЏ lm. РћРЅР° РІС…РѕРґРёС‚ РІ Р±РѕР»СЊС€СѓСЋ СЃРµРјСЊСЋ С„СѓРЅРєС†РёР№ РїСЂРёРјРµРЅСЏРµРјС‹С… РґР»СЏ РјРѕРґРµР»РёСЂРѕРІР°РЅРёСЏ Рё РёСЃРїРѕР»СЊР·СѓРµС‚ Р°РЅР°Р»РѕРіРёС‡РЅС‹Р№ РёРј СЃРёРЅС‚Р°РєСЃРёСЃ.</p>
<pre class="html"><code></code></pre>
<table>
<colgroup>
<col width="25%" />
<col width="27%" />
<col width="30%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">
РїРµСЂРµРјРµРЅРЅР°СЏ РґР»СЏ С…СЂР°РЅРµРЅРёСЏ РјРѕРґРµР»Рё
</th>
<th align="left">
Р¤СѓРЅРєС†РёСЏ РёРЅРёС†РёР°С†РёРё Р»РёРЅРµР№РЅРѕР№ РјРѕРґРµР»Рё
</th>
<th align="left">
РћСЃРЅРѕРІРЅР°СЏ С„РѕСЂРјСѓР»Р°: РѕС‚РєР»РёРє ~ РїРѕРєР°Р·Р°С‚РµР»Рё
</th>
<th align="left">
РўР°Р±Р»РёС†Р° СЃ РґР°РЅРЅС‹РјРё
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">
mod
</td>
<td align="left">
= lm(
</td>
<td align="left">
tc2009 ~ low,
</td>
<td align="left">
data = crime)
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>mod = lm(tc2009 ~ low, data = crime)</code></pre>
<p>Р’ R СЃСѓС‰РµСЃС‚РІСѓРµС‚ РѕСЃРѕР±С‹Р№ РєР»Р°СЃСЃ РґР°РЅРЅС‹С… РєРѕС‚РѕСЂС‹Р№ РЅР°Р·С‹РІР°РµС‚СЃСЏ “С„РѕСЂРјСѓР»С‹”, СЃРѕР·РґР°РЅРЅС‹Р№ РґР»СЏ РѕРїРёСЃР°РЅРёСЏ Р·Р°РІРёСЃРёРјРѕСЃС‚РµР№ РјРµР¶РґСѓ РѕР±СЉРµРєС‚Р°РјРё. Р”Р»СЏ С‚РѕРіРѕ С‡С‚РѕР±С‹ СЃРѕР·РґР°С‚СЊ РїРѕРґРѕР±РЅСѓСЋ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ РІ R РёСЃРїРѕР»СЊР·СѓРµС‚СЃСЏ СЃРёРјРІРѕР» С‚РёР»СЊРґР° - ~</p>
<pre class="r"><code>tc2009 ~ low</code></pre>
<pre><code>## tc2009 ~ low</code></pre>
<pre class="r"><code>class(tc2009 ~ low)</code></pre>
<pre><code>## [1] &quot;formula&quot;</code></pre>
<p>РџРѕ СЃСѓС‚Рё Р·Р°РїРёСЃСЊ y ~ x, РІ R СЂР°РІРЅРѕСЃРёР»СЊРЅР° РјР°С‚РµРјР°С‚РёС‡РµСЃРєРѕР№ Р·Р°РїРёСЃРё <span class="math inline">\(y{i}=N\big(\alpha+\beta{i} x{i}+\sigma\big)\)</span>. Р”Р»СЏ РІР°СЃ, РєР°Рє РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РІР°Р¶РЅРѕ РІСЃРµРіРґР° РїРѕРјРЅРёС‚СЊ С‡С‚Рѕ РѕРїРёСЃС‹РІР°РµРјР°СЏ РёР»Рё Р·Р°РІРёСЃРёРјР°СЏ РїРµСЂРµРјРµРЅРЅР°СЏ РІСЃРµРіРґР° РЅР°С…РѕРґРёС‚СЃСЏ РІ РїРѕРґРѕР±РЅРѕР№ Р·Р°РїРёСЃРё СЃР»РµРІР°, С‚.Рµ. “Р·Р°РІРёСЃРёРјР°СЏ РїРµСЂРµРјРµРЅРЅР°СЏ” ~ “РЅРµР·Р°РІРёСЃРёРјР°СЏ РїРµСЂРµРјРµРЅРЅР°СЏ”. РР»Рё РґР»СЏ СЃР»СѓС‡Р°СЏ y ~ x : Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ y РѕС‚ x, РЅРѕ РЅРё РєР°Рє РЅРµ РЅР°РѕР±РѕСЂРѕС‚.</p>
<p>РљР°Рє СѓР¶Рµ СѓРїРѕРјРёРЅР°Р»РѕСЃСЊ СЂР°РЅРµРµ РїРѕРґРѕР±РЅС‹Р№ СЃРёРЅС‚Р°РєСЃРёСЃ С…Р°СЂР°РєС‚РµСЂРµРЅ РЅРµ С‚РѕР»СЊРєРѕ РґР»СЏ С„СѓРЅРєС†РёРё lm. Р’ СЃРµРјРµР№СЃС‚РІРѕ РїРѕРґРѕР±РЅС‹С… РµР№ С„СѓРЅРєС†РёР№ РІС…РѕРґСЏС‚ lmer,lme,rlm,glm,gam Рё РґСЂ, С‡Р°СЃС‚СЊ РёР· РєРѕС‚РѕСЂС‹С… РјС‹ СЂР°СЃСЃРјРѕС‚СЂРёРј С‡СѓС‚СЊ РїРѕР·Р¶Рµ.</p>
<p>Р’РµСЂРЅРµРјСЃСЏ Рє РЅР°С€РµР№ РјРѕРґРµР»Рё, РєРѕС‚РѕСЂР°СЏ РїС‹С‚Р°РµС‚СЃСЏ РѕРїРёСЃР°С‚СЊ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ РєРѕР»РёС‡РµСЃС‚РІР° РїСЂРµСЃС‚СѓРїР»РµРЅРёР№ РІ 2009 РіРѕРґСѓ РѕС‚ РјРёРЅРёРјР°Р»СЊРЅРѕ РЅР°Р±Р»СЋРґР°РµРјРѕР№ С‚РµРјРїРµСЂР°С‚СѓСЂС‹ РЅР° РґР°РЅРЅРѕР№ С‚РµСЂСЂРёС‚РѕСЂРё Р·Р° СЂР°СЃСЃРјР°С‚СЂРёРІР°РµРјРѕРµ РІСЂРµРјСЏ. Р”Р»СЏ С‚РѕРіРѕ, С‡С‚РѕР±С‹ СѓРІРёРґРµС‚СЊ, РєР°РєРёРµ РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РЅР°Рј СЂР°СЃСЃС‡РёС‚Р°Р» R, РѕР±СЂР°С‚РёРјСЃСЏ Рє СЃРѕРґРµСЂР¶РёРјРѕРјСѓ РјРѕРґРµР»Рё СЌС‚РѕРіРѕ РѕР±СЉРµРєС‚Р° - mod</p>
<pre class="r"><code>mod</code></pre>
<pre><code>## 
## Call:
## lm(formula = tc2009 ~ low, data = crime)
## 
## Coefficients:
## (Intercept)          low  
##     4256.86        21.65</code></pre>
<p>РќР° СЃР°РјРѕРј РґРµР»Рµ РІ РѕР±СЉРµРєС‚Рµ РјРѕРґРµР»Рё СЃРѕРґРµСЂР¶РёС‚СЃСЏ РЅР° РјРЅРѕРіРѕ Р±РѕР»СЊС€Рµ РёРЅС„РѕСЂРјР°С†РёРё, С‡РµРј РїРѕРєР°Р·С‹РІР°РµС‚СЃСЏ РїСЂРё СЃС‚Р°РЅРґР°СЂС‚РЅРѕРј РІС‹РІРѕРґРµ, РїРѕСЌС‚РѕРјСѓ РѕР±СЉРµРєС‚С‹ РјРѕРґРµР»Рё РІСЃРµРіРґР° Р»СѓС‡С€Рµ СЃРѕС…СЂР°РЅСЏС‚СЊ РІ РѕС‚РґРµР»СЊРЅСѓСЋ РїРµСЂРµРјРµРЅРЅСѓСЋ. РЈРІРёРґРµС‚СЊ РІСЃСЋ СЃР»РѕР¶РЅРѕСЃС‚СЊ РѕР±СЉРµРєС‚Р° РјРѕРґРµР»Рё РІС‹ РјРѕР¶РµС‚Рµ РІС‹РїРѕР»РЅРёРІ СЃР»РµРґСѓСЋС‰СѓСЋ РєРѕРјР°РЅРґСѓ:</p>
<pre class="r"><code>names(mod)</code></pre>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;</code></pre>
<div id="section-4" class="section level3">
<h3>РџРѕР»СѓС‡РµРЅРёРµ РґР°РЅРЅС‹С… РёР· РјРѕРґРµР»Рё</h3>
<p>РЎСѓС‰РµСЃС‚РІСѓРµС‚ СЃС‚Р°РЅРґР°СЂС‚РЅС‹Р№ РїРѕРґС…РѕРґ РїСЂРё СЂР°Р±РѕС‚Рµ СЃ РјРѕРґРµР»СЏРјРё РІ R, РєСЂР°С‚РєРѕ РѕРЅ РѕРїРёСЃС‹РІР°РµС‚СЃСЏ С…СЂР°РЅРµРЅРёРµ Рё РёСЃСЃР»РµРґРѕРІР°РЅРёРµ. РЎСѓС‚СЊ РµРіРѕ СЃРІРѕРґРёС‚СЃСЏ Рє РґРІСѓРј РїСЂРѕСЃС‚С‹Рј РґРµР№СЃС‚РІРёСЏРј - СЃРѕС…СЂР°РЅРµРЅРёСЋ РѕР±СЉРµРєС‚Р° РјРѕРґРµР»Рё РІ РїР°РјСЏС‚Рё РїРѕРґ РІРёРґРѕРј РїРµСЂРµРјРµРЅРЅРѕР№ Рё РІС‹РїРѕР»РЅРµРЅРёСЏ СЂСЏРґР° С„СѓРЅРєС†РёР№ РЅР° СЌС‚РѕРј РѕР±СЉРµРєС‚Рµ, РґР»СЏ РїРѕР»СѓС‡РµРЅРёСЏ РґР°РЅРЅС‹С… РїРѕ РёСЃСЃР»РµРґРѕРІР°РЅРёСЋ С„СѓРЅРєС†РёРё РѕР±СЉРµРєС‚Р°.</p>
<p>Рљ РїРѕРґРѕР±РЅС‹Рј С„СѓРЅРєС†РёСЏРј РѕС‚РЅРѕСЃСЏС‚СЃСЏ С‚СЂРё СЃР»РµРґСѓСЋС‰РёРµ С„СѓРЅРєС†РёРё, РєРѕС‚РѕСЂС‹Рµ РїСЂРµРґРѕСЃС‚Р°РІР»СЏСЋС‚ РјРёРЅРёРјР°Р»СЊРЅРѕ РЅРµРѕР±С…РѕРґРёРјС‹Р№ С„СѓРЅРєС†РёРѕРЅР°Р» РґР»СЏ РёСЃСЃР»РµРґРѕРІР°РЅРёСЏ С„СѓРЅРєС†РёР№.</p>
<p>Р’С‹ СѓР¶Рµ Р·РЅР°РєРѕРјС‹ СЃ С„СѓРЅРєС†РёРµР№ summary, РєРѕС‚РѕСЂР°СЏ РїСЂРµРґРѕСЃС‚Р°РІР»СЏРµС‚ РЅР°Рј РѕР±С‰СѓСЋ РёРЅС„РѕСЂРјР°С†РёСЋ РѕР± РѕР±СЉРµРєС‚Рµ, РІ РґР°РЅРЅРѕРј СЃР»СѓС‡Р°Рµ РјС‹ РїРѕР»СѓС‡РёРј РѕР±С‰СѓСЋ РёРЅС„РѕСЂРјР°С†РёСЋ РїРѕ РјРѕРґРµР»Рё:</p>
<pre class="r"><code>summary(mod)</code></pre>
<pre><code>## 
## Call:
## lm(formula = tc2009 ~ low, data = crime)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1134.36  -647.13    98.03   533.62  1344.30 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4256.86     233.44  18.236  &lt; 2e-16 ***
## low            21.65       5.33   4.061 0.000188 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 649.9 on 46 degrees of freedom
## Multiple R-squared:  0.2639, Adjusted R-squared:  0.2479 
## F-statistic: 16.49 on 1 and 46 DF,  p-value: 0.000188</code></pre>
<p>Р¤СѓРЅРєС†РёСЏ predict() (РїСЂРµРґСЃРєР°Р·Р°РЅРёРµ) СЂР°СЃСЃС‡РёС‚С‹РІР°РµС‚ Р·РЅР°С‡РµРЅРёСЏ РёРЅС‚РµСЂРµСЃСѓСЋС‰РµР№ РІР°СЃ РїРµСЂРµРјРµРЅРЅРѕР№(СЃС‚РѕР»Р±С†Р° РІ С‚Р°Р±Р»РёС†Рµ) РґР»СЏ РєР°Р¶РґРѕРіРѕ РµРµ Р·РЅР°С‡РµРЅРёСЏ. Рў.Рµ. РґР»СЏ РІСЃРµС… СѓР¶Рµ РёРјРµСЋС‰РёС…СЃСЏ Р·РЅР°С‡РµРЅРёР№ РІР°С€РµР№ РїРµСЂРµРјРµРЅРЅРѕР№ Р±СѓРґРµС‚ РїРѕСЃС‡РёС‚Р°РЅРѕ Р·РЅР°С‡РµРЅРёСЏ СЌС‚РѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ РёСЃС…РѕРґСЏ РёР· РІР°С€РµР№ РјРѕРґРµР»Рё, С‚Р°РєРёРј РѕР±СЂР°Р·РѕРј РІС‹ СЃРјРѕР¶РµС‚Рµ СѓР·РЅР°С‚СЊ РЅР° СЃРєРѕР»СЊРєРѕ РїСЂРµРґСЃРєР°Р·С‹РІР°РµРјС‹Рµ РІР°С€РµР№ РјРѕРґРµР»СЊСЋ Р·РЅР°С‡РµРЅРёСЏ СЂР°СЃС…РѕРґСЏС‚СЃСЏ СЃ СЂРµР°Р»СЊРЅС‹РјРё РґР°РЅРЅС‹РјРё.</p>
<pre class="r"><code>predict(mod)</code></pre>
<pre><code>##        1        2        3        4        5        6        7        8 
## 3672.386 2525.082 3390.972 3629.091 3282.735 2936.379 3564.150 3888.858 
##        9       10       11       12       13       14       15       16 
## 4213.567 3888.858 4516.629 2958.027 3477.561 3239.441 3390.972 3455.913 
##       17       18       19       20       21       22       23       24 
## 3910.506 3217.794 3390.972 3499.208 3152.852 3845.564 3390.972 2741.554 
##       25       26       27       28       29       30       31       32 
## 3239.441 3174.499 3239.441 3520.855 3174.499 3131.205 3520.855 2958.027 
##       33       34       35       36       37       38       39       40 
## 3412.619 3672.386 3087.910 3347.677 3715.680 3845.564 3001.321 3564.150 
##       41       42       43       44       45       46       47       48 
## 3758.975 2763.201 3174.499 3607.444 3217.794 3455.913 3066.263 2828.143</code></pre>
<p>Р¤СѓРЅРєС†РёСЏ resid() (РѕСЃС‚Р°С‚РєРё РёР»Рё РѕС‚РєР»РѕРЅРµРЅРёСЏ) РїРѕСЃС‡РёС‚Р°РµС‚ СЂР°Р·РЅРёС†Сѓ РјРµР¶РґСѓ РєР°Р¶РґС‹Рј РёРјРµСЋС‰РёРјСЃСЏ Сѓ РІР°СЃ Р·РЅР°С‡РµРЅРёРµРј РјРѕРґРµР»РёСЂСѓРµРјРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ Рё РїСЂРµРґСЃРєР°Р·Р°РЅРЅС‹Рј РІР°С€РµР№ РјРѕРґРµР»СЊСЋ СЂРµР·СѓР»СЊС‚Р°С‚РѕРј (С‚Рѕ С‡С‚Рѕ РІР°Рј СЃС‡РёС‚Р°Р»Р° РїСЂРµРґС‹РґСѓС‰Р°СЏ С„СѓРЅРєС†РёСЏ).</p>
<pre class="r"><code>resid(mod)</code></pre>
<pre><code>##            1            2            3            4            5 
##   665.114163  1042.018405   334.228411   786.308663   -81.135339 
##            6            7            8            9           10 
##    88.120658  -917.849587   107.941665   240.132917   291.741665 
##           11           12           13           14           15 
##  -573.828580  -702.426592   194.439412  -508.540840   270.428411 
##           16           17           18           19           20 
##  -631.913338   538.694415  -692.793590   397.428411  -704.407838 
##           21           22           23           24           25 
##   207.848160  -202.963835   531.928411    86.345907   -55.540840 
##           26           27           28           29           30 
##   590.500910  -786.540840 -1134.355088  1344.300910  -818.204590 
##           31           32           33           34           35 
##   622.844912  -725.826592   282.481162   475.814163   160.589909 
##           36           37           38           39           40 
##  -739.577089  -844.780336   716.636165  -975.121091   868.450413 
##           41           42           43           44           45 
##   749.625164   761.798657  -597.299090  -921.344087   866.106410 
##           46           47           48 
##  -418.513338  -193.962841     5.056907</code></pre>
</div>
<div id="section-5" class="section level3">
<h3>РРЅС‚РµСЂРїСЂРµС‚РёСЂСѓРµРј РґР°РЅРЅС‹Рµ РјРѕРґРµР»РµР№</h3>
<p>РљР°Рє СѓР¶Рµ Рё РіРѕРІРѕСЂРёР»РѕСЃСЊ СЂР°РЅРµРµ Р»РёРЅРµР№РЅС‹Рµ РјРѕРґРµР»Рё РЅР°РёР±РѕР»РµРµ РїСЂРёРјРёС‚РёРІРЅС‹Рµ, Р° РїРѕС‚РѕРјСѓ Р»СѓС‡С€Рµ РІСЃРµРіРѕ РїРѕРґРґР°СЋС‰РёРµСЃСЏ РёРЅС‚РµСЂРїСЂРµС‚Р°С†РёРё <span class="math inline">\(y{i}=\alpha+\beta x+\epsilon\)</span></p>
<p><span class="math inline">\(\alpha\)</span> СЌС‚Рѕ Р·РЅР°С‡РµРЅРёРµ РЅР°С€РµР№ РїРµСЂРµРјРµРЅРЅРѕР№ РїСЂРё x СЂР°РІРЅРѕРј 0.</p>
<p><span class="math inline">\(\beta\)</span> РїСЂРµРґРїРѕР»Р°РіР°РµРјРѕРµ СѓРІРµР»РёС‡РµРЅРёРµ Р·РЅР°С‡РµРЅРёСЏ y РІС‹Р·РІР°РЅРЅРѕРµ СѓРІРµР»РёС‡РµРЅРёРµРј x РЅР° РѕРґРЅСѓ РµРґРёРЅРёС†Сѓ</p>
<p>Р”Р»СЏ РїРѕР»СѓС‡РµРЅРёСЏ РєРѕСЌС„РёС†РёРµРЅС‚РѕРІ РІР°С€РµР№ РјРѕРґРµР»Рё РІС‹ РјРѕР¶РµС‚Рµ РІРѕСЃРїРѕР»СЊР·РѕРІР°С‚СЊСЃСЏ СЃР»РµРґСѓСЋС‰РёРјРё Р°Р±СЃРѕР»СЋС‚РЅРѕ РёРґРµРЅС‚РёС‡РЅС‹РјРё С„СѓРЅРєС†РёСЏРјРё:</p>
<pre class="r"><code>coef(mod)</code></pre>
<pre><code>## (Intercept)         low 
##  4256.86158    21.64725</code></pre>
<pre><code>## (Intercept)         low 
##  4256.86158    21.64725</code></pre>
<pre class="r"><code>coefficients(mod)</code></pre>
<pre><code>## (Intercept)         low 
##  4256.86158    21.64725</code></pre>
<pre><code>## (Intercept)         low 
##  4256.86158    21.64725</code></pre>
<p>РС… РІС‹РґР°С‡Р° РјРѕР¶РµС‚ РїРѕРєР°Р·Р°С‚СЊСЃСЏ РЅРµ РѕС‡РµРЅСЊ СЏСЃРЅРѕР№, РЅРѕ РґРѕСЃС‚Р°С‚РѕС‡РЅРѕ РІСЃРїРѕРјРЅРёС‚СЊ, С‡С‚Рѕ <span class="math inline">\(\alpha\)</span> СЌС‚Рѕ С‚РѕС‡РєР°, РІ РєРѕС‚РѕСЂРѕР№ РїСЂСЏРјР°СЏ С…Р°СЂР°РєС‚РµСЂРёР·СѓСЋС‰Р°СЏ РЅР°С€Сѓ РјРѕРґРµР»СЊ РїРµСЂРµСЃРµРєР°РµС‚ РѕСЃСЊ y Рё СЃС‚Р°РЅРѕРІРёС‚СЃСЏ РґРѕРІРѕР»СЊРЅРѕ РѕС‡РµРІРёРґРЅРѕ, С‡С‚Рѕ РїСЂРµРґСЃС‚Р°РІР»РµРЅРЅРѕРµ РЅР°Рј Р·Р°РЅС‡РµРЅРёРµ Intercept РЅРµ С‡С‚Рѕ РёРЅРѕРµ, РєР°Рє РєРѕСЌС„С„РёС†РёРµРЅС‚ <span class="math inline">\(\alpha\)</span>. РќСѓ РѕСЃС‚Р°РІС€РµРµСЃСЏ Р·РЅР°С‡РµРЅРёРµ low СЌС‚Рѕ РєРѕСЌС„С„РёС†РёРµРЅС‚ <span class="math inline">\(\beta\)</span>.</p>
<p>РўР°РєРёРј РѕР±СЂР°Р·РѕРј РґР»СЏ РЅР°С€РµР№ РјРґРµР»РёСЂСѓРµРјРѕР№ РїРµСЂРјРµРЅРЅРѕР№ tc2009 Р·РЅР°С‡РµРЅРёРµ РїСЂРё low = -10 СЃРѕСЃС‚Р°РІРёС‚ 4256.86 + 21.6 * (-10) = 4040.86. РР·РјРµРЅРµРЅРёРµ РїРµСЂРµРјРµРЅРЅРѕР№ low РЅР° РµРґРёРЅРёС†Сѓ РїСЂРёРІРµРґРµС‚ Рє РёР·РјРµРЅРµРЅРёСЋ РЅР° 21.6 РІ РїРµСЂРµРјРµРЅРЅРѕР№ tc2009</p>
<p>РџРѕСЃС‚СЂРѕРёРј РіСЂР°С„РёРє Р·Р°РІРёСЃРёРјРѕС‚СЃРё РїСЂРµРґСЃРєР°Р·С‹РІР°РµРјС‹С… РЅР°С€РµР№ С„СѓРЅРєС†РёРµР№ Р·РЅР°С‡РµРЅРёР№ РѕС‚ РЅРµР·Р°РІРёСЃРёРјРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ low, РІРѕСЃРїРѕР»СЊР·СѓРµРјСЃСЏ РґР»СЏ СЌС‚РѕРіРѕ С„СѓРЅРєС†РёРµР№ predict()</p>
<pre class="r"><code>qplot(low, predict(mod), data = crime, geom = &quot;line&quot;)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>Р›РѕРіРёС‡РЅРѕ, С‡С‚Рѕ РґР»СЏ РїРѕСЃС‚СЂРѕРµРЅРёСЏ СЌС‚РѕРіРѕ РіСЂР°С„РёРєР° РјС‹ РёСЃРїРѕР»СЊР·РѕРІР°Р»Рё geom = “line”, С‡С‚Рѕ СЂР°РІРЅРѕР·РЅР°С‡РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°РЅРёСЋ <code>+geom_line()</code>, С‚.Рє. РЅР°С€Р° Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ Р»РёРЅРµР№РЅР° Рё СЌС‚Рѕ РёРјРµРЅРЅРѕ С‚РѕС‚ С‚РёРї РіСЂР°С„РёРєР°, РєРѕРѕСЂС‹Р№ РјС‹ С…РѕС‚РёРј РїРѕР»СѓС‡РёС‚СЊ. РњРµР¶ С‚РµРј, ggplot РїРѕР·РІРѕР»СЏРµС‚ РЅР°Рј РїРѕСЃС‚СЂРѕРёС‚СЊ РјРѕРґРµР»СЊ РјРѕРґРµР» РїСЂСЏРјРѕ РїСЂРё СЃРѕР·РґР°РЅРёРё РіСЂР°С„РёРєР° Рё, РєР°Рє РЅРё СЃС‚СЂР°РЅРЅРѕ РјС‹ СѓР¶Рµ РґРµР»Р°Р»Рё СЌС‚Рѕ РЅР° РїСЂРµРґС‹РґСѓС‰РёС… Р·Р°РЅСЏС‚РёСЏС…. Р”Р»СЏ СЌС‚РѕРіРѕ СЃСѓС‰РµСЃС‚РІСѓРµС‚ СѓР¶Рµ С…РѕСЂРѕС€Рѕ РёР·РІРµСЃС‚РЅР°СЏ РЅР°Рј РіРµРѕРјРµС‚СЂРёСЏ <code>geom_smooth()</code>. РџСЂР°РІРґР° РґР»СЏ С‚РѕРіРѕ С‡С‚РѕР±С‹ РїРѕР»СѓС‡РёС‚СЊ Р°РЅР°Р»РѕРіРёС‡РЅС‹Р№ РїСЂРµРґС‹РґСѓС‰РµРјСѓ РіСЂР°С„РёРє, РјС‹ РґРѕР»Р¶РЅС‹ СЏРІРЅРѕ РѕР±СЉСЏРІРёС‚СЊ С„СѓРЅРєС†РёРё РіРµРѕРјРµС‚СЂРё С‚РѕС‚ С‚РёРї, С‡С‚Рѕ РјС‹ СѓСЃРїРѕР»СЊР·РѕРІР°Р»Рё, С‚.Рµ. <code>geom_smooth(method=lm)</code>, СЃРѕРѕС‚РІРµС‚СЃС‚РІРµРЅРЅРѕ ggplot Р±СѓРґРµС‚ Р·РЅР°С‚СЊ С‡С‚Рѕ РЅР°С€Р° РјРѕРґРµР»СЊ Р±СѓРґРµС‚ РёРјРµС‚СЊ РѕР±Р±С‰РёР№ РІРёРґ <code>lm(x~y, crime)</code>. Р”РѕР±Р°РІР»РµРЅРёРµ РїР°СЂР°РјРµС‚СЂР° <code>se=FALSE</code> СѓР±РµСЂРµС‚ РґРѕРІРµСЂРёС‚РµР»СЊРЅС‹Рµ РёРЅС‚РµСЂРІР°Р»С‹, РєРѕС‚РѕСЂС‹Рµ С‡Р°С‰Рµ РІРІРѕРґСЏС‚ РІ Р·Р°Р±Р»СѓР¶РґРµРЅРёРµ, С‡РµРј РїРѕРјРѕРіР°СЋС‚.</p>
<pre class="r"><code>qplot(low, tc2009, data = crime) + 
  geom_smooth(method = lm)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<pre class="r"><code>qplot(low, tc2009, data = crime) +
  geom_smooth(se = FALSE, method = lm)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p><strong><em>Р’Р°Р¶РЅРѕ</em></strong>. РџРѕ СѓРјРѕР»С‡Р°РЅРёСЋ R РїС‹С‚Р°РµС‚СЃСЏ РґРѕР±Р°РІРёС‚СЊ <span class="math inline">\(\alpha\)</span> РІ РєР°Р¶РґСѓСЋ Р»РёРЅРµР№РЅСѓСЋ РјРѕРґРµР»СЊ . Рў.Рµ. R СЃС‚СЂРѕРёС‚ РјРѕРґРµР»СЊ РёСЃС…РѕРґСЏ РёР· С‚РѕРіРѕ, С‡С‚Рѕ <span class="math inline">\(\alpha\)</span> РЅРµ СЂР°РІРЅР° 0. РњРµР¶ С‚РµРј РјС‹ РјРѕР¶РµРј Р·Р°СЃС‚Р°РІРёС‚СЊ R СЃС‚СЂРѕРёС‚СЊ РјРѕРґРµР»СЊ РёСЃС…РѕРґСЏ РёР· С‚РѕРіРѕ, С‡С‚Рѕ <span class="math inline">\(\alpha\)</span> СЂР°РІРЅР° 0. Рў.Рµ. РіСЂР°С„РёРє РЅР°С€РµР№ С„СѓРЅРєР№РёРё РґРѕР»Р¶РµРЅ РѕР±СЏР·Р°С‚РµР»СЊРЅРѕ РїСЂРѕС…РѕРґРёС‚СЊ С‡РµСЂРµР· РєРѕРѕСЂРґРёРЅР°С‚С‹ (0, 0).</p>
<p>Р”Р»СЏ С‚РѕРіРѕ С‡С‚РѕР±С‹ R РёСЃС…РѕРґРёР» РёР· С‚РѕРіРѕ, С‡С‚Рѕ <span class="math inline">\(\alpha\)</span> СЂР°РІРЅР° 0 РІ С„РѕСЂРјСѓР»Сѓ РјРѕРґРµР»Рё РЅСѓР¶РЅРѕ РґРѕР±Р°РІРёС‚СЊ 0 РёР»Рё -1. Р”РѕР±Р°РІР»РµРЅРёРµ Рє С„РѕСЂРјСѓР»Рµ +1 Р·Р°СЃС‚Р°РІР»СЏРµС‚ R СЃС‚РѕРёС‚СЊ РјРѕРґРµР»СЊ РёСЃС…РѕРґСЏ РёР· С‚РѕРіРѕ, С‡С‚Рѕ <span class="math inline">\(\alpha\)</span> РЅРµ СЂР°РІРЅР° 0. Р Р°СЃСЃРјРѕС‚СЂРёРј СЃР»РµРґСѓСЋС‰РёРµ РїСЂРёРјРµСЂС‹:</p>
<p>Р’РєР»СЋС‡Р°РµРј <span class="math inline">\(\alpha\)</span> РІ РјРѕРґРµР»СЊ</p>
<pre class="r"><code>lm(tc2009 ~ 1 + low, data = crime)</code></pre>
<pre><code>## 
## Call:
## lm(formula = tc2009 ~ 1 + low, data = crime)
## 
## Coefficients:
## (Intercept)          low  
##     4256.86        21.65</code></pre>
<pre class="r"><code>lm(tc2009 ~ low, data = crime)</code></pre>
<pre><code>## 
## Call:
## lm(formula = tc2009 ~ low, data = crime)
## 
## Coefficients:
## (Intercept)          low  
##     4256.86        21.65</code></pre>
<pre class="r"><code>qplot(low, predict(lm(tc2009 ~ 1 + low, data = crime)), data = crime, geom = &quot;line&quot;)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p>РСЃРєР»СЋС‡Р°РµРј <span class="math inline">\(\alpha\)</span> РёР· РјРѕРґРµР»Рё</p>
<pre class="r"><code>lm(tc2009 ~ low - 1, data = crime)</code></pre>
<pre><code>## 
## Call:
## lm(formula = tc2009 ~ low - 1, data = crime)
## 
## Coefficients:
##    low  
## -67.36</code></pre>
<pre class="r"><code>lm(tc2009 ~ 0 + low, data = crime)</code></pre>
<pre><code>## 
## Call:
## lm(formula = tc2009 ~ 0 + low, data = crime)
## 
## Coefficients:
##    low  
## -67.36</code></pre>
<pre class="r"><code>qplot(low, predict(lm(tc2009 ~ low - 1, data = crime)), data = crime, geom = &quot;line&quot;)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>РљР°Рє РІС‹ РјРѕРіР»Рё Р·Р°РјРµС‚РёС‚СЊ РІРєР»СЋС‡РµРЅРёРµ РёР»Рё РёСЃРєР»СЋС‡РµРЅРёРµ $$$$ РєРѕСЂРµРЅРЅС‹Рј РѕР±СЂР°Р·РѕРј РјРµРЅСЏРµС‚ РЅР°С€Сѓ РјРѕРґРµР»СЊ. РџРѕСЌС‚РѕРјСѓ Рє РїРѕРґРѕР±РЅРѕРјСѓ РїСЂРёРµРјСѓ СЃС‚РѕРёС‚ РїСЂРёР±РµРіР°С‚СЊ С‚РѕР»СЊРєРѕ РІ С‚РµС… СЃР»СѓС‡Р°СЏС… РєРѕРіРґР° РІС‹ С‚РѕС‡РЅРѕ СѓРІРµСЂРµРЅС‹ РІ С‚РѕРј, С‡С‚Рѕ РІР°С€Р° С„СѓРЅРєС†РёСЏ РїСЂРѕС…РѕРґРёС‚ РёР»Рё РЅРµ РїСЂРѕС…РѕРґРёС‚ С‡РµСЂРµР· РЅР°С‡Р°Р»Рѕ РєРѕРѕСЂРґРёРЅР°С‚.</p>
<p>Р”Р°РІР°Р№С‚Рµ С‚РµРїРµСЂСЊ РІРѕСЃРїРѕР»СЊР·СѓРµРјСЃСЏ РґСЂСѓРіРёРј РЅР°Р±РѕСЂРѕРј РґР°РЅРЅС‹С…, РєРѕС‚РѕСЂС‹Р№ РјС‹ СѓР¶Рµ СѓСЃРїРµР»Рё Р·Р°РіСЂСѓР·РёС‚СЊ - wages. Р”Р°РЅРЅР°СЏ С‚Р°Р±Р»РёС†Р° СЃРѕРґРµСЂР¶РёС‚ РґР°РЅРЅС‹Рµ, РєРѕС‚РѕСЂС‹Рµ Р±С‹Р»Рё СЃРѕР±СЂР°РЅС‹ РґР»СЏ РїРѕРїС‹С‚РєРё РѕРїРёСЃР°РЅРёСЏ Р·Р°РІРёСЃРёРјРѕСЃС‚Рё Р·Р°СЂР°Р±РѕС‚РєР° С‡РµР»РѕРІРµРєР° РѕС‚ РµРіРѕ СЂРѕСЃС‚Р°. Р”Р°РІР°Р№С‚Рµ РїРѕСЃС‚СЂРѕРёРј РјРѕРґРµР»СЊ, РєРѕС‚РѕСЂР°СЏ Р±СѓРґРµС‚ РѕРїРёСЃС‹РІР°С‚СЊ С‚Р°РєСѓСЋ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ Рё РїРѕРїС‹С‚Р°РµРјСЃСЏ РёРЅС‚РµСЂРїСЂРµС‚РёСЂРѕРІР°С‚СЊ СЂРµР·СѓР»СЊС‚Р°С‚.</p>
<pre class="r"><code>hmod &lt;- lm(earn ~ height, data = wages)
coef(hmod)</code></pre>
<pre><code>## (Intercept)      height 
## -126523.359    2387.196</code></pre>
<p>Р”Р°РІР°Р№С‚Рµ РїРѕРґСЃС‚Р°РІРёРј РїРѕР»СѓС‡РµРЅРЅС‹Рµ РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РІ РѕР±С‰РµРµ СѓСЂР°РІРЅРµРЅРёРµ Р»РёРЅРµР№РЅРѕР№ СЂРµРіСЂРµСЃСЃРёРё <span class="math inline">\(earn=\alpha+\beta\times height+\epsilon\)</span>. Р’ СЂРµР·СѓР»СЊС‚Р°С‚Рµ РјС‹ РїРѕР»СѓС‡РёРј СЃР»РµРґСѓСЋС‰РµРµ СѓСЂР°РІРЅРµРЅРёРµ:</p>
<p><span class="math inline">\(earn=-126523.36+2387.20\times height+\epsilon\)</span></p>
<p>Р”Р°РІР°Р№С‚Рµ РІСЃРїРѕРјРЅРёРј, С‡С‚Рѕ РїСЂРёСЃСѓС‚СЃС‚РІСѓСЋС‰РёР№ РІ РєРѕРЅС†Рµ РјРЅРѕРіРѕС‡Р»РµРЅР° СЌР»РµРјРµРЅС‚ <span class="math inline">\(\epsilon\)</span> СЏРІР»СЏРµС‚СЃСЏ РїРѕРєР°Р·Р°С‚РµР»РµРј С‚РѕРіРѕ, С‡С‚Рѕ РЅР°С€Р° РјРѕРґРµР»СЊ РЅРµ РјРѕРґРµС‚ Р±С‹С‚СЊ Р°Р±СЃРѕР»СЋС‚РЅРѕР№ С‚РѕС‡РЅРѕР№, Р° РїРѕС‚РѕРјСѓ РІСЃРµРіРґР° РїСЂРёСЃСѓС‚СЃС‚РІСѓРµС‚ РѕС‚РєР»РѕРЅРµРЅРёРµ РѕС‚ СЂРµР°Р»СЊРЅС‹С… РґР°РЅРЅС‹С…. Р’СЃРµ СЌС‚Рё РѕС‚РєР»РѕРЅРµРЅРёСЏ Рё РїСЂРµРґСЃС‚Р°РІР»РµРЅС‹ СЌР»РµРјРµРЅС‚РѕРј <span class="math inline">\(\epsilon\)</span>. Рў.Рє. РјС‹ РЅРµ Р·РЅР°РµРј РѕС€РёР±РєРё РґР»СЏ РєР°Р¶РґРѕРіРѕ РєРѕРЅРєСЂРµС‚РЅРѕРіРѕ Р·РЅР°С‡РµРЅРёСЏ, РІ РїСЂРµРґСЃС‚Р°РІР»РµРЅРёРё СѓСЂР°РІРЅРµРЅРёСЏ РјС‹ Р±СѓРґРµРј Р±СЂР°С‚СЊ <span class="math inline">\(\epsilon\)</span> СЂР°РІРЅС‹Рј РЅСѓР»СЋ, РЅРѕ РїСЂРё СЌС‚РѕРј РїРѕРјРЅРёС‚СЊ, С‡С‚Рѕ РѕС‚РєР»РѕРЅРµРЅРёРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚.</p>
<p>Р”Р°РЅРЅС‹Рµ РїРѕ СЂРѕСЃС‚Сѓ РїСЂРµРґСЃС‚Р°РІР»РµРЅС‹ РІ РґСЋР№РјР°С…. РџРѕСЌС‚РѕРјСѓ РґР»СЏ С‡РµР»РѕРІРµРєР° РІС‹СЃРѕС‚РѕР№ 68 РґСЋР№РјРѕРІ(1,72 РјРµС‚СЂР°) СЂР°СЃС‡РµС‚РЅР°СЏ РїРѕ РґР°РЅРЅС‹Рј РЅР°С€РµР№ РјРѕРґРµР»Рё Р·Р°СЂРїР»Р°С‚Р° СЃРѕСЃС‚Р°РІРёС‚</p>
<p><span class="math inline">\(earn=-126523.36+2387.20\times 68+\epsilon\)</span></p>
<p><span class="math inline">\(earn=35806.24\)</span></p>
<p>Р•С‰Рµ РѕРґРЅРёРј РґРѕРІРѕР»СЊРЅРѕ РїСЂРѕСЃС‚С‹Рј РІС‹РІРѕРґРѕРј РёР· РЅР°С€РµР№ РјРѕРµРґР»Рё Р±СѓРґРµС‚ С‚Рѕ, С‡С‚Рѕ СѓРІРµРґРёС‡РµРЅРёРµ СЂРѕСЃС‚Р° РЅР° 1 РґСЋР№Рј РґРѕР»Р¶РЅРѕ РїСЂРёРІРѕРґРёС‚СЊ Рє СЂРѕСЃС‚Сѓ РґРѕС…РѕРґРѕРІ РЅР° $2387.20 РІ РіРѕРґ.</p>
<pre class="r"><code>qplot(height, earn, data = wages, alpha = I(1/4)) +
  geom_smooth(se = FALSE, method = lm) + theme_bw()</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<div id="section-6" class="section level4">
<h4>Р”Р°РІР°Р№С‚Рµ РїРѕРґРІРµРґРµРј РЅРµР±РѕР»СЊС€РѕР№ РёС‚РѕРі</h4>
<p>РџРѕРґРіРѕРЅРєР° РјРѕРґРµР»Рё РІ R СЃРѕСЃС‚РѕРёС‚ РёР· 3 СЌС‚Р°РїРѕРІ:</p>
<ol style="list-style-type: decimal">
<li><p>РћРїРёСЃР°РЅРёРµ РѕС‚РЅРѕС€РµРЅРёР№ РјРµР¶РґСѓ РёРЅС‚РµСЂРµСЃСѓСЋС‰РёРјРё РЅР°СЃ РїРµСЂРµРјРµРЅРЅС‹РјРё СЃ РїРѕРјРѕС‰СЊСЋ С„РѕСЂРјСѓР»:<code>earn ~ height</code></p></li>
<li><p>РСЃРїРѕР»СЊР·РѕРІР°РЅРёРµ СЃРїРµС†РёР°Р»СЊРЅС‹С… С„РѕСЂРјСѓР» РґР»СЏ “РїРѕРґРіРѕРЅРєРё”(СЃРѕР·РґР°РЅРёСЏ) РјРѕРґРµР»Рё РїРѕ Р·Р°РґР°РЅРЅРѕР№ СЂР°РЅРµРµ С„РѕСЂРјСѓР»Рµ: <code>mod &lt;- lm(earn ~ height, data = wages)</code></p></li>
<li><p>РђРЅР°Р»РёР· РїРѕР»СѓС‡РµРЅРЅРѕРіРѕ СЂРµР·СѓР»СЊС‚Р°С‚Р° СЂР°Р·Р»РёС‡РЅС‹РјРё СЃРїРѕСЃРѕР±Р°РјРё: <code>summary(mod)</code> <code>plot(mod)</code></p></li>
</ol>
</div>
</div>
</div>
<div id="section-7" class="section level2">
<h2>РђРЅР°Р»РёР· РјРѕРґРµР»Рё Рё СЃС‚Р°С‚РёСЃС‚РёС‡РµСЃРєРёРµ РІС‹РІРѕРґС‹</h2>
<p>Р”РѕРІРѕР»СЊРЅРѕ РѕС‡РµРІРёРґРЅРѕ, С‡С‚Рѕ РјРѕРґРЅРѕ РїРѕР»СѓС‡РёС‚СЊ РјРѕРґРµР»Рё РѕРїРёСЃС‹РІР°СЋС‰РёРµ СЃРІСЏР·Рё РјРµР¶РґСѓ СЃРѕРІРµСЂС€РµРЅРЅРѕ РЅРµ СЃРІСЏР·Р°РЅРЅС‹РјРё РґР°РЅРЅС‹РјРё. РўРѕРіРґР° РїРµСЂРµРґ РЅР°РјРё РІСЃС‚Р°РµС‚ РІРѕРїСЂРѕСЃ С‚РѕРіРѕ, Р° РєР°Рє РјС‹ РјРѕР¶РµРј Р±С‹С‚СЊ СѓРІРµСЂРµРЅС‹, С‡С‚Рѕ СЃРІСЏР·СЊ, РєРѕС‚РѕСЂСѓСЋ РЅР°Рј “РѕС‚С‹СЃРєР°Р»Р°” РјРѕРґРµР»СЊ СЃСѓС‰РµСЃС‚РІСѓРµС‚ Рё С…РѕС‚СЊ СЃРєРѕР»СЊРєРѕ-РЅРёР±СѓРґСЊ С‚РѕС‡РЅР°. РќР°РёРјРµРЅСЊС€Р°СЏ СЃСѓРјРјР° РєРІР°РґСЂР°С‚РѕРІ РѕС‚РєР»РѕРЅРµРЅРёР№, РєРѕРЅРµС‡РЅРѕ С…РѕСЂРѕС€РёР№ РїРѕРєР°Р·Р°С‚РµР»СЊ, РЅРѕ РЅР°РґРѕ РїРѕРЅРёРјР°С‚СЊ, С‡С‚Рѕ СЌС‚РѕС‚ РїРѕРєР°Р·Р°С‚РµР»СЊ РЅРёС‡РµРіРѕ РЅР°Рј РЅРµ РіР°СЂР°РЅС‚РёСЂСѓРµС‚.</p>
<p>Р•СЃР»Рё РІРµСЂРЅСѓС‚СЊСЃСЏ РѕС‚ РѕР±С‰РµРіРѕ РѕРїРёСЃР°РЅРёСЏ Рє Р±РѕР»РµРµ СЃС‚Р°С‚РёСЃС‚РёС‡РµСЃРєРѕРјСѓ, РјРѕРґРµР»СЊ, РєРѕС‚РѕСЂСѓСЋ РјС‹ РїРѕР»СѓС‡Р°РµРј Р±Р»Р°РіРѕРґР°СЂСЏ R, РїСЂРµРґСЃС‚Р°РІР»СЏРµС‚ С‚РѕР»СЊРєРѕ С‚РѕС‚ РЅРµР±РѕР»СЊС€РѕР№ РѕР±СЉРµРј РґР°РЅРЅС‹С…, С‡С‚Рѕ Сѓ РЅР°СЃ РµСЃС‚СЊ, РёР»Рё РІС‹Р±РѕСЂРєСѓ. РќР°СЃ Р¶Рµ РІСЃРµРіРґР° РёРЅС‚РµСЂРµСЃСѓРµС‚ РјРѕРґРµР»СЊ, РєРѕС‚РѕСЂР°СЏ РѕРїРёСЃС‹РІР°РµС‚ РіРµРЅРµСЂР°Р»СЊРЅСѓСЋ СЃРѕРІРѕРєСѓРїРЅРѕСЃС‚СЊ. РўР°РєРёРј РѕР±СЂР°Р·РѕРј, Р±РѕР»СЊС€Рµ РІСЃРµРіРѕ РІ РїРѕР»СѓС‡РµРЅРЅРѕР№ РЅР°РјРё РјРѕРґРµР»Рё РЅР°СЃ Р±СѓРґРµС‚ РёРЅС‚РµСЂРµСЃРѕРІР°С‚СЊ С‚Рѕ, РЅР° СЃРєРѕР»СЊРєРѕ РѕРЅР° РѕС‚Р»РёС‡Р°РµС‚СЃСЏ РѕС‚ РјРѕРґРµР»Рё РіРµРЅРµСЂР°Р»СЊРЅРѕР№ СЃРѕРІРѕРєСѓРїРЅРѕСЃС‚Рё.</p>
<p>Р”Р°РІР°Р№С‚Рµ Р·Р°РіСЂСѓР·РёРј РґР°РЅРЅС‹Рµ РєРѕС‚РѕСЂС‹Рµ СЃРѕРґРµСЂР¶Р°С‚ 100 СЃРѕРІРµСЂС€РµРЅРЅРѕ СЃР»СѓС‡Р°Р№РЅРѕ РѕС‚РѕР±СЂР°РЅРЅС‹С… Р·РЅР°С‡РµРЅРёР№ РёР· РїСЂРµРґС‹РґСѓС‰РµРіРѕ РЅР°Р±Р±СЂР° РґР°РЅРЅС‹С… Рё РїРѕСЃС‚СЂРѕРёРј РіСЂР°С„РёРє РїРѕР»СѓС‡РµРЅРЅС‹С… РґР°РЅРЅС‹С….</p>
<pre class="r"><code>w1 &lt;- read.csv(&quot;https://dl.dropboxusercontent.com/s/qnybbt5sxiedsd7/w1.csv?dl=0&quot;)
qplot(height, earn, data = w1) +  geom_smooth(method = lm, se = F)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>РџРѕСЃС‚СЂРѕРёРј Р°РЅР°Р»РѕРіРёС‡РЅС‹Р№ РіСЂР°С„РёРє РґР»СЏ РІСЃРµРіРѕ РѕР±СЉРµРјР° РґРѕСЃС‚СѓРїРЅС‹С… РґР°РЅРЅС‹С….</p>
<pre class="r"><code>qplot(height, earn, data = wages) +  geom_smooth(method = lm, se = F)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>Р”Р°РІР°Р№С‚Рµ Р·Р°РґР°РґРёРјСЃСЏ РІРѕРїСЂРѕСЃРѕРј Рѕ С‚РѕРј, Р° С‡С‚Рѕ Р±СѓРґРµС‚ РµСЃР»Рё РјС‹ РІРѕР·СЊРјРµРј РґСЂСѓРіСѓСЋ РІС‹Р±РѕСЂРєСѓ? Р‘СѓРґРµС‚ Р»Рё <span class="math inline">\(\beta\)</span> = <span class="math inline">\(\beta\)</span> РµСЃР»Рё РјС‹ РІРѕР·СЊРјРµРј РґСЂСѓРіСѓСЋ РІС‹Р±РѕСЂРєСѓ? РЎРєРѕСЂРµРµ РІСЃРµРіРѕ РЅРµС‚. Р‘СѓРґРµС‚ Р»Рё <span class="math inline">\(\beta\)</span> = 0, РµСЃР»Рё РјС‹ РІРѕР·СЊРјРµРј РґСЂСѓРіСѓСЋ РІС‹Р±РѕСЂРєСѓ? Р’РѕР·РјРѕР¶РЅРѕ.</p>
<p>РЎР»РµРґСѓРµС‚ СЃРґРµР»Р°С‚СЊ РІР°Р¶РЅРѕРµ РѕС‚СЃС‚СѓРїР»РµРЅРёРµ. Р—РЅР°С‡РµРЅРёРµ <span class="math inline">\(\beta\)</span> = 0 СЃРёР»СЊРЅРѕ РѕС‚Р»РёС‡Р°РµС‚СЃСЏ РїРѕ РІР°Р¶РЅРѕСЃС‚Рё РґР»СЏ РЅР°СЃ РѕС‚ РІСЃРµС… РѕСЃС‚Р°Р»СЊРЅС‹С… Р·РЅР°С‡РµРЅРёР№, С‚.Рє. РѕРЅРѕ Р±СѓРґРµС‚ Р·РЅР°С‡РёС‚СЊ, С‡С‚Рѕ РёР·РјРµРЅРµРЅРёРµ РЅРµР·Р°РІРёСЃРёРјРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ РЅРµ РїСЂРёРІРѕРґРёС‚ Рє РёР·РјРµРЅРµРЅРёСЋ Р·Р°РІРёСЃРёРјРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№. Р”СЂСѓРіРёРјРё СЃР»РѕРІР°РјРё, РѕРЅРѕ Р±СѓРґРµС‚ Р·РЅР°С‡РёС‚СЊ, С‡С‚Рѕ Сѓ РЅР°СЃ РЅРµС‚ СЃРІСЏР·Рё РјРµР¶РґСѓ РЅР°С€РёРјРё РїРµСЂРµРјРµРЅС‹РјРё.</p>
<p>Рђ РєР°РєРѕРІ РёРЅРµС‚СЂРІР°Р» РІ РєРѕС‚РѕСЂРѕРј Р»РµР¶Р°С‚ РІСЃРµ РІРѕР·РјРѕР¶РЅС‹Рµ Р·РЅР°С‡РµРЅРёСЏ <span class="math inline">\(\beta\)</span>?</p>
<p>Р”Р»СЏ РѕС‚РІРµС‚Р° РЅР° СЌС‚РѕС‚ РІРѕРїСЂРѕСЃ РµСЃС‚СЊ РґРІР° РёРЅСЃС‚СЂСѓРјРµРЅС‚Р°Р»СЊРЅС‹С… РїРѕРґС…РѕРґР° - РїРѕРґС…РѕРґС‹ РґР»СЏ СЂР°СЃСЃСѓР¶РґРµРЅРёР№ Рѕ РЅРµРѕРїСЂРµРґРµР»РµРЅРЅРѕСЃС‚Рё РїР°СЂР°РјРµС‚СЂРѕРІ РјРѕРґРµР»Рё</p>
<ul>
<li>РїР°СЂР°РјРµС‚СЂРёС‡РµСЃРєР°СЏ СЃС‚Р°С‚РёСЃС‚РёРєР°</li>
<li>РЅРµРїР°СЂР°РјРµС‚СЂРёС‡РµСЃРєР°СЏ СЃС‚Р°С‚РёСЃС‚РёРєР° (Р±СѓС‚СЃС‚СЂР°РїРёСЂРѕРІР°РЅРёРµ РёР»Рё СЃР°РјРѕРЅР°СЃС‚СЂРѕР№РєР°)</li>
</ul>
<div id="section-8" class="section level3">
<h3>РџР°СЂР°РјРµС‚СЂРёС‡РµСЃРєР°СЏ СЃС‚Р°С‚РёСЃС‚РёРєР°</h3>
<p>Р•СЃР»Рё РјРѕРґРµР»СЊ СѓРґРѕРІР»РµС‚РІРѕСЂСЏРµС‚ СЂСЏРґСѓ РїСЂРµРґРїРѕР»РѕР¶РµРЅРёР№, С‚Рѕ СЃСѓС‰РµСЃС‚РІСѓРµС‚ РІРѕР·РјРѕР¶РЅРѕСЃС‚СЊ РІС‹С‡РёСЃР»РёС‚СЊ РІРµСЂРѕСЏС‚РЅРѕСЃС‚СЊ РЅР°Р±Р»СЋРґРµРЅРёСЏ РѕРїСЂРµРґРµР»РЅРЅРѕР№ ОІ, РґР°Р¶Рµ РІ С‚Рѕ РІСЂРµРјСЏ РєР°Рє РёСЃС‚РёРЅРЅР°СЏ ОІ=0. Р•СЃР»Рё РІС‹ РІСЃРїРѕРјРЅРёС‚Рµ РєСѓСЂСЃ СЃС‚Р°С‚РёСЃС‚РёРєРё, С‚Рѕ РїРѕР№РјРµС‚Рµ, С‡С‚Рѕ РјС‹ РїСЂРѕСЃС‚Рѕ РґСѓСЂРіРёРјРё СЃР»РѕРІР°РјРё СЃС„РѕСЂРјСѓР»РёСЂРѕРІР°Р»Рё РЅСѓР»РµРІСѓСЋ РіРёРїРѕС‚РµР·Сѓ РґР»СЏ СЂРµРіСЂРµСЃСЃРёРѕРЅРѕРіРѕ Р°РЅР°Р»РёР·Р°. РљРѕС‚РѕСЂР°СЏ СЃРѕСЃС‚РѕСЏР»Р° РІ С‚РѕРј, С‡С‚Рѕ РіРµРЅРµСЂР°Р»СЊРЅС‹Р№ СѓРіР»РѕРІРѕР№ РєРѕСЌС„С„РёС†РёРµРЅС‚ Р»РёРЅРёРё СЂРµРіСЂРµСЃСЃРёРё ОІ СЂР°РІРµРЅ РЅСѓР»СЋ.</p>
<p>Р”Р»СЏ С‚РѕРіРѕ, С‡С‚РѕР±С‹ СЂР°Р·РѕР±СЂР°С‚СЊСЃСЏ РІ СЌС‚РѕРј РіР»СѓР±Р¶Рµ, РґР°РІР°Р№С‚Рµ СЂР°СЃСЃРјРѕС‚СЂРёРј РєРѕРЅРєСЂРµС‚РЅС‹Р№ РїСЂРёРјРµСЂ. Р”Р»СЏ СЌС‚РѕРіРѕ РІРµСЂРЅРµРјСЃСЏ Рє РјРѕРґРµР»Рё Р·Р°РІРёСЃРёРјРѕСЃС‚Рё Р·Р°СЂР°Р±РѕС‚РєР° РѕС‚ СЂРѕСЃС‚Р°: <code>hmod</code>:</p>
<pre class="r"><code>summary(hmod)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height, data = wages)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -47903 -19744  -5184  11642 276796 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -126523      14076  -8.989   &lt;2e-16 ***
## height          2387        211  11.312   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 29910 on 1377 degrees of freedom
## Multiple R-squared:  0.08503,    Adjusted R-squared:  0.08437 
## F-statistic:   128 on 1 and 1377 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Р Р°СЃСЃРјРѕС‚СЂРёРј РїРѕРґСЂРѕР±РЅРµРµ РїСЂРµРґР»РѕР¶РµРЅРЅСѓСЋ РЅР°Рј РІС‹РґР°С‡Сѓ. <code>#      Estimate Std. Error t value   Pr(&gt;|t|)</code> `<code># height   2387        211   11.312    &lt;2e-16 ***</code></p>
<p>Р’РµСЂРѕСЏС‚РЅРѕСЃС‚СЊ С‚РѕРіРѕ, С‡С‚Рѕ <span class="math inline">\(\beta_{height} &gt;= 2387\)</span> РїСЂРё СѓСЃР»РѕРІРёРё, С‡С‚Рѕ РёСЃС‚РёРЅРЅР°СЏ <span class="math inline">\(\beta=0\)</span> РІ РїСЂРµРґСЃС‚Р°РІР»РµРЅРЅРѕРј РЅР°Рј РїСЂРёРјРµСЂРµ РїСЂР°РєС‚РёС‡РµСЃРєРё СЂР°РІРЅР° 2Рµ-16 (РїСЂР°РєС‚РёС‡РµСЃРєРё 0). РР»Рё РґСЂСѓРіРёРјРё СЃР»РѕРІР°РјРё, РІРµСЂРѕСЏС‚РЅРѕСЃС‚СЊ РЅСѓР»РµРІРѕР№ РіРёРїРѕС‚РµР·С‹ СЂР°РІРЅР° РїСЂРµРґРµР»СЊРЅРѕ РјР°Р»РѕР№ РІРІРµР»РёС‡РёРЅРµ, Р° Р·РЅР°С‡РёС‚ РјС‹ РјРѕР¶РµРј СЃРєР°Р·Р°С‚СЊ, С‡С‚Рѕ <span class="math inline">\(\beta\)</span> РЅРµ СЂР°РІРµРЅ РЅСѓР»СЋ.</p>
<p>Р•СЃР»Рё Р±С‹С‚СЊ СЃРѕРІСЃРµРј С‚РѕС‡РЅС‹РјРё, РЅРёР·РєРё p-Р·РЅР°С‡РµРЅРёСЏ ( &lt; 0.05), РјРѕРіСѓС‚ Р±С‹С‚СЊ СЂРµР·СѓР»СЊС‚Р°С‚РѕРј СЃР»РµРґСѓСЋС‰РёС… СЃРѕР±С‹С‚РёР№ 1. РЈ РЅР°СЃ РєСЂР°Р№РЅРµ РЅРµ СЂРµРїСЂРµР·РµРЅС‚Р°С‚РёРІРЅР°СЏ РІС‹Р±РѕСЂРєР° 2. РСЃС‚РёРЅРЅР°СЏ ОІ РіРµРЅРµСЂР°Р»СЊРЅРѕР№ СЃРѕРІРѕРєСѓРїРЅРѕСЃС‚Рё РЅРµ СЂР°РІРЅР° 0 3. РќР°С€Р° РјРѕРґРµР»СЊ РІ РїСЂРёРЅС†РёРїРµ РЅРµ РєРѕСЂСЂРµРєС‚РЅР°</p>
<p>Р’РѕР·РЅРёРєР°РµС‚ Р»РѕРіРёС‡РЅС‹Р№ РІРѕРїСЂРѕСЃ, РЅРѕ РµСЃР»Рё РјС‹ РґРѕРєР°Р·Р°Р»Рё С‡С‚Рѕ ОІ РЅРµ РЅРѕР»СЊ, С‚Рѕ С‡РµРјСѓ Р¶Рµ РѕРЅР° СЂР°РІРЅР°. Рљ СЃРѕР¶Р°Р»РµРЅРёСЋ Сѓ РЅР°СЃ РЅРµС‚ РґСЂСѓРіРёС… РґР°РЅРЅС‹С…, РєСЂРѕРјРµ РїРѕР»СѓС‡РµРЅРЅС‹С… РѕС‚ РјРѕРґРµР»Рё, РїРѕСЌС‚РѕРјСѓ РЅР°РёР±РѕР»РµРµ РїСЂР°РІРёР»СЊРЅС‹Рј Р±СѓРґРµС‚ РїСЂРµРґРїРѕР»РѕР¶РёС‚СЊ, С‡С‚Рѕ ОІ = 2387.</p>
<p>Р—Р°РјРµС‚РёРј, РѕРґРЅР°РєРѕ, С‡С‚Рѕ РЅР°Р№РґРµРЅРЅРѕРµ РЅР°РјРё РЅР°РёР±РѕР»РµРµ РІРµСЂРѕСЏС‚РЅРѕРµ С‚РѕС‡РµС‡РЅРѕРµ Р·РЅР°С‡РµРЅРёРµ ОІ РїСЂРё РїРѕРІС‚РѕСЂРЅС‹С… РёР·РјРµСЂРµРЅРёСЏС… РјРѕР¶РµС‚ РѕРєР°Р·Р°С‚СЊСЃСЏ РёРЅС‹Рј. Р§С‚РѕР±С‹ РѕС…Р°СЂР°РєС‚РµСЂРёР·РѕРІР°С‚СЊ СЌС‚Сѓ РЅРµРѕРїСЂРµРґРµР»РµРЅРЅРѕСЃС‚СЊ, РЅРµРѕР±С…РѕРґРёРјРѕ СЂР°СЃСЃС‡РёС‚Р°С‚СЊ РґРѕРІРµСЂРёС‚РµР»СЊРЅС‹Р№ РёРЅС‚РµСЂРІР°Р» вЂ“ РЅРµ РїСЂРѕС‚РёРІРѕСЂРµС‡Р°С‰РёР№ РёРјРµСЋС‰РёРјСЃСЏ РґР°РЅРЅС‹Рј РґРёР°РїР°Р·РѕРЅ Р·РЅР°С‡РµРЅРёР№, РІ РєРѕС‚РѕСЂРѕРј РЅР°С…РѕРґРёС‚СЃСЏ РёСЃС‚РёРЅРЅРѕРµ Р·РЅР°С‡РµРЅРёРµ РЅР°С€РµР№ РІРµР»РёС‡РёРЅС‹ СЃ РѕРїСЂРµРґРµР»РµРЅРЅРѕР№ РІРµСЂРѕСЏС‚РЅРѕСЃС‚СЊСЋ (РЅР°РїСЂРёРјРµСЂ, 95%). РћСЂРёРµРЅС‚РёСЂРѕРІРѕС‡РЅРѕ РѕС†РµРЅРёС‚СЊ РіСЂР°РЅРёС†С‹ РґРѕРІРµСЂРёС‚РµР»СЊРЅРѕРіРѕ РёРЅС‚РµСЂРІР°Р»Р° РјРѕР¶РЅРѕ, РїСЂРµРґРїРѕР»РѕР¶РёРІ, С‡С‚Рѕ РїСЂРёРјРµСЂРЅРѕ 95% РІСЃРµС… Р·РЅР°С‡РµРЅРёР№ СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ РѕС†РµРЅРѕРє ОІ Р»РµР¶Р°С‚ РІ РґРёР°РїР°Р·РѕРЅРµ В±2<span class="math inline">\(SE{\beta}\)</span> РѕС‚РЅРѕСЃРёС‚РµР»СЊРЅРѕ РµРіРѕ СЃСЂРµРґРЅРµРіРѕ Р·РЅР°С‡РµРЅРёСЏ, РіРґРµ <span class="math inline">\(SE{\beta}\)</span> вЂ“ СЃС‚Р°РЅРґР°СЂС‚РЅР°СЏ РѕС€РёР±РєР° РїР°СЂР°РјРµС‚СЂР° ОІ. РћРґРЅР°РєРѕ РЅРµРѕРїСЂРµРґРµР»РµРЅРЅРѕСЃС‚СЊ РёРјРµРµС‚СЃСЏ РІ РѕС‚РЅРѕС€РµРЅРёРё РЅРµ С‚РѕР»СЊРєРѕ РѕС†РµРЅРєРё РїР°СЂР°РјРµС‚СЂР° ОІ, РЅРѕ Рё РѕС†РµРЅРєРё РµРіРѕ СЃС‚Р°РЅРґР°СЂС‚РЅРѕРіРѕ РѕС‚РєР»РѕРЅРµРЅРёСЏ РґР»СЏ СЃРѕРѕС‚РІРµС‚СЃС‚РІСѓСЋС‰РµРіРѕ РЅРѕСЂРјР°Р»СЊРЅРѕРіРѕ СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ. РќРµ СѓРіР»СѓР±Р»СЏСЏСЃСЊ РІ РґРµС‚Р°Р»Рё, РѕС‚РјРµС‚РёРј, С‡С‚Рѕ РІ СЃРІСЏР·Рё СЃ СЌС‚РёРј РѕР±СЃС‚РѕСЏС‚РµР»СЊСЃС‚РІРѕРј Р±РѕР»РµРµ С‚РѕС‡РЅС‹Рµ Р·РЅР°С‡РµРЅРёСЏ РіСЂР°РЅРёС† РґРѕРІРµСЂРёС‚РµР»СЊРЅРѕРіРѕ РёРЅС‚РµСЂРІР°Р»Р° РґР°РґСѓС‚ РІС‹С‡РёСЃР»РµРЅРёСЏ, РѕСЃРЅРѕРІР°РЅРЅС‹Рµ РЅР° СЃРІРѕР№СЃС‚РІР°С… t- СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ РЎС‚СЊСЋРґРµРЅС‚Р°. РўРѕРіРґР° РіСЂР°РЅРёС†С‹ 95%-РіРѕ РґРѕРІРµСЂРёС‚РµР»СЊРЅРѕРіРѕ РёРЅС‚РµСЂРІР°Р»Р° РґР»СЏ РїР°СЂР°РјРµС‚СЂР° ОІ СЃРѕСЃС‚Р°РІСЏС‚: <span class="math display">\[ОІ В±  t_{0.975} SE{\beta} \]</span>,</p>
<p>РіРґРµ <span class="math inline">\(t_{0.975}\)</span> вЂ“ 0.975-РєРІР°РЅС‚РёР»СЊ t-СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ СЃ (n - p) С‡РёСЃР»РѕРј СЃС‚РµРїРµРЅРµР№ СЃРІРѕР±РѕРґС‹, n вЂ“ РѕР±СЉРµРј РІС‹Р±РѕСЂРєРё, Р° p вЂ“ С‡РёСЃР»Рѕ РїР°СЂР°РјРµС‚СЂРѕРІ РјРѕРґРµР»Рё.</p>
<p>РџРѕР»СѓС‡РёС‚СЊ РёРЅС‚РµСЂРІР°Р» РґР»СЏ Р·Р°РґР°РЅРЅРѕР№ С‚РѕС‡РЅРѕСЃС‚Рё РјРѕР¶РЅРѕ СЃР»РµРґСѓСЋС‰РµР№ РєРѕРјР°РЅРґРѕР№:</p>
<pre class="r"><code>confint(hmod, level = 0.95)</code></pre>
<pre><code>##                   2.5 %     97.5 %
## (Intercept) -154135.798 -98910.920
## height         1973.228   2801.163</code></pre>
<p>Р•С‰Рµ СЂР°Р·, РґР°РЅРЅС‹Рµ РЅР°Рј С†РёС„СЂС‹ РѕР·РЅР°С‡Р°СЋС‚, С‡С‚Рѕ РјС‹ РјРѕР¶РµРј СЃ 95% РІРµСЂРѕСЏС‚РЅРѕСЃС‚СЊСЋ СѓС‚РІРµСЂР¶РґР°С‚СЊ, С‡С‚Рѕ Р·РЅР°С‡РµРЅРёРµ ОІ РЅР°С…РѕРґРёС‚СЃСЏ РІ РґР°РЅРЅРѕРј РЅР°Рј РёРЅС‚РµСЂРІР°Р»Рµ РѕС‚ 1973.228 РґРѕ 2801.163.</p>
<p>Р Р°СЃРјРѕС‚СЂРёРј РµС‰Рµ СЂР°Р· РґР°РЅРЅС‹Рµ РїРѕ СЃРІСЏР·Рё РјРµР¶РґСѓ С‚РµРјРїРµСЂР°С‚СѓСЂРѕР№ Рё РїСЂРµСЃС‚СѓРїРЅРѕСЃС‚СЊСЋ</p>
<pre class="r"><code>mod &lt;- lm(tc2009 ~ low, data = crime)
summary(mod)</code></pre>
<pre><code>## 
## Call:
## lm(formula = tc2009 ~ low, data = crime)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1134.36  -647.13    98.03   533.62  1344.30 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4256.86     233.44  18.236  &lt; 2e-16 ***
## low            21.65       5.33   4.061 0.000188 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 649.9 on 46 degrees of freedom
## Multiple R-squared:  0.2639, Adjusted R-squared:  0.2479 
## F-statistic: 16.49 on 1 and 46 DF,  p-value: 0.000188</code></pre>
<p>РљР°Рє РІС‹ РјРѕР¶РµС‚Рµ РІРёРґРµС‚СЊ, РјРѕРґРµР»СЊ РіРѕРІРѕСЂРёС‚ РЅР°Рј, С‡С‚Рѕ СЃСѓС‰РµСЃС‚РІСѓРµС‚ РґРѕСЃС‚РѕРІРµСЂРЅР°СЏ СЃРІСЏР·СЊ РјРµР¶РґСѓ РЅРёР·РєРёРјРё С‚РµРјРїРµСЂР°С‚СѓСЂР°РјРё Рё СѓСЂРѕРІРЅРµРј РїСЂРµСЃС‚СѓРїРЅРѕСЃС‚Рё. РЎ РґСЂСѓРіРѕР№ СЃС‚РѕСЂРѕРЅС‹, РѕС‡РµРЅСЊ СЃР»РѕР¶РЅРѕ СЃРµР±Рµ РїСЂРµРґСЃС‚Р°РІРёС‚СЊ РєР°РєРѕРІР° СЂРµР°Р»СЊРЅР°СЏ СЃРІСЏР·СЊ РјРµР¶РґСѓ РЅРёР·РєРёРјРё С‚РµРјРїРµСЂР°С‚СѓСЂР°РјРё Рё РїСЂРµСЃС‚СѓРїРЅРѕСЃС‚СЊСЋ.</p>
<p>Р­С‚РѕС‚ РїСЂРёРјРµСЂ РґРѕР»Р¶РµРЅ РІР°Рј РЅР°РїРѕРјРЅРёС‚СЊ Рѕ С‚РѕРј, С‡С‚Рѕ РЅРёР·РєРёРµ СЂ Р·РЅР°С‡РµРЅРёСЏ РЅРµ РѕР±СЏР·Р°С‚РµР»СЊРЅРѕ РѕР·РЅР°С‡Р°СЋС‚ РЅРµ РЅСѓР»РµРІСѓСЋ <span class="math inline">\(\beta\)</span>. Р РІ РґР°РЅРЅРѕРј СЃР»СѓС‡Р°Рµ Р±РѕР»РµРµ РІРµСЂРЅС‹Рј Р±СѓРґРµС‚ РїСЂРµРґРїРѕР»РѕР¶РёС‚СЊ, С‡С‚Рѕ РјС‹ РїРѕРґРѕР±СЂР°Р»Рё РЅРµРІРµСЂРЅСѓСЋ РјРѕРґРµР»СЊ РёР»Рё РЅР°С€Р° РІС‹Р±РѕСЂРєР° РєСЂР°Р№РЅРµ РЅРµСѓРґР°С‡РЅР°.</p>
<p>РљР°РєРёРµ Р¶Рµ СЃСѓС‰РµСЃС‚РІСѓСЋС‚ СЃРїРѕСЃРѕР±С‹ СЃРґРµР»Р°С‚СЊ РїСЂР°РІРёР»СЊРЅС‹Р№ РІС‹РІРѕРґ РёР· РїРѕР»СѓС‡РµРЅРЅС‹С… РјРѕРґРµР»РµР№? Р”Р°РІР°Р№С‚Рµ РїРѕСЃРјРѕС‚СЂРёРј РЅР° С‚Рѕ РєР°Рє СЂР°СЃРїСЂРµРґРµР»РµРЅС‹ РЅР°С€Рё РґР°РЅРЅС‹Рµ РїРѕСЃС‚СЂРѕРёРІ РіСЂР°С„РёРєРё, РґР»СЏ РґРІСѓС… С‚Р°Р±Р»РёС†, РјРѕРґРµР»Рё РґР°РЅРЅС‹С… РєРѕС‚РѕСЂС‹С… РјС‹ СЃС‚СЂРѕРёР»Рё.</p>
<pre class="r"><code>qplot(low, tc2009, data = crime)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<pre class="r"><code>qplot(height, earn, data = wages)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>РџРµСЂРІРѕРµ, С‡С‚Рѕ СЃСЂР°Р·Сѓ Р±СЂРѕСЃР°РµС‚СЃСЏ РІ РіР»Р°Р·Р°, СЌС‚Рѕ С‚Рѕ, С‡С‚Рѕ РґР»СЏ РїРµСЂРІРѕР№ РјРѕРґРµР»Рё Р»РёРЅРµР№РЅР°СЏ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ СЏРІР»СЏРµС‚СЃСЏ РІРїРѕР»РЅРµ РїРѕРґС…РѕРґСЏС‰РёРј РІР°СЂРёР°РЅС‚РѕРј. Рђ РІРѕС‚ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ РјРµР¶РґСѓ РїРµСЂРµРјРµРЅРЅС‹РјРё РІРѕ РІС‚РѕСЂРѕР№ С‚Р°Р±Р»РёС†Рµ РґР°РЅРЅС‹С… РІСЂСЏРґ Р»Рё СЏРІР»СЏРµС‚СЃСЏ Р»РёРЅРµР№РЅРѕР№.</p>
<p>Р’ РѕР±СЉРµРєС‚Рµ СЃРѕРґРµСЂР¶Р°С‰РµРј РјРѕРґРµР»СЊ РµСЃС‚СЊ РґР°РЅРЅС‹Рµ РґР»СЏ РїРѕСЃС‚СЂРѕРµРЅРёСЏ РіСЂР°С„РёРєРѕРІ РїРѕ РїСЂРѕРІРµСЂРєРµ СЂСЏРґР° РїСЂРµРґРїРѕР»РѕР¶РµРЅРёР№. Р’ РїРµСЂРІСѓСЋ РѕС‡РµСЂРµРґСЊ РјС‹ РґРѕР»Р¶РЅС‹ РїСЂРѕРІРµСЂРёС‚СЊ РїСЂРµРґРїРѕР»РѕР¶РµРЅРёРµ Рѕ РЅРѕСЂРјР°Р»СЊРЅРѕСЃС‚Рё СЂР°СЃРїСЂРµРґРµР»РµРЅРёСЏ РґР°РЅРЅС‹С….</p>
<pre class="r"><code>plot(mod)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-76-1.png" width="672" /><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-76-2.png" width="672" /><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-76-3.png" width="672" /><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-76-4.png" width="672" /></p>
<p>РџРµСЂРІС‹Р№ Рё С‚СЂРµС‚РёР№ РіСЂР°С„РёРєРё - Residuals vs Fitted Рё Scale-Location РїРѕРєР°Р·С‹РІР°СЋС‚ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ РѕС‚РєР»РѕРЅРµРЅРёР№ РѕС‚ РїСЂРµРґСЃРєР°Р·Р°РЅРЅС‹С… РјРѕРґРµР»СЊСЋ Р·РЅР°С‡РµРЅРёР№. Р•СЃР»Рё РЅР° РіСЂР°С„РёРєРµ РјРѕР¶РЅРѕ РїСЂРѕСЃР»РµРґРёС‚СЊ С…РѕС‚СЊ РєР°РєСѓСЋ-С‚Рѕ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ, С‚Рѕ СЌС‚Рѕ РѕР·РЅР°С‡Р°РµС‚, С‡С‚Рѕ РѕС‚РєР»РѕРЅРµРЅРёСЏ РЅРµ СЃР»СѓС‡Р°Р№РЅС‹ Рё СЃСѓС‰РµСЃС‚РІСѓРµС‚ РµС‰Рµ РєР°РєРѕР№-С‚Рѕ С„Р°РєС‚РѕСЂ РІРѕР·РґРµР№СЃС‚РІСѓСЋС‰РёР№ РЅР° РёР·СѓС‡Р°РµРјСѓСЋ Р·Р°РІРёСЃРёРјСѓСЋ РїРµСЂРµРјРµРЅРЅСѓСЋ, Р° Р·РЅР°С‡РёС‚ РјС‹ РґРѕР»Р¶РЅС‹ СѓСЃР»РѕР¶РЅРёС‚СЊ РЅР°С€Сѓ РјРѕРґРµР»СЊ.</p>
<p>Р’С‚РѕСЂРѕР№ РіСЂР°С„РёРє Normal Q-Q РїРѕРєР°Р·С‹РІР°РµС‚ СЂР°СЃРїСЂРµРґРµР»РµРЅРёРµ РѕС‚РєР»РѕРЅРµРЅРёР№ РїРѕ РєРІР°РЅС‚РёР»СЏРј. Р§РµРј Р±Р»РёР¶Рµ СЂР°СЃРїСЂРµРґРµР»РµРЅРёРµ Рє Р»РёРЅРµР№РЅРѕРјСѓ, С‚РµРј Р±РѕР»СЊС€Рµ С€Р°РЅСЃ С‚РѕРіРѕ, С‡С‚Рѕ РЅР°С€Рё РѕС‚РєР»РѕРЅРµРЅРёСЏ СЂР°СЃРїСЂРµРґРµР»РµРЅС‹ РЅРѕСЂРјР°Р»СЊРЅРѕ.</p>
<p>РЎ РїРѕРјРѕС‰СЊСЋ РїРѕСЃР»РµРґРЅРµРіРѕ РіСЂР°С„РёРєР° РІС‹ РјРѕР¶РµС‚Рµ РѕРїСЂРµРґРµР»РёСЊС‚ С‚РѕС‡РєРё, РєРѕС‚РѕСЂС‹Рµ СЃРёР»СЊРЅРѕ РѕС‚Р»РёС‡Р°СЋС‚СЃСЏ РѕС‚ РѕСЃС‚Р°Р»СЊРЅС‹С… Рё С‚РµРј СЃР°РјС‹Рј РїСЂРёРІРѕРґСЏС‚ Рє СЃРёР»СЊРЅС‹Рј РѕС‚РєР»РѕРЅРµРЅРёСЏРј РІ РјРѕРґРµР»Рё. РќР° РіСЂР°С„РёРєРµ РїСЂРµСЂС‹РІРЅРѕР№ Р»РёРЅРёРµР№ РїРѕРєР°Р·Р°РЅР° Р·РѕРЅР° РїСЂРё РІС‹С…РѕРґРµ С‚РѕС‡РµРє Р·Р° РїСЂРµРґРµР»С‹ РєРѕС‚РѕСЂРѕР№ СЃС‚РѕРёС‚ РѕР±СЂР°С‚РёС‚СЊ РЅР° РЅРёС… РїСЂРёСЃС‚Р°Р»СЊРЅРѕРµ РІРЅРёРјР°РЅРёРµ. Р•СЃР»Рё С‚Р°РєРёРµ С‚РѕС‡РєРё РёРјРµСЋС‚СЃСЏ, С‚Рѕ СЃР»РµРґСѓРµС‚ СЃРѕР·РґР°С‚СЊ Р°Р»СЊС‚РµСЂРЅР°С‚РёРІРЅС‹Р№ РЅР°Р±РѕСЂ РґР°РЅРЅС‹С…, Р±РµР· СЌС‚РёС… С‚РѕС‡РµРє, РїРѕСЃС‚СЂРѕРёС‚СЊ РЅРѕРІСѓСЋ РјРѕРґРµР»СЊ РґР»СЏ СѓР¶Рµ РґР»СЏ Р°Р»СЊС‚РµСЂРЅР°С‚РёРІРЅРѕРіРѕ РЅР°Р±РѕСЂР° РґР°РЅРЅС‹С… Рё РІС‹Р±СЂР°С‚СЊ Р»СѓС‡С€СѓСЋ.</p>
</div>
</div>
<div id="section-9" class="section level2">
<h2>РњРЅРѕР¶РµСЃС‚РІРµРЅРЅРѕРµ СЃСЂР°РІРЅРµРЅРёРµ</h2>
<p>Р”Рѕ СЌС‚РѕРіРѕ РјС‹ СЃС‚СЂРѕРёР»Рё РјРѕРґРµР»Рё, РёСЃРїРѕР»СЊР·СѓСЏ С‚РѕР»СЊРєРѕ С‡РёСЃР»РµРЅРЅС‹Рµ РїРµСЂРµРјРµРЅРЅС‹Рµ. Р”Р°РІР°Р№С‚Рµ РІСЃРїРѕРјРЅРёРј С‡С‚Рѕ Сѓ РЅР°СЃ РµСЃС‚СЊ РµС‰Рµ Рё РєР°С‚РµРіРѕСЂРёР°Р»СЊРЅС‹Рµ Р·РЅР°С‡РµРЅРёСЏ РЅР°Р·С‹РІР°РµРјС‹Рµ R С„Р°РєС‚РѕСЂР°РјРё Рё СЂР°СЃСЃРјРѕС‚СЂРёРј СЃР»РµРґСѓСЋС‰РёР№ РїСЂРёРјРµСЂ:</p>
<pre class="r"><code>rmod &lt;- lm(earn ~ race, data = wages)
coef(rmod)</code></pre>
<pre><code>##  (Intercept) racehispanic    raceother    racewhite 
##    28372.094    -2886.791     3905.320     4993.330</code></pre>
<p>РњС‹ РїРѕРїС‹С‚Р°Р»РёСЃСЊ РїРѕСЃС‚РѕСЂСЂРёС‚СЊ Р»РёРЅРµР№РЅСѓСЋ РјРѕРґРµР»СЊ Р·Р°РІРёСЃРёРјРѕСЃС‚Рё Р·Р°СЂР°Р±РѕС‚РєР° РѕС‚ СЂР°СЃС‹. Р•СЃР»Рё РјС‹ РїРѕСЃРјРѕС‚СЂРёРј РЅР° РєРѕСЌС„С„РёС†РёРµРЅС‚С‹, С‚Рѕ СЂРµР·СѓР»СЊС‚Р°С‚ Р±СѓРґРµС‚ РґРѕРІРѕР»СЊРЅРѕ РЅРµРѕР¶РёРґР°РЅРЅС‹Р№. Р’Рѕ РїРµСЂРІС‹С…, Р±С‹Р»Рё РїРѕСЃС‡РёС‚Р°РЅС‹ РєРѕСЌС„С„РёС†РёРµРЅС‚С‹ РґР»СЏ РєР°Р¶РґРѕРіРѕ СѓСЂРѕРІРЅСЏ С„Р°РєС‚РѕСЂР°, Р° РІРѕ РІС‚РѕСЂС‹С…, Сѓ РЅР°СЃ РїСЂРµРґСЃС‚Р°РІР»РµРЅС‹ РЅРµ РІСЃРµ СѓСЂРѕРІРЅРё, РЅР°РїСЂРјРµСЂ Сѓ РЅР°СЃ РЅРµС‚ РєРѕСЌС„С„РёС†РёРµРЅС‚Р° РґР»СЏ СѓСЂРѕРІРЅСЏ “black”.</p>
<p>Р”РµР»Рѕ РІ С‚РѕРј, С‡С‚Рѕ РѕРґРёРЅ РёР· СѓСЂРѕРІРЅРµР№ РїРµСЂРµРјРµРЅРЅРѕР№ РІС‹Р±РёСЂР°РµС‚СЃСЏ РІ РєР°С‡РµСЃС‚РІРµ Р±Р°Р·РѕРІРѕРіРѕ. РљР°Р¶РґС‹Р№ РїРѕСЃР»РµРґСѓСЋС‰РёР№ СѓСЂРѕРІРµРЅСЊ РїРѕР»СѓС‡Р°РµС‚ РЅРµРєРёР№ РЅРѕРјРµСЂ РІ РіСЂР°РґР°С†РёРё Рё РґР»СЏ РЅРµРіРѕ СЂР°СЃСЃРёС‚С‹РІР°РµС‚СЃСЏ РѕС‚РґРµР»СЊРЅС‹Р№ РєРѕСЌС„С„РёС†РёРµРЅС‚, РєРѕС‚РѕСЂС‹Рµ РїРѕРєР°Р·С‹РІР°РµС‚ РЅР° СЃРєРѕР»СЊРєРѕ РµРіРѕ РєРѕСЌС„С„РёС†РёРµРЅС‚ РѕС‚Р»РёС‡Р°РµС‚СЃСЏ РѕС‚ Р±Р°Р·РѕРІРѕРіРѕ.</p>
<p>Рў.Рє. РјС‹ РЅРµ СѓРІРёРґРµР»Рё РєРѕСЌС„С„РёС†РёРµРЅС‚Р° РґР»СЏ С‡РµСЂРЅРѕРіРѕ РЅР°СЃРµР»РµРЅРёСЏ, Р·РЅР°С‡РёС‚ РѕРЅ Рё СЏРІР»СЏРµС‚СЃСЏ Р±Р°Р·РѕРІС‹Рј, С‚.Рµ. 28372.09. Р”Р»СЏ РёСЃРїР°РЅРѕСЏР·С‹С‡РЅРѕРіРѕ РЅР°СЃРµР»РµРЅРёСЏ РёС‚РѕРіРѕРІС‹Р№ РєРѕСЌС„С„РёС†РёРµРЅС‚ СЃРѕСЃС‚Р°РІРёС‚ 28372.09 + -2886.79 = 25485.30. Р РґР»СЏ Р±РµР»РѕРіРѕ РЅР°СЃРµР»РµРЅРёСЏ 28372.09 + 4993.33 = 33365.42</p>
<p>Рў.Рє. РёС‚РѕРіРѕРІС‹Р№ РїРѕРєР°Р·Р°С‚РµР»СЊ Сѓ РёСЃРїР°РЅРѕСЏР·С‹С‡РЅРѕРіРѕ РЅР°СЃРµР»РµРЅРёСЏ СЃР°РјС‹Р№ РЅРёР·РєРёР№ Р±С‹Р»Рѕ Р±С‹ Р»РѕРіРёС‡РЅРѕ СЃРґРµР»Р°С‚СЊ РµРіРѕ Р±Р°Р·РѕРІС‹Рј СѓСЂРѕРІРЅРµРј. Р’С‹ РјРѕР¶РµС‚Рµ СЌС‚Рѕ СЃРґРµР»Р°С‚СЊ РїРѕРјРµРЅСЏРІ РїРѕСЂСЏРґРѕРє СѓСЂРѕРІРЅРµР№ Сѓ С„Р°РєС‚РѕСЂР°:</p>
<pre class="r"><code>wages$race &lt;- factor(wages$race, 
  levels = c(&quot;hispanic&quot;, &quot;white&quot;, &quot;black&quot;, &quot;other&quot;))
rmod2 &lt;- lm(earn ~ race, data = wages)
coef(rmod2)</code></pre>
<pre><code>## (Intercept)   racewhite   raceblack   raceother 
##   25485.303    7880.121    2886.791    6792.111</code></pre>
<p>Р›РµРіРєРѕ Р·Р°РјРµС‚РёС‚СЊ, С‡С‚Рѕ РЅРµ СЃРјРѕС‚СЂСЏ РЅР° С‚Рѕ, С‡С‚Рѕ Р·РЅР°С‡РµРЅРёСЏ РєРѕСЌС„С„РёС†РёРµРЅС‚РѕРІ РїРѕРјРµРЅСЏР»РёСЃСЊ, РёС… СЂРµР·СѓР»СЊС‚РёСЂСѓСЋС‰РёРµ Р·РЅР°С‡РµРЅРёСЏ РѕСЃС‚Р°Р»РёСЃСЊ РїСЂРµР¶РЅРёРјРё.</p>
<div id="anova" class="section level4">
<h4>ANOVA</h4>
<p>Р”Р°РІР°Р№С‚Рµ РѕРїСЏС‚СЊ РѕР±СЂР°С‚РёРјСЃСЏ Рє РІР°С€РёРј Р·РЅР°РЅРёСЏРј РїРѕ СЃС‚Р°С‚РёСЃС‚РёРєРµ Рё Р·Р°РґСѓРјР°РµСЃСЏ, Р° РЅР° С‡С‚Рѕ Р¶Рµ РїРѕС…РѕР¶ СЂРµРіСЂРµСЃСЃРёРѕРЅС‹Р№ Р°РЅР°Р»РёР· РґР»СЏ РєР°С‚РµРіРѕСЂРёР°Р»СЊРЅС‹С… РїРµСЂРµРјРµРЅРЅС‹С…? РџРѕ СЃСѓС‚Рё РІ РЅРµРј РјС‹ РїС‹С‚Р°РµРјСЃСЏ СЃСЂР°РІРЅРёС‚СЊ СЂР°Р·Р»РёС‡РёСЏ РјРµР¶РґСѓ Р±РѕР»СЊС€РѕР№ РѕР±СЉРµРґРёРЅСЏСЋС‰РµР№ РіСЂСѓРїРїРѕР№ Рё РµРµ РѕС‚РґРµР»СЊРЅС‹РјРё РїРѕРґРіСЂСѓРїРїР°РјРё, С‡С‚Рѕ РѕС‡РµРЅСЊ РїРѕС…РѕР¶Рµ РЅР° РґРёСЃРїРµСЂСЃРёРѕРЅРЅС‹Р№ Р°РЅР°Р»РёР· (ANOVA - Analysis of Variance). РќР° СЃР°РјРѕРј РґРµР»Рµ СЌС‚Рѕ С‚Р°Рє Рё РјС‹ РјРѕР¶РµРј РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РґР°РЅРЅС‹Рµ РґРёСЃРїРµСЂРёСЃРѕРЅРЅРѕРіРѕ Р°РЅР°Р»РёР·Р°, РїСЂРёРјРµРЅРёРІ РєРѕРјР°РЅРґСѓ anova() РЅР° РЅР°С€Сѓ РјРѕРґРµР»СЊ.</p>
<pre class="r"><code>anova(rmod2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: earn
##             Df     Sum Sq    Mean Sq F value  Pr(&gt;F)  
## race         3 6.7924e+09 2264121503  2.3241 0.07328 .
## Residuals 1375 1.3395e+12  974196170                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>РџРѕРјРёРјРѕ РґРёСЃРїРµСЂСЃРёРѕРЅРЅРѕРіРѕ Р°РЅР°Р»РёР·Р° СЃСѓС‰РµСЃС‚РІСѓРµС‚ РјРЅРѕР¶РµСЃС‚РІРѕ РїРѕРґРѕР±РЅС‹С… РµРјСѓ С‚РµСЃС‚РѕРІ, РєРѕС‚РѕСЂС‹РјРё РІС‹ С‚РѕР¶Рµ РјРѕР¶РµС‚Рµ РІРѕСЃРїРѕР»СЊР·РѕРІР°С‚СЊСЃСЏ:</p>
<table>
<colgroup>
<col width="28%" />
<col width="51%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th>Р¤СѓРЅРєС†РёСЏ</th>
<th>РўРµСЃС‚</th>
<th>РЎС‚Р°С‚РёСЃС‚РёРєР°</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>lm</td>
<td>ANOVA</td>
<td>СЃСЂРµРґРЅРµРµ</td>
</tr>
<tr class="even">
<td>aov</td>
<td>ANOVA</td>
<td>СЃСЂРµРґРЅРµРµ</td>
</tr>
<tr class="odd">
<td>anova</td>
<td>ANOVA</td>
<td>СЃСЂРµРґРЅРµРµ</td>
</tr>
<tr class="even">
<td>oneway.test</td>
<td>ANOVA РґР»СЏ СЂР°Р·Р»РёС‡РЅС‹С… РґРёСЃРїРµСЂСЃРёР№</td>
<td>СЃСЂРµРґРЅРµРµ</td>
</tr>
<tr class="odd">
<td>pairwise.t.test</td>
<td>t С‚РµСЃС‚ РјРЅРѕР¶РµС‚СЃРІР° РіСЂСѓРїРї</td>
<td>СЃСЂРµРґРЅРµРµ</td>
</tr>
<tr class="even">
<td>kruskal.test</td>
<td>Kruskal Wallis Rank Sum</td>
<td>СЃСѓРјРјР°</td>
</tr>
<tr class="odd">
<td>friedman.test</td>
<td>Friedman Rank Sum</td>
<td>СЃСѓРјРјР°</td>
</tr>
<tr class="even">
<td>fligner.test</td>
<td>Fligner-Killeen</td>
<td>РґРёСЃРїРµСЂСЃРёСЏ</td>
</tr>
<tr class="odd">
<td>bartlett.test</td>
<td>Bartlett test</td>
<td>РґРёСЃРїРµСЂСЃРёСЏ</td>
</tr>
</tbody>
</table>
<p>Р”Р°РІР°Р№С‚Рµ РїРѕСЃРјРѕС‚СЂРёРј Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ Р·Р°СЂР°Р±РѕС‚РєР° РѕС‚ РїРѕР»Р°. Р СЃСѓС‰РµСЃС‚РІСѓРµС‚ Р»Рё СЃС‚Р°С‚РёСЃС‚РёС‡РµСЃРєРё РґРѕСЃС‚РѕРІРµСЂРЅР°СЏ СЂР°Р·РЅРёС†Р° РјРµР¶РґСѓ Р·Р°СЂРїР»Р°С‚Р°РјРё РјСѓР¶С‡Рё Рё Р¶РµРЅС‰РёРЅ</p>
<pre class="r"><code>smod &lt;- lm(earn ~ sex, data = wages)
coef(smod)</code></pre>
<pre><code>## (Intercept)     sexmale 
##    24245.65    21747.48</code></pre>
<pre class="r"><code>wages$sex &lt;- factor(wages$sex, 
  levels = c(&quot;male&quot;, &quot;female&quot;))
smod &lt;- lm(earn ~ sex, data = wages)
coef(smod)</code></pre>
<pre><code>## (Intercept)   sexfemale 
##    45993.13   -21747.48</code></pre>
<p>РС‚Р°Рє, РµСЃР»Рё РјС‹ РІРѕР·СЊРјРµРј РјСѓР¶СЃРєСѓСЋ Р·Р°СЂРїР»Р°С‚Сѓ РІ РєР°С‡РµСЃС‚РІРµ Р±Р°Р·РѕРІРѕР№, РѕРЅР° СЃРѕСЃС‚Р°РІРёС‚ 45993, Р° Р¶РµРЅСЃРєР°СЏ Р±СѓРґРµС‚ РјРµРЅСЊС€Рµ РµРµ РЅР° 21747. Р Р°Р·РЅРёС†Р° РѕРєР°Р·Р°Р»Р°СЃСЊ РєРѕР»РѕСЃР°Р»СЊРЅРѕР№, РїРѕСЌС‚РѕРјСѓ РґР°РІР°Р№С‚Рµ РїСЂРѕРІРµСЂРёРј РЅР° СЃРєРѕР»СЊРєРѕ СЌС‚Рё РґР°РЅРЅС‹Рµ СЃС‚Р°РёСЃС‚РёС‡РµСЃРєРё РґРѕСЃС‚РѕРІРµСЂРЅС‹:</p>
<pre class="r"><code>anova(smod)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: earn
##             Df     Sum Sq    Mean Sq F value    Pr(&gt;F)    
## sex          1 1.5320e+11 1.5320e+11  176.81 &lt; 2.2e-16 ***
## Residuals 1377 1.1931e+12 8.6646e+08                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Pr(&gt;F) &lt; 2.2e-16 *** РіРѕРІРѕСЂРёС‚ РЅР°Рј Рѕ С‚РѕРј, С‡С‚Рѕ РІРµСЂРѕСЏС‚РЅРѕСЃС‚СЊ РЅСѓР»РµРІРѕР№ РіРёРїРѕС‚РµР·С‹ СЂР°РІРЅР° РЅСѓР»СЋ, Р° Р·РЅР°С‡РёС‚ СЂР°СЃСЃС‡РёС‚Р°РЅРЅР°СЏ РЅР°С€РµР№ РјРѕРґРµР»СЊСЋ РѕРіСЂРѕРјРЅР°СЏ СЂР°Р·РЅРёС†Р° СЏРІР»СЏРµС‚СЃСЏ СЃС‚Р°С‚РёСЃС‚РёС‡РµСЃРєРё РґРѕСЃС‚РѕРІРµСЂРЅРѕР№. Р“РёСЃС‚РѕРіСЂР°РјРјР° Р·Р°СЂРїР»Р°С‚ РµС‰Рµ СЂР°Р· РїРѕРґС‚РІРµСЂР¶РґР°РµС‚ РЅР°Рј СЌС‚Рѕ:</p>
<pre class="r"><code>qplot(earn, data = wages, geom = &quot;density&quot;, color = sex) + theme_bw()</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>РџРѕСЃС‚СЂРѕРёРІ Р°РЅР°Р»РѕРіРёС‡РЅС‹Р№ РіСЂР°С„РёРє РґР»СЏ СЂР°Р·Р»РёС‡РЅС‹С… СЂР°СЃ РјС‹ РјРѕР¶РµРј Р·Р°РјРµС‚РёС‚СЊ, С‡С‚Рѕ СЂР°Р·РЅРёС†Р° РјРµР¶РґСѓ СЂР°СЃСЃР°РјРё РЅРµ РЅР° СЃС‚РѕР»СЊРєРѕ РїСЂРёРЅС†РёРїРёР°Р»СЊРЅР°СЏ:</p>
<pre class="r"><code>qplot(earn, data = wages, geom = &quot;density&quot;, color = race) + theme_bw()</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
</div>
</div>
<div id="section-10" class="section level2">
<h2>РћС†РµРЅРєР° С„СѓРЅРєС†РёР№ РјРЅРѕРіРёС… РїРµСЂРµРјРµРЅРЅС‹С…</h2>
<p>Р”Рѕ СЌС‚РѕРіРѕ РјС‹ СЂР°СЃСЃРјР°С‚СЂРёРІР°Р»Рё Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ РѕРґРЅРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ С‚РѕР»СЊРєРѕ РѕС‚ РѕРґРЅРѕР№ РґСЂСѓРіРѕР№. РњРµР¶ С‚РµРј, R РїРѕР·РІРѕР»СЏРµС‚ РёСЃРєР°С‚СЊ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ РѕС‚ РЅРµРѕРіСЂР°РЅРёС‡РµРЅРЅРѕРіРѕ РєРѕР»РёС‡РµСЃС‚РІР° РїРµСЂРµРјРµРЅРЅС‹С…. РќР°РїСЂРјРµСЂ РїРѕСЃС‚СЂРѕРёРј РјРѕРґРµР»СЊ Р·Р°РІРёСЃРёРјРѕСЃС‚Рё Р·Р°СЂР°Р±РѕС‚РєР° РѕС‚ СЂРѕСЃС‚Р°</p>
<pre class="r"><code>m1 &lt;- lm(earn ~ height, data = wages)
coef(m1)</code></pre>
<pre><code>## (Intercept)      height 
## -126523.359    2387.196</code></pre>
<p>Рђ РІРѕС‚ СѓР¶Рµ СЃР»РµРґСѓСЋС‰РёР№ РєРѕРґ РїРѕР·РІРѕР»СЏРµС‚ РЅР°Рј РѕРїРёСЃР°С‚СЊ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ Р·Р°СЂР°Р±РѕС‚РєР° РѕС‚ РІРѕР·СЂР°СЃС‚Р° Рё РїРѕР»Р°.</p>
<pre class="r"><code>m2 &lt;- lm(earn ~ height + sex, data = wages)
coef(m2)</code></pre>
<pre><code>## (Intercept)      height   sexfemale 
##  -15605.703     879.424  -16874.158</code></pre>
<p>Р’С‚РѕСЂРѕР№ РєРѕСЌС„С„РёС†РёРµРЅС‚ РѕР¶РµС‚ Р±С‹С‚СЊ РёРЅС‚РµСЂРїСЂРµС‚РёСЂРѕРІР°РЅ РєР°Рє СЌС„С„РµРєС‚ РѕС‚ РЅР°Р»РёС‡РёСЏ Р¶РµРЅСЃРєРѕРіРѕ РїРѕР»Р° …РєРѕРіРґР° СЂРѕСЃС‚ СЂР°СЃСЃРјР°С‚СЂРёРІР°РµС‚СЃСЏ РЅРµРёР·РјРµРЅРЅС‹Рј. РџРµСЂРІС‹Р№ РєРѕСЌС„С„РёС†РёРµРЅС‚ РјРѕР¶РµС‚ Р±С‹С‚СЊ РёРЅС‚РµСЂРїСЂРµС‚РёСЂРѕРІР°РЅ РєР°Рє РёР·РјРµРЅРµРЅРёСЏ Р·Р°СЂР°Р±РѕС‚РєР° РІ Р·Р°РІРёСЃРёРјРѕСЃС‚Рё РѕС‚ СЂРѕСЃС‚Р° …РїСЂРё СѓСЃР»РѕРІРёРё, С‡С‚Рѕ РїРѕР» РЅРµРёР·РјРµРЅРµРЅ.</p>
<p>РЎР»РµРґСѓСЋС‰РёР№ РіСЂР°С„РёРє РґРµРјРѕРЅСЃС‚СЂРёСЂСѓРµС‚ РґРІРµ РјРѕРґРµР»Рё - Р·Р°РІРёСЃРёРјРѕСЃС‚Рё Р·Р°СЂР°Р±РѕС‚РєР° РѕС‚ СЂРѕСЃС‚Р° РґР»СЏ РјСѓР¶С‡РёРЅ Рё Р¶РµРЅС‰РёРЅ</p>
<pre class="r"><code>qplot(height, earn, data = wages, alpha = I(1/10), color = sex) + theme_bw() + geom_line(aes(y = predict(m2)))</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<p>РўР°РєРёРј РѕР±СЂР°Р·РѕРј РґРѕР±Р°РІР»РµРЅРёРµ РґРѕРїРѕР»РЅРёС‚РµР»СЊРЅРѕР№ РїРµСЂРµРјРµРЅРЅР№Рѕ РїРѕ СЃСѓС‚Рё РїСЂРёРІРµР»Рѕ Рє СЂР°Р·Р±РёРµРЅРёСЋ РЅР°С€РµР№ РјРѕРґРµР»Рё.</p>
<p>РћР±СЂР°С‚РёРјСЃСЏ Рє РёР·РІРµСЃС‚РЅРѕРјСѓ РІР°Рј РЅР°Р±РѕСЂСѓ РґР°РЅРЅС‹Р№ diamond Рё СЂР°СЃСЃРјРѕС‚СЂРёРј РІР»РёСЏРЅРёРµ С‚РёРїР° РѕРіСЂР°РЅРєРё (cut) Рё РєРѕР»РёС‡РµСЃС‚РІР° РєР°СЂР°С‚ РІ Р±СЂРёР»Р»РёР°РЅС‚Рµ РЅР° РµРіРѕ СЃС‚РѕРёРјРѕСЃС‚СЊ:</p>
<pre class="r"><code>qplot(price, data = diamonds, color = cut, geom = &quot;density&quot;)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p>РџРѕСЃС‚СЂРѕРёРј РґРІРµ РјРѕРґРµР»Рё, СЃ СѓС‡РµС‚РѕРј Рё Р±РµР· СѓС‡РµС‚Р° РІРµСЃР° Р±СЂРёР»Р»РёР°РЅС‚Р° РІ РєР°СЂР°С‚Р°С…:</p>
<pre class="r"><code>diamonds$cut &lt;- as.character(diamonds$cut)

d1 &lt;- lm(price ~ cut, data = diamonds)
coef(d1)</code></pre>
<pre><code>##  (Intercept)      cutGood     cutIdeal   cutPremium cutVery Good 
##    4358.7578    -429.8933    -901.2158     225.4999    -376.9979</code></pre>
<pre class="r"><code>d2 &lt;- lm(price ~ cut + carat, data = diamonds)
coef(d2)</code></pre>
<pre><code>##  (Intercept)      cutGood     cutIdeal   cutPremium cutVery Good 
##    -3875.470     1120.332     1800.924     1439.077     1510.135 
##        carat 
##     7871.082</code></pre>
<p>Р•СЃР»Рё РјС‹ РїРѕСЃРјРѕС‚СЂРёРј РЅР° РґР°РЅРЅС‹Рµ РјРѕРґРµР»Рё РЅРµ СѓС‡РёС‚С‹РІР°РІС€РµР№ РІРµСЃ Р±СЂРёР»Р»РёР°РЅС‚Р°, РјС‹ СѓРІРёРґРёРј СЃС‚СЂР°РЅРЅСѓСЋ РєР°СЂС‚РёРЅСѓ, РєРѕРіРґР° СЃС‚РѕРёРјРѕСЃС‚СЊ Р±СЂРёР»Р»РёР°РЅС‚Р° СЃ РёРґРµР°Р»СЊРЅРѕР№ Р°РіСЂР°РЅРєРѕР№ СЃРёР»СЊРЅРѕ РјРµРЅСЊС€Рµ, С‡РµРј Сѓ Р±СЂРёР»Р»РёР°РЅС‚Р° СЃ С…РѕСЂРѕС€РµР№ Рё РѕС‡РµРЅСЊ С…РѕСЂРѕС€РµР№ РѕРіСЂР°РЅРєРѕР№. РќРѕ РµСЃР»Рё РІ РјРѕРґРµР»Рё СѓС‡РµСЃС‚СЊ РІРµСЃ (Р° Р·РЅР°С‡РёС‚ Рё СЂР°Р·РјРµСЂ) Р±СЂРёР»Р»РёР°РЅС‚Р°, С‚Рѕ РІСЃРµ СЃС‚Р°РЅРѕРІРёС‚СЃСЏ РЅР° СЃРІРѕРё РјРµСЃС‚Р°. Р Р±СЂРёР»Р»РёР°РЅС‚С‹ СЃ РёРґРµР°Р»СЊРЅРѕР№ Р°РіСЂР°РЅРєРѕР№ РІ СЌС‚РѕР№ РјРѕРґРµР»Рё СЃС‚РѕСЏС‚ РґРѕСЂРѕР¶Рµ, РЅРѕ СЃ СѓС‡РµС‚РѕРј РёС… “РєР°СЂР°С‚РЅРѕСЃС‚Рё”.</p>
<p>РћРїРёСЃР°РЅРЅРѕРµ РІС‹С€Рµ РїСЂРµРєСЂР°СЃРЅРѕ РІРёРґРЅРѕ РЅР° СЃР»РµРґСѓСЋС‰РµРј РіСЂР°С„РёРєРµ:</p>
<pre class="r"><code>qplot(carat, predict(d2), data = diamonds, color = cut, geom = &quot;line&quot;)</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
<div id="section-11" class="section level4">
<h4>РџРѕРґРѕР±РЅС‹Р№ СЌС„С„РµРєС‚ РѕС‚ РІРІРµРґРµРЅРёСЏ РґРѕРїРѕР»РЅРёС‚РµР»СЊРЅРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ С€РёСЂРѕРєРѕ РёР·РІРµСЃС‚РµРЅ Рё РґР°Р¶Рµ РёРјРµРµС‚ СЃРѕР±СЃС‚РІРµРЅРЅРѕРµ РёРјСЏ - РїР°СЂР°РґРѕРєСЃ РЎРёРјРїСЃРѕРЅР°</h4>
<p>РЎСѓС‚СЊ РµРіРѕ СЃРѕСЃС‚РѕРёС‚ РІ С‚РѕРј, С‡С‚Рѕ СЃРІСЏР·СЊ РјРµР¶РґСѓ РґРІСѓРјСЏ РїРµСЂРµРјРµРЅРЅС‹РјРё РјРѕР¶РµС‚ РёР·РјРµРЅРёС‚СЊСЃСЏ, РµСЃР»Рё СѓС‡РµСЃС‚СЊ, С‚СЂРµС‚СЊСЋ, СЃРІСЏР·Р°РЅРЅСѓСЋ СЃ РЅРёРјРё РїРµСЂРµРјРµРЅРЅСѓСЋ.</p>
</div>
<div id="section-12" class="section level4">
<h4>Рў.Рє. СЌС‚Р° РїСЂРѕР±Р»РµРјР° С…РѕСЂРѕС€Рѕ РёР·РІРµСЃС‚РЅР°, Сѓ РЅРµРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚ Рё СЃС‚Р°РЅРґР°СЂС‚РЅРѕРµ СЂРµС€РµРЅРёРµ:</h4>
<p>РњРѕРґРµР»РёСЂСѓР№С‚Рµ РєР°Р¶РґС‹Р№ РёСЃС‚РѕС‡РЅРёРє РёР·РјРµРЅРµРЅРёР№ РІ СЃРёСЃС‚РµРјРµ РѕРґРЅРѕРІСЂРµРјРµРЅРЅРѕ</p>
<p>РЎРѕР·РґР°РґРёРј РЅРѕРІСѓСЋ РјРѕРґРµР»СЊ, РєРѕС‚РѕСЂР°СЏ РїСЂРµРґСЃРєР°Р·С‹РІР°РµС‚ Р·Р°СЂР°Р±РѕС‚РѕРє РІ Р·Р°РІРёСЃРёРјРѕСЃС‚Рё РѕС‚ СЂРѕСЃС‚Р°, РїРѕР»Р°, СЂР°СЃС‹, РѕР±СЂР°Р·РѕРІР°РЅРёСЏ Рё РІРѕР·СЂР°СЃС‚Р°.Р РїРѕРїС‹С‚Р°РµРјСЃСЏ РѕС‚РІРµС‚РёС‚СЊ РЅР° РІРѕРїСЂРѕСЃ СЃСѓС‰РµСЃС‚РІСѓРµС‚ Р»Рё СЃРІСЏР·СЊ РјРµР¶РґСѓ РІС‹СЃРѕС‚РѕР№ Рё Р·Р°СЂР°Р±РѕС‚РєРѕРј? Рђ РјРµР¶РґСѓ РїРѕР»РѕРј Рё Р·Р°СЂР°Р±РѕС‚РєРѕРј?</p>
<pre class="r"><code>m3 &lt;- lm(earn ~ height + sex + race + ed + age, data = wages)
coef(m3)</code></pre>
<pre><code>## (Intercept)      height   sexfemale   racewhite   raceblack   raceother 
## -74354.1693    632.7391 -17552.5441   4592.7865   2086.0663   1708.3196 
##          ed         age 
##   4382.0853    287.4744</code></pre>
<p>РЎРёРјРІРѕР» . РёСЃРїРѕР»СЊР·СѓРµС‚СЃСЏ РІ С„РѕСЂРјСѓР»Рµ, РєР°Рє РѕР±РѕР·РЅР°С‡РµРЅРёРµ РІСЃРµС… РѕСЃС‚Р°Р»СЊРЅС‹С… РїРµСЂРµРјРµРЅРЅС‹С…. Рў.Рµ. РјС‹ РјРѕР¶РµРј РѕРїРёСЃР°С‚СЊ С‚Р°РєСѓСЋ Р¶Рµ РјРѕРґРµР»СЊ СЃ РїРѕРјРѕС‰СЊСЋ РєРѕРґР°:</p>
<pre class="r"><code>lm(earn ~ height + sex + race + ed + age, data = wages)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height + sex + race + ed + age, data = wages)
## 
## Coefficients:
## (Intercept)       height    sexfemale    racewhite    raceblack  
##    -74354.2        632.7     -17552.5       4592.8       2086.1  
##   raceother           ed          age  
##      1708.3       4382.1        287.5</code></pre>
<pre class="r"><code>lm(earn ~ ., data = wages)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ ., data = wages)
## 
## Coefficients:
## (Intercept)       height    sexfemale    racewhite    raceblack  
##    -74354.2        632.7     -17552.5       4592.8       2086.1  
##   raceother           ed          age  
##      1708.3       4382.1        287.5</code></pre>
<p>РџРѕРґРѕР±РЅСѓСЋ Р·Р°РїРёСЃСЊ, СЃ РёСЃРїРѕР»СЊР·РѕРІР°РЅРёРµРј Р·РЅР°РєР° . РјРѕР¶РЅРѕ РјРѕРґРёС„РёС†РёСЂРѕРІР°С‚СЊ РѕС‚РЅРёРјР°СЏ РѕС‚ РЅРµРµ РѕС‚РґРµР»СЊРЅС‹Рµ РїРµСЂРµРјРµРЅРЅС‹Рµ:</p>
<pre class="r"><code>lm(earn ~ height + sex + race + ed, data = wages)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height + sex + race + ed, data = wages)
## 
## Coefficients:
## (Intercept)       height    sexfemale    racewhite    raceblack  
##    -46648.9        440.6     -18036.5       6128.5       2915.6  
##   raceother           ed  
##      3379.3       4159.8</code></pre>
<pre class="r"><code>lm(earn ~ . - age, data = wages)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ . - age, data = wages)
## 
## Coefficients:
## (Intercept)       height    sexfemale    racewhite    raceblack  
##    -46648.9        440.6     -18036.5       6128.5       2915.6  
##   raceother           ed  
##      3379.3       4159.8</code></pre>
</div>
</div>
</div>
<div id="section-13" class="section level1">
<h1>РЈСЃР»РѕРІРёСЏ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёСЏ РїРµСЂРµРјРµРЅРЅС‹С…</h1>
<p>Р”Рѕ СЌС‚РѕРіРѕ РјС‹ РёСЃС…РѕРґРёР»Рё РёР· С‚РѕРіРѕ, С‡С‚Рѕ РєР°Р¶РґР°СЏ РёР· РЅРµР·Р°РІРёСЃРёРјС‹С… РїРµСЂРµРјРµРЅРЅС‹С… РЅРµ РІР»РёСЏРµС‚ РЅР° РґСЂСѓРіСѓСЋ. Р§С‚Рѕ, РЅР°РїСЂРёРјРµСЂ РѕС‡РµРІРёРґРЅРѕ РЅРµ РІРµСЂРЅРѕ РґР»СЏ РїРѕР»Р° Рё СЂРѕСЃС‚Р°, С‚.Рє. СЃСЂРµРґРЅРёР№ СЂРѕСЃС‚ Р¶РµРЅС‰РёРЅ РјРµРЅСЊС€Рµ. Р”Р»СЏ С‚РѕРіРѕ, С‡С‚РѕР±С‹ R СѓС‡РёС‚С‹РІР°Р» РїСЂРё РјРѕРґРµР»РёСЂРѕРІР°РЅРёРё РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёРµ РЅРµР·Р°РІРёСЃРёРјС‹С… РїРµСЂРµРјРµРЅРЅС‹С…, РјС‹ РґРѕР»Р¶РЅС‹ Р±СѓРґРµРј РґРѕР±Р°РІРёС‚СЊ Рє С„РѕСЂРјСѓР»Рµ РµС‰Рµ РѕРґРЅСѓ РїРµСЂРµРјРµРЅРЅСѓСЋ, РєРѕС‚РѕСЂР°СЏ РѕРїРёСЃС‹РІР°РµС‚ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёРµ СЌС‚РёС… РїРµСЂРµРјРµРЅРЅС‹С… РјРµР¶РґСѓ СЃРѕР±РѕР№. РўР°Рє РґР»СЏ РІС‹С€РµСѓРїРѕРјСЏРЅСѓС‚С‹С… СЂРѕСЃС‚Р° Рё РїРѕР»Р° РёС‚РѕРіРѕРІР°СЏ С„РѕСЂРјСѓР»Р° РјРѕРґРµР»Рё Р±СѓРґРµС‚ РІС‹РіР»СЏРґРµС‚СЊ С‚Р°Рє:</p>
<pre class="r"><code>m4 &lt;- lm(earn ~ height + sex + height:sex,   data = wages)
coef(m4)</code></pre>
<pre><code>##      (Intercept)           height        sexfemale height:sexfemale 
##      -42677.4003        1265.9167       30510.4336        -701.4065</code></pre>
<p>Р§С‚Рѕ РѕР·РЅР°С‡Р°СЋС‚ РїРѕР»СѓС‡РµРЅРЅС‹Рµ РєРѕСЌС„С„РёС†РёРµРЅС‚С‹? Р”Р»СЏ РјСѓР¶С‡РёРЅ СѓРІРµР»РёС‡РµРЅРёРµ СЂРѕСЃС‚Р° РЅР° 1 РґСЋР№Рј РїСЂРёРІРµРґРµС‚ Рє СѓРІРµР»РёС‡РµРЅРёСЋ Р·Р°СЂР°Р±РѕС‚РєР° РЅР° 1265.92. Р”Р»СЏ Р¶РµРЅС‰РёРЅ СѓРІРµР»РёС‡РµРЅРёРµ СЂРѕСЃС‚Р° РЅР° 1 РґСЋР№Рј РїСЂРёРІРµРґРµС‚Рµ Рє СѓРІРµР»РёС‡РµРЅРёСЋ Р·Р°СЂР°Р±РѕС‚РєР° РЅР° 1265.92 + (-701.41) = 564.51.</p>
<p>Р•СЃР»Рё РјС‹ РїРѕСЃС‚СЂРѕРёРј РіСЂР°С„РёРєРё РґРІСѓС… РїСЂРµРґСЃРєР°Р·Р°РЅРёР№ РґРІСѓС… РјРѕРґРµР»РµР№, С‚Рѕ СЃРјРѕР¶РµРј Р·Р°РјРµС‚РёС‚СЊ, С‡С‚Рѕ Сѓ РјРѕРґРµР»Рё СЃ СѓС‡РµС‚РѕРј РІР·Р°РјРёРѕРґРµР№СЃС‚РІРёСЏ РїРµСЂРµРјРµРЅРЅС‹С… РїСЂСЏРјС‹Рµ РґР»СЏ РјСѓР¶С‡РёРЅ Рё Р¶РµРЅС‰РёРЅ РїРµСЂРµСЃС‚Р°Р»Рё Р±С‹С‚СЊ РїР°СЂР°Р»Р»РµР»СЊРЅС‹. Р§С‚Рѕ РѕР·РЅР°С‡Р°РµС‚, С‡С‚РѕРёР·РјРµРЅРµРЅРёРµ РІ СЂРѕСЃС‚Рµ Сѓ РјСѓР¶С‡РёРЅ Рё Р¶РµРЅС‰РёРЅ Р±СѓРґРµС‚ РїСЂРёРІРѕРґРёС‚СЊ Рє СЂР°Р·РЅРѕРјСѓ СЂРѕСЃС‚Сѓ Р·Р°СЂРїР»Р°С‚.</p>
<pre class="r"><code>qplot(height, earn, data = wages, alpha = I(1/10), color = sex) + theme_bw() + geom_line(aes(y = predict(lm(earn ~ height + sex,   data = wages))))</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
<pre class="r"><code>qplot(height, earn, data = wages, alpha = I(1/10), color = sex) + theme_bw() + geom_line(aes(y = predict(m4)))</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-99-1.png" width="672" /></p>
<p>РС‚Р°Рє, С„СѓРЅРєС†РёСЏ РІРёРґР°</p>
<pre class="r"><code>lm(earn ~ height + sex + height:sex, data = wages)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height + sex + height:sex, data = wages)
## 
## Coefficients:
##      (Intercept)            height         sexfemale  height:sexfemale  
##         -42677.4            1265.9           30510.4            -701.4</code></pre>
<p>Р±СѓРґРµС‚ РїСЂРµРґСЃРєР°Р·С‹РІР°С‚СЊ Р·РЅР°С‡РµРЅРёРµ Р·Р°СЂР°Р±РѕС‚РєР° РїРѕ Р·РЅР°С‡РµРЅРёСЋ СЂРѕСЃС‚Р°…СЃ СѓС‡РµС‚РѕРј Р·РЅР°С‡РµРЅРёСЏ РїРѕР»Р° …Рё СЃ СѓС‡РµС‚РѕРј РІР·Р°РёРјРѕРґРµСЃС‚РІРёСЏ РјРµР¶РґСѓ РїРµСЂРµРјРµРЅРЅС‹РјРё СЂРѕСЃС‚ Рё РїРѕР»</p>
<div id="yxz--yzx----" class="section level5">
<h5>Р’Р°Р¶РЅРѕ: РїРѕСЂСЏРґРѕРє РїРµСЂРµРјРµРЅРЅС‹С… РІ С„РѕСЂРјСѓР»Рµ РёРјРµРµС‚ РїРµСЂРІРѕСЃС‚РµРЅРµРЅРЅРѕРµ Р·РЅР°С‡РµРЅРёРµ y~x+z Рё y~z+x СЌС‚Рѕ РґРІРµ СЂР°Р·РЅС‹Рµ РјРѕРґРµР»Рё</h5>
<pre class="r"><code>lm(earn ~ height * sex, data = wages)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height * sex, data = wages)
## 
## Coefficients:
##      (Intercept)            height         sexfemale  height:sexfemale  
##         -42677.4            1265.9           30510.4            -701.4</code></pre>
<p>Р—РЅР°Рє * СЃР»СѓР¶РёС‚ СЃРѕРєСЂР°С‰РµРЅРЅРѕР№ Р·Р°РїРёСЃСЊСЋ РѕР±РѕР·РЅР°С‡РµРЅРёСЏ С‚РѕРіРѕ, С‡С‚Рѕ РјС‹ С…РѕС‚РёРј СЂР°СЃСЃРјРѕС‚СЂРµС‚СЊ РІР»РёСЏРЅРёРµ СЌС‚РёС… РґРІСѓС… РїРµСЂРµРјРµРЅРЅС‹С… РЅР° Р·Р°РІРёСЃРёРјСѓСЋ РїРµСЂРµРјРµРЅРЅСѓСЋ Рё С…РѕС‚РёРј СѓС‡РµСЃС‚СЊ РёС… РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёРµ РјРµР¶РґСѓ СЃРѕР±РѕР№.</p>
<p>Р—Р°РїРёСЃСЊ ^2 РѕР±РѕР·РЅР°С‡Р°РµС‚, С‡С‚Рѕ РІ РјРѕРґРµР»Рё РЅСѓР¶РЅРѕ СѓС‡РµСЃС‚СЊ РІСЃРµ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёСЏ РїРµСЂРІРѕРіРѕ РїРѕСЂСЏРґРєР°(СЃ РѕРґРЅРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ - +) Рё РІСЃРµ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёСЏ РІС‚РѕСЂРѕРіРѕ РїРѕСЂСЏРґРєР° (РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёСЏ РїРµСЂРµРјРµРЅРЅС‹С… РјРµР¶РґСѓ СЃРѕР±РѕР№ - :)</p>
<pre class="r"><code>lm(earn ~ height + sex + height:sex, data = w1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height + sex + height:sex, data = w1)
## 
## Coefficients:
##    (Intercept)          height         sexmale  height:sexmale  
##       -31845.8           868.3        139602.2         -1683.4</code></pre>
<pre class="r"><code>lm(earn ~ height * sex, data = w1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height * sex, data = w1)
## 
## Coefficients:
##    (Intercept)          height         sexmale  height:sexmale  
##       -31845.8           868.3        139602.2         -1683.4</code></pre>
<pre class="r"><code>lm(earn ~ (height + sex)^2, data = w1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ (height + sex)^2, data = w1)
## 
## Coefficients:
##    (Intercept)          height         sexmale  height:sexmale  
##       -31845.8           868.3        139602.2         -1683.4</code></pre>
<p>Р•СЃР»Рё РјС‹ Р·Р°С…РѕС‚РёРј СЂР°СЃСЃРјРѕС‚СЂРµС‚СЊ РјРѕРґРµР»СЊ СЃ С‚СЂРµРјСЏ РЅРµР·Р°РІРёСЃРёРјС‹РјРё РїРµСЂРµРјРµРЅРЅС‹РјРё,РЅР°РїСЂРёРјРµСЂ РґРѕР±Р°РІРёРј РІ РЅР°С€Сѓ РјРѕРґРµР»СЊ СЂР°СЃСЃСѓ, С‚Рѕ Сѓ РЅР°СЃ РїРѕСЏРІСЏС‚СЊСЃСЏ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёСЏ Рё С‚СЂРµС‚СЊРµРіРѕ РїРѕСЂСЏРґРєР° - height:sex:race</p>
<p>РўРѕРіРґР° РјС‹ РјРѕР¶РµРј РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ Р·Р°РїРёСЃСЊ ^3, РєРѕС‚РѕСЂР°СЏ Р±СѓРґРµС‚ РѕР±РѕР·РЅР°С‡Р°С‚СЊ, С‡С‚Рѕ РІ РјРѕРґРµР»Рё РЅР°РґРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РІСЃРµ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёСЏ РїРµСЂРІРѕРіРѕ, РІС‚РѕСЂРѕРіРѕ Рё С‚СЂРµС‚СЊРµРіРѕ РїРѕСЂСЏРґРєР°.</p>
<pre class="r"><code>lm(earn ~ (height + sex + race)^3,data = w1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ (height + sex + race)^3, data = w1)
## 
## Coefficients:
##                 (Intercept)                       height  
##                     -166395                         2944  
##                     sexmale                 racehispanic  
##                      491439                       183266  
##                   raceother                    racewhite  
##                      385211                       128984  
##              height:sexmale          height:racehispanic  
##                       -7062                        -2437  
##            height:raceother             height:racewhite  
##                       -6064                        -1993  
##        sexmale:racehispanic            sexmale:raceother  
##                          NA                           NA  
##           sexmale:racewhite  height:sexmale:racehispanic  
##                     -396323                           NA  
##    height:sexmale:raceother     height:sexmale:racewhite  
##                          NA                         6052</code></pre>
<pre class="r"><code>qplot(height, earn, data = w1, alpha = I(1/10), color = sex) + theme_bw() + geom_line(aes(y = predict(lm(earn ~ (height + sex + race)^3,data = w1))))</code></pre>
<p><img src="Part-4-topic-1_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
</div>
<div id="r" class="section level4">
<h4>РЁРїР°СЂРіР°Р»РєР° РїРѕ С„РѕСЂРјСѓР»Р°Рј РјРѕРґРµР»РёСЂРѕРІР°РЅРёСЏ РІ R</h4>
<ul>
<li>‘~’ РћС‚РґРµР»СЏРµС‚ Р·Р°РІРёСЃРёРјС‹Рµ РїРµСЂРµРјРµРЅРЅС‹Рµ СЃРїСЂР°РІР° РѕС‚ РЅРµР·Р°РІРёСЃРёРјС‹С… РїРµСЂРµРјРµРЅРЅС‹С… СЃР»РµРІР°. Рљ РїСЂРёРјРµСЂСѓ, С„РѕСЂРјСѓР»Р° Р·Р°РІРёСЃРёРјРѕСЃС‚Рё y РѕС‚ x, z, Рё w Р±СѓРґРµС‚ РІС‹РіР»СЏРґРµС‚СЊ РєР°Рє y ~ x + z + w.</li>
<li>‘+’ Р Р°Р·РґРµР»СЏРµС‚ РЅРµР·Р°РІРёСЃРёРјС‹Рµ РїРµСЂРµРјРµРЅРЅС‹Рµ.</li>
<li>‘:’ РћР±РѕР·РЅР°С‡Р°РµС‚ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёРµ РјРµР¶РґСѓ РЅРµР·Р°РІРёСЃРёРјС‹РјРё РїРµСЂРµРјРµРЅРЅС‹РјРё. РћРїРёСЃР°РЅРёРµ y РєР°Рє РІРµР»РёС‡РёРЅС‹ Р·Р°РІРёСЃРёРјРѕР№ РѕС‚ x, z, Рё РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёСЏ РјРµР¶РґСѓ x Рё z Р±СѓРґРµС‚ РІС‹РіР»СЏРґРµС‚СЊ РєР°Рє y ~ x + z + x:z.</li>
<li>‘*’ РљРѕСЂРѕС‚РєР°СЏ Р·Р°РїРёСЃСЊ РІСЃРµС… РІРѕР·РјРѕР¶РЅС‹С… РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёР№ РјРµР¶РґСѓ РїРµСЂРµРјРµРЅРЅС‹РјРё. РљРѕРґ y ~ x* z* w СЂР°РІРЅРѕР·РЅР°С‡РµРЅ y ~ x + z + w + x:z + x:w + z:w + x:z:w.</li>
<li>‘^’ РћР±РѕР·РЅР°С‡Р°РµС‚ РІР·Р°РёРјРѕРґРµР№СЃС‚РІРёРµ РѕРїСЂРµРґРµР»РµРЅРЅРѕРіРѕ СѓСЂРѕРІРЅСЏ. РўР°Рє РєРѕРґ y ~ (x + z + w)^2 СЂР°РІРЅРѕР·РЅР°С‡РµРЅ y ~ x + z + w + x:z + x:w + z:w.</li>
<li>‘.’ РљСЂР°С‚РєР°СЏ Р·Р°РїРёСЃСЊ РѕР±РѕР·РЅР°С‡Р°СЋС‰Р°СЏ РІСЃРµ РѕСЃС‚Р°Р»СЊРЅС‹Рµ РїРµСЂРµРјРµРЅРЅС‹Рµ РІ С‚Р°Р±Р»РёС†Рµ РєСЂРѕРјРµ Р·Р°РІРёСЃРёРјРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№. РќР°РїСЂРёРјРµСЂ, РµСЃР»Рё С‚Р°Р±Р»РёС†Р° СЃРѕРґРµСЂР¶РёС‚ РїРµСЂРµРјРµРЅРЅС‹Рµ x, y, z, Рё w, С‚РѕРіРґР° РєРѕРґ y ~ . Р±СѓРґРµС‚ СЂР°РІРЅРѕР·РЅР°С‡РµРЅ y ~ x + z + w.</li>
<li>‘-’ Р—РЅР°Рє РјРёРёРЅСѓСЃР° СѓР±РёСЂР°РµС‚ РїРµСЂРµРјРµРЅРЅСѓСЋ РёР· С„РѕСЂРјСѓР»С‹. РќР°РїСЂРёРјРµСЂ, y ~ (x + z + w)^2 вЂ“ x:w СЂР°РІРЅРѕР·РЅР°С‡РЅРѕ y ~ x + z + w + x:z + z:w.</li>
<li>‘-1’ РЈР±РёСЂР°РµС‚ РїРµСЂРІС‹Р№ РєРѕСЌС„РёС†РёРµРЅС‚, Р·Р°СЃС‚Р°РІР»СЏСЏ РіСЂР°С„РёРє РјРѕРґРµР»СЊРЅРѕР№ С„СѓРЅРєС†РёРё РїСЂРѕС…РѕРґРёС‚СЊ С‡РµСЂРµР· РЅР°С‡Р°Р»Рѕ РєРѕРѕСЂРґРёРЅР°С‚ .</li>
<li>‘I()’ Р­Р»РµРјРµРЅС‚С‹ РІРЅСѓС‚СЂРё СЃРєРѕР±РѕРє РёРЅС‚РµСЂРїСЂРµС‚РёСЂСѓСЋС‚СЃСЏ С‡РёСЃР»РµРЅРЅРѕ. РќР°РїСЂРёРјРµСЂ, y ~ x + (z + w)^2 СЂР°РІРЅРѕР·РЅР°С‡РЅРѕ y ~ x + z + w + z:w. РќРѕ, РєРѕРґ y ~ x + I((z + w)^2) СЂР°РІРЅРѕР·РЅР°С‡РµРЅ y ~ x + h, РіРґРµ h РЅРѕРІР°СЏ РїРµСЂРµРјРµРЅРЅР°СЏ, РїРѕР»СѓС‡РµРЅРЅР°СЏ РІРѕР·РІРµРґРµРЅРёРµРј РІ РєРІР°РґСЂР°С‚ СЃСѓРјРјС‹ z Рё w.</li>
<li>‘function’ Р›СЋР±Р°СЏ РјР°С‚РµРјР°С‚РёС‡РµСЃРєР°СЏ С„СѓРЅРєС†РёСЏ РјРѕР¶РµС‚ Р±С‹С‚СЊ РёСЃРїРѕР»СЊР·РѕРІР°РЅР° РІ С„РѕСЂРјСѓР»Рµ. РќР°РїСЂРёРјРµСЂ, log(y) ~ x + z + w РїРѕРїС‹С‚Р°РµС‚СЃСЏ РѕРїРёСЃР°С‚СЊ Р·Р°РІРёСЃРёРјРѕСЃС‚СЊ log(y) РѕС‚ x, z, Рё w.</li>
</ul>
</div>
<div id="section-14" class="section level4">
<h4>РђРЅР°Р»РёР· РјРѕРґРµР»РµР№ РјРЅРѕР¶РµСЃС‚РІРµРЅРЅРѕР№ СЂРµРіСЂРµСЃРёРё</h4>
<p>Р’СЃРµ Р·Р°РґР°С‡Рё, С‡С‚Рѕ СЃС‚РѕСЏР»Рё РїРµСЂРµРґ РЅР°РјРё РїРѕ Р°РЅР°Р»РёР·Сѓ РјРѕРґРµР»РµР№ Р»РёРЅРµР№РЅРѕР№ СЂРµРіСЂРµСЃСЃРё Р°РєС‚СѓР°Р»СЊРЅС‹ Рё Р·РґРµСЃСЊ. РќРѕ РґР»СЏ РјРѕРґРµР»РµР№ РјРЅРѕР¶РµСЃС‚РІРµРЅРЅРѕР№ СЂРµРіСЂРµСЃСЃРёРё РїРѕСЏРІР»СЏРµС‚СЃСЏ РµС‰Рµ РѕРґРЅР° Р·Р°РґР°С‡Р° - РѕРїСЂРµРґРµР»РµРЅРёРµ РІРєР»Р°РґР° РєР°Р¶РґРѕР№ РѕС‚РґРµСЊРЅРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№ РІ РёС‚РѕРіРѕРІСѓСЋ РјРѕРґРµР»СЊ Рё Р·Р°РєР»СЋС‡РµРЅРёРµ Рѕ РµРµ РЅРµРѕР±С…РѕРґРёРјРѕСЃС‚Рё РїСЂРµР±С‹РІР°РЅРёСЏ РІ РѕРЅРѕР№.</p>
<p>Р•С‰Рµ РѕРґРЅР° РїСЂРѕР±Р»РµРјР°, РєСЂРѕРјРµ С‚РѕРіРѕ, С‡С‚Рѕ РїРµСЂРµРјРµРЅРЅС‹Рµ, РєРѕС‚РѕСЂС‹Рµ РІС‹ РґРѕР±Р°РІРёР»Рё РјРѕРіСѓС‚ РЅРµР·РЅР°С‡РёС‚РµР»СЊРЅРѕ РІР»РёСЏС‚СЊ РЅР° РІР°С€Сѓ РјРѕРґРµР»СЊ, Р·Р°РєР»СЋС‡Р°РµС‚СЃСЏ РІ С‚РѕРј, С‡С‚Рѕ РµСЃР»Рё РїСЂРёСЃСѓС‚СЃС‚РІСѓСЋС‰РёРµ РІ РјРѕРґРµР»Рё РїРµСЂРµРјРµРЅРЅС‹Рµ РєРѕСЂРµР»Р»РёСЂСѓСЋС‚, СЌС‚Рѕ РјРѕР¶РµС‚ РІРЅРѕСЃРёС‚СЊ СЃРёР»СЊРЅСѓСЋ РѕС€РёР±РєСѓ РІ РёС… СЂ-Р·РЅР°С‡РµРЅРёСЏ.</p>
<p>Р”Р»СЏ С‚РѕРіРѕ С‡С‚РѕР±С‹ РёР·Р±РµР¶Р°С‚СЊ РїРѕРґРѕР±РЅРѕР№ СЃРёС‚СѓР°С†РёРё, РёР·РІРµСЃС‚РЅРѕР№ РїРѕРґ РЅР°Р·РІР°РЅРёРµРј РјСѓР»СЊС‚РёРєРѕР»Р»РёРЅРµР°СЂРЅРѕСЃС‚СЊ, РІР°Рј РїСЂРёРґРµС‚СЃСЏ РїСЂРѕРІРµСЂРёС‚СЊ РєРѕСЌС„С„РёС†РµРЅС‚С‹ РєРѕСЂСЂРµР»СЏС†РёРё РґР»СЏ РІСЃРµС… РІР°С€РёС… РїРµСЂРµРјРµРЅРЅС‹С…:</p>
<pre class="r"><code>cor(wages$height, wages$ed)</code></pre>
<pre><code>## [1] 0.1140473</code></pre>
<pre class="r"><code>cor(wages$height, wages$age)</code></pre>
<pre><code>## [1] -0.1337271</code></pre>
<pre class="r"><code>cor(wages$height, as.numeric(wages$sex))</code></pre>
<pre><code>## [1] -0.7036717</code></pre>
<p>Р•СЃР»Рё РЅРµРєРѕС‚РѕСЂС‹Рµ РёР· РІР°С€РёС… РїРµСЂРµРјРµРЅРЅС‹С… Р·РЅР°С‡РёРјРѕ РєРѕСЂСЂРµР»РёСЂСѓСЋС‚, С‚Рѕ РІР°Рј РЅР°РґРѕ РІС‹Р±СЂР°С‚СЊ РѕРґРЅСѓ РёР· РЅРёС…, РѕС‚РєР°Р·Р°РІС€РёСЃСЊ РѕС‚ РґСЂСѓРіРѕР№.</p>
<p>РџРѕРјРёРјРѕ СЌС‚РёС… РїСЂРѕР±Р»РµРј, РґР»СЏ РјРѕРґРµР»РµР№ СЃРѕРµСЂР¶Р°С‰РёС… РјРЅРѕР¶РµСЃС‚РІРѕ РїРµСЂРµРјРµРЅРЅС‹С… РїСЂРѕР±Р»РµРјРѕР№ СЃС‚Р°РЅРѕРІРёС‚СЃСЏ С‚Рѕ, С‡С‚Рѕ СЃ СѓРІРµР»РёС‡РµРЅРёРµРј РєРѕР»РёС‡РµСЃС‚РІР° РїРµСЂРµРјРµРЅРЅС‹С… СѓРІРµР»РёС‡РёРІР°РµС‚ С€Р°РЅСЃ С‚РѕРіРѕ, РґР»СЏ РєР°РєРѕР№-С‚Рѕ РёР· РїРµСЂРµРјРµРЅРЅС‹С… РјС‹ РїРѕР»РёРј РЅРµР°РґРµРєРІР°С‚РЅС‹Рµ СЂ-Р·РЅР°С‡РµРЅРёРµ РїСЂРѕСЃС‚Рѕ РІ СЂРµР·СѓР»СЊС‚Р°С‚Рµ РЅРµСѓРґР°С‡РЅРѕР№ РІС‹Р±РѕСЂРєРё.</p>
<p>РќР°РїСЂРёРјРµСЂ, СЂ-Р·РЅР°С‡РµРЅРёРµ &lt; 0.05 Р±СѓРґРµС‚ РєР°Р¶РґС‹Рј РґРІР°РґС†Р°С‚С‹Рј СЃСЂРµРґРё Р±РµСЃРєРѕРЅРµС‡РЅРѕРіРѕ РјРЅРѕР¶РµСЃС‚РІР° p-Р·РЅР°С‡РµРЅРёР№, РїСЂРѕСЃС‚Рѕ РїРѕ Р·Р°РєРѕРЅСѓ Р±РѕР»СЊС€РёС… С‡РёСЃРµР».</p>
<p>РўРѕРіРґР°, РІРµСЂРѕСЏС‚РЅРѕСЃС‚СЊ С‚РѕРіРѕ, С‡С‚Рѕ С…РѕС‚СЏ Р±С‹ РѕРґРЅРѕ СЂ-Р·РЅР°С‡РµРЅРёРµ &lt; 0.05 = 0.05. Р’РµСЂРѕСЏС‚РЅРѕСЃС‚СЊ С‚РѕРіРѕ, С‡С‚Рѕ С…РѕС‚СЏ Р±С‹ РѕРґРЅРѕ РёР· РґРІСѓС… СЂ-Р·РЅР°С‡РµРЅРёР№ &lt; 0.05 = 0.098. … … … Р’РµСЂРѕСЏС‚РЅРѕСЃС‚СЊ С‚РѕРіРѕ, С‡С‚Рѕ С…РѕС‚СЏ Р±С‹ РѕРґРЅРѕ РёР· РґРІР°РґС†Р°С‚Рё СЂ-Р·РЅР°С‡РµРЅРёР№ &lt; 0.05 = 0.64</p>
<p>Р”Р»СЏ С‚РѕРіРѕ, С‡С‚РѕР±С‹ РЅРµ РѕС‚РІРµСЂРіРЅСѓС‚СЊ СЂРµР°Р»СЊРЅРѕ РІР»РёСЏСЋС‰РёРµ РЅР° РІР°С€Сѓ РјРѕРґРµР»СЊ РїРµСЂРµРјРµРЅРЅС‹Рµ РІ СЂРµР·СѓР»СЊС‚Р°С‚Рµ С‚Р°РєРѕРіРѕ СЌС„С„РµРєС‚Р° СЂРµРєРѕРјРµРЅРґСѓРµС‚СЃСЏ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ РѕРґРёРЅ РёР· СЃР»РµРґСѓСЋС‰Рё РїРѕРґС…РѕРґРѕРІ</p>
<ol style="list-style-type: decimal">
<li>РСЃРїРѕР»СЊР·РѕРІР°С‚СЊ Р±РѕР»РµРµ РЅРёР·РєРѕРµ О± Р·РЅР°С‡РµРЅРёРµ РґР»СЏ РѕРїСЂРµРґРµР»РµРЅРёСЏ Р·РЅР°С‡РёРјРѕСЃС‚Рё (РЅР°РїСЂРёРјРµСЂ СЂР°РІРЅРѕРµ О± / p)</li>
<li>РџСЂРѕРІРµСЂСЏС‚СЊ РІ РїРµСЂРІСѓСЋ РѕС‡РµСЂРµРґСЊ С‚Рѕ, С‡Рѕ РІСЃСЏ РјРѕРґРµР»СЊ СЃС‚Р°С‚РёСЃС‚РёС‡РµСЃРєРё Р·РЅР°С‡РёРјР° Рё СѓР¶Рµ РёСЃС…РѕРґСЏ РёР· СЌС‚РѕРіРѕ РїСЂРёРЅРёРјР°С‚СЊ СЂРµС€РµРЅРёРµ РѕР± РёСЃРєР»СЋС‡РµРЅРёРё С‚РѕР№ РёР»Рё РёРЅРѕР№ РїРµСЂРµРјРµРЅРЅРѕР№.</li>
</ol>
<p>РќР°РїСЂРёРјРµСЂ, РґР»СЏ РјРѕРґРµР»Рё m4</p>
<pre class="r"><code>summary(m4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = earn ~ height + sex + height:sex, data = wages)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -49699 -20090  -5034  11553 271709 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)      -42677.4    30488.0  -1.400  0.16180   
## height             1265.9      434.9   2.911  0.00366 **
## sexfemale         30510.4    39644.1   0.770  0.44166   
## height:sexfemale   -701.4      585.8  -1.197  0.23141   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 29340 on 1375 degrees of freedom
## Multiple R-squared:  0.1205, Adjusted R-squared:  0.1186 
## F-statistic: 62.82 on 3 and 1375 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>РџРѕР»СѓС‡РµРЅРЅС‹Рµ РґР°РЅРЅС‹Рµ РѕР·РЅР°С‡Р°СЋС‚, С‡С‚Рѕ РјРѕРґРµР»СЊ m4 РёРјРµРµС‚ Р·РЅР°С‡РёРјСѓСЋ СЂР°Р·РЅС†Сѓ РІ С‚РѕС‡РЅРѕСЃС‚Рё РїСЂРµРґСЃРєР°Р·Р°РЅРёСЏ РїРѕ СЃСЂР°РІРЅРµРЅРёСЋ СЃ РјРѕРґРµР»СЊСЋ m1. Рў.Рµ. РґСЂСѓРіРёРјРё СЃР»РѕРІР°РјРё, С‚.Рє. СЂР°Р·РЅРёС†Р° РјРµР¶РґСѓ РјРѕРґРµР»СЏРјРё Р·Р°РєР»СЋС‡Р°Р»Р°СЃСЊ РІ РЅР°Р»РёС‡РёРё РІ РјРѕРґРµР»Рё m4 РїРµСЂРµРјРµРЅРЅРѕР№ РїРѕР»(sex), С‚Рѕ РІРєР»СЋС‡РµРЅРёРµ РїРµСЂРµРјРµРЅРЅРѕР№ РїРѕР» РІ РЅР°С€Сѓ РјРѕРґРµР»СЊ СѓР»СѓС‡С€Р°РµС‚ РµРµ С‚РѕС‡РЅРѕСЃС‚СЊ, Р° Р·РЅР°С‡РёС‚ РїРµСЂРµРјРµРЅРЅР°СЏ РїРѕР» РёРјРµРµС‚ РїСЂР°РІРѕ РІ РЅРµР№ РїСЂРёСЃСѓС‚СЃС‚РІРѕРІР°С‚СЊ.</p>
<p>Р•СЃР»Рё РјС‹ СЂР°СЃСЃРјРѕС‚СЂРёРј РґР°РЅРЅС‹Рµ, РїРѕР»СѓС‡РµРЅРЅС‹Рµ РѕС‚ С„СѓРЅРєС†РёРё anova() С‚РѕР»СЊРєРѕ РґР»СЏ РѕРґРЅРѕР№ РјРѕРґРµР»Рё m4, С‚Рѕ РјС‹ СѓРІРёРґРёРј, С‡С‚Рѕ</p>
<pre class="r"><code>anova(m4)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: earn
##              Df     Sum Sq    Mean Sq  F value    Pr(&gt;F)    
## height        1 1.1448e+11 1.1448e+11 132.9410 &lt; 2.2e-16 ***
## sex           1 4.6562e+10 4.6562e+10  54.0720 3.307e-13 ***
## height:sex    1 1.2343e+09 1.2343e+09   1.4334    0.2314    
## Residuals  1375 1.1840e+12 8.6112e+08                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>СЂ-Р·РЅР°С‡РµРЅРёРµ РґР»СЏ РїРµСЂРµРјРµРЅРЅРѕР№ height:sex Р±РѕР»СЊС€Рµ РїСЂРµРґРµР»СЊРЅРѕРіРѕ СЂ-Р·РЅР°РµРЅРёСЏ, Р° Р·РЅР°С‡РёС‚, РјРѕРґРµР»СЊ СЃРѕРґРµСЂР¶Р°С‰Р°СЏ РїРµСЂРµРјРµРЅРЅС‹Рµ heights + sex + heights:sex РЅРµ Р·РЅР°С‡РёРјРѕ Р»СѓС‡С€Рµ С‡РµРј РјРѕРґРµР»СЊ СЃРѕРґРµСЂР¶Р°С‰Р°СЏ РїРµСЂРµРјРµРЅРЅС‹Рµ heights + sex, Р° Р·РЅР°С‡РёС‚ РѕС‚ РїРµСЂРµРјРµРЅРЅРѕР№ height:sex РјС‹ РјРѕР¶РµРј РѕС‚РєР°Р·Р°С‚СЊСЃСЏ.</p>
</div>
<div id="section-15" class="section level4">
<h4>РС‚РѕРіРѕРІС‹Р№ Р°Р»РіРѕСЂРёС‚Рј РёСЃСЃР»РµРґРѕРІР°РЅРёСЏ РјРѕРґРµР»Рё Р±СѓРґРµС‚ Р·Р°РєР»СЋС‡Р°С‚СЊСЃСЏ РІ РїРѕР»СѓС‡РµРЅРёРё Рё РёРЅС‚РµСЂРїСЂРµС‚Р°С†РёРё СЃР»РµРґСѓСЋС‰РёС… Р·РЅР°С‡РµРЅРёР№</h4>
<ul>
<li>РљРѕСЌС„С„РёС†РёРµРЅС‚С‹ - coef(mod)</li>
<li>РћСЃС‚Р°С‚РєРё - resid(mod)</li>
<li>Р”РѕРІРµСЂРёС‚РµР»СЊРЅС‹Р№ РёРЅС‚РµСЂРІР°Р» - confint(mod)</li>
<li>P-Р·РЅР°С‡РµРЅРёСЏ - summary(mod)</li>
<li>РЎСЂР°РІРЅРµРЅРёРµ РІР°СЂРёР°РЅС‚РѕРІ РјРѕРґРµР»Рё - anova(mod1, mod2)</li>
</ul>
</div>
</div>

</div> <!-- lessonContent -->
</div> <!-- lessonPage -->


<script type="text/javascript">
  var lesson = window.location.href.match(/lesson-[0-9]+/g);
  if (lesson !== null) {
    lesson = 'nav-' + lesson[0];
    $('#'+lesson).addClass('current');
  }

  $('#show-answer').on("click", function() {
    $('#show-answer').addClass('showing');
    $('#model-answer').addClass('showing');
  })
</script>
  </div> <!-- articleBandContent -->
</div> <!-- pageContent -->

<!-- <div id="rStudioFooter" class="band full">
<div class="bandContent">
  <div id="copyright">Создано с помощью R в Лаборатории Агроэкологического Мониторинга и Прогнозирования экосистем - <a href="http://lamp-lab.ru">ЛАМП</a></div>
  <div id="logos">
<a href="https://twitter.com/rstudio" class="footerLogo twitter"></a>
  <a href="https://github.com/rstudio" class="footerLogo gitHub"></a>
   <a href="https://www.linkedin.com/company/rstudio-inc" class="footerLogo linkedIn"></a>
  <a href="https://www.facebook.com/pages/RStudio-Inc/267733656584415" Class="footerLogo facebook"></a>
  </div>
</div>
</div> -->

<div class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <p class="navbar-text pull-left">© 2019 - Создано с помощью R в Лаборатории Агроэкологического Мониторинга и Прогнозирования экосистем -
      <a href="http://lamp-lab.ru">ЛАМП</a>
      </p>
    </div>
</div>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
