---
title: "Задания"
output:
  html_document:
    toc_float: false
    highlight: textmate
    includes:
      before_body: [include_header.html]
      after_body: [include_footer.html]
---

## Введение в R 


1. Вычислить среднее для каждой колонки таблицы iris, за исключением колонки "Species" и соберите результат в список (list).

2. Вычислить среднее для каждой строки, исключив перед этим колонку "Species" и сохраните результат в векторе.

3. Создайте случайные 1000 нуклеотидов, сохранив их в вектор DNA, посчитайте количество нуклеотидов A и T, их долю от общей длинны ДНК и запишите результат в вектор 'dna_at'

4. Создайте векто в котором записан произвольный набор латинских букв длинной не менее 10000 символов и посчитайте количество гласных.

5. Отсортируйте все виды в таблице iris по средней длинне лепестков. Результат должен быть фактором с градациями в виде имен видов с правильной последовательностью уровней.

6. Напишите функцию для рассчета медианы вектора самостоятельно.

7. Постройте график зависимости длины чашелистиков от длинны лепестков для каждого вида из таблицы iris

8. По данным таблицы 'diamonds'(пакет ggplot2 ) почитайте среднюю стоимость цены карата для бриллиантов дороже 1000$ для каждой категории яркости (clarity).

## Регрессионный и корелляционный анализы

1. Написать собственную функцию, которая бы для двух векторов одинакового объема считала бы коэффициент корелляции Спирмена  $r = 1 - \frac{6\sum_{i=1}^N d^2}{n(n^2 - 1)}$.  Для получения рангов ипользуйте функцию rank. Дополнительные балы для тех, кто сможет исользовать функцую match вместо rank.

2. Используя данные по [ссылке][l1], постройте оптимальную линейную модель множественной регрессии для co2_flux используя только данные летних месяцев. В данных вместо значения NA используется значения -9999, исправьте это действием подобным data[data == -9999] = NA. Для выбора нужных суток используйте переменную DOY - день года (1 января - DOY = 1)

**ВНИМАНИЕ! Для успешного решения задачи внимательно прочитайте раздел "Манипуляции над данными"!**

## Темы курсовых и самостоятельных работ:
### для 125 группы

1. Адельшина Руфия  - "Создание моделей линейной регрессии потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
2. Барышкина Татьяна - "Создание моделей линейной регрессии дневных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации" 
3. Васильков Павел - "Создание моделей линейной регрессии дневных потоков углекислого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации" 
4. Гулиева Илона - "Создание моделей линейной регрессии дневных потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
5. Евдокимова Валерия - "Создание моделей линейной регрессии дневных потоков паров воды газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
6. Ковригина Елизавета - "Создание моделей линейной регрессии дневных потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации" 
7. Любимов Иван  - "Создание моделей линейной регрессии дневных потоков паров воды за осенний период 2013 года по данным измерений методом турбулентной пульсации" 
8. Минасян Александр - "Создание моделей линейной регрессии ночных потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
9. Новикова Виктория - "Создание моделей линейной регрессии ночных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации" 
10. Пимахина Татьяна - "Создание моделей линейной регрессии ночных потоков углекислого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации" 
11. Покоева Мария - "Создание моделей линейной регрессии ночных потоков паров воды за весенний период 2013 года по данным измерений методом турбулентной пульсации"
12. Рассоленко Максим - "Создание моделей линейной регрессии ночных потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации"
13. Рябинкина Виктория - "Создание моделей линейной регрессии ночных потоков паров воды за осенний период 2013 года по данным измерений методом турбулентной пульсации"
14. Семенова Анастасия - "Создание моделей линейной регрессии потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации"
15. Соловьев Алексей - "Создание моделей линейной регрессии потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации"
16. Уляшкина Алена - "Создание моделей линейной регрессии потоков углексилого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации"
17. Хадиев Амирхан - "Создание моделей линейной регрессии потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации"

### для 121 группы

1. Агеева Екатерина - "Создание моделей линейной регрессии потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
2. Бочарова Татьяна - "Создание моделей линейной регрессии дневных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации" 
3. Васильев Дмитрий - "Создание моделей линейной регрессии дневных потоков углекислого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации"
4. Васильева Маргарита - "Создание моделей линейной регрессии дневных потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
5. Виноградова Кристина - "Создание моделей линейной регрессии дневных потоков паров воды газа за весенний период 2013 года по данным измерений методом турбулентной пульсации"
6. Исаков Павел - "Создание моделей линейной регрессии дневных потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации" 
7. Канавский Роман - "Создание моделей линейной регрессии дневных потоков паров воды за осенний период 2013 года по данным измерений методом турбулентной пульсации" 
8. Козина Татьяна - "Создание моделей линейной регрессии ночных потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
9. Комраков Кирилл - "Создание моделей линейной регрессии ночных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации" 
10. Мусенова Дарья - "Создание моделей линейной регрессии ночных потоков углекислого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации"
11. Наумова Ольга - "Создание моделей линейной регрессии ночных потоков паров воды за весенний период 2013 года по данным измерений методом турбулентной пульсации"
12. Пасечник Галина - "Создание моделей линейной регрессии ночных потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации"
13. Поличевская Анна - "Создание моделей линейной регрессии ночных потоков паров воды за осенний период 2013 года по данным измерений методом турбулентной пульсации"
14. Постникова Ксения - "Создание моделей линейной регрессии потоков паров воды за весенний период 2013 года по данным измерений методом турбулентной пульсации"
15.Соколов Артем - "Создание моделей линейной регрессии потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации"
16. Соколов Дмитрий - "Создание моделей линейной регрессии потоков углексилого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации"
17.Чебану Георгий - "Создание моделей линейной регрессии потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации"
18. Юдина Ксения - "Создание моделей линейной регрессии потоков паров воды за осениий период 2013 года по данным измерений методом турбулентной пульсации"


### для 124 группы

1. Акимова Юлия - "Создание моделей линейной регрессии потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации"
2. Альсаед Нур - "Создание моделей линейной регрессии дневных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации"
3. Алябина Александра - "Создание моделей линейной регрессии дневных потоков углекислого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации"
4. Бакулева Анастасия - "Создание моделей линейной регрессии дневных потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
5. Белокуров Павел - "Создание моделей линейной регрессии дневных потоков паров воды газа за весенний период 2013 года по данным измерений методом турбулентной пульсации"
6. Вершенник Елизавета - "Создание моделей линейной регрессии дневных потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации" 
7. Ветрова Екатерина - "Создание моделей линейной регрессии дневных потоков паров воды за осенний период 2013 года по данным измерений методом турбулентной пульсации" 
8. Горбаневский Алексей - "Создание моделей линейной регрессии ночных потоков углекислого газа за весенний период 2013 года по данным измерений методом турбулентной пульсации" 
9. Григорян Артем - "Создание моделей линейной регрессии ночных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации" 
10. Данилов Никита - "Создание моделей линейной регрессии ночных потоков углекислого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации"
11. Двойникова Светлана - "Создание моделей линейной регрессии ночных потоков паров воды за весенний период 2013 года по данным измерений методом турбулентной пульсации"
12. Киреев Кирилл - "Создание моделей линейной регрессии ночных потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации"
13. Киселева Ангелина - "Создание моделей линейной регрессии ночных потоков паров воды за осенний период 2013 года по данным измерений методом турбулентной пульсации"
14. Малахова Дарья - "Создание моделей линейной регрессии потоков паров воды за весенний период 2013 года по данным измерений методом турбулентной пульсации"
15. Одинцова Ирина - "Создание моделей линейной регрессии потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации"
16. Пассова Дарья  - "Создание моделей линейной регрессии потоков углексилого газа за осенний период 2013 года по данным измерений методом турбулентной пульсации"
17. Пелевина Анна  - "Создание моделей линейной регрессии потоков паров воды за летний период 2013 года по данным измерений методом турбулентной пульсации"
18. Путникова Елена  - "Создание моделей линейной регрессии потоков паров воды за осенний период 2013 года по данным измерений методом турбулентной пульсации"
19. Руфуллаев Элвин  - "Создание моделей линейной регрессии ночных потоков паров воды по данным измерений методом турбулентной пульсации 2013 года"
20. Скачкова Александра - "Создание моделей линейной регрессии дневных потоков паров воды   по данным измерений методом турбулентной пульсации 2013 года"
21. Староверова Юлия  - "Создание моделей линейной регрессии дневных потоков углекислого газа  по данным измерений методом турбулентной пульсации 2013 года"
22. Шапкин Андрей  - "Создание моделей линейной регрессии ночных потоков углекислого газа  по данным измерений методом турбулентной пульсации 2013 года"




[l1]:https://www.dropbox.com/s/erhs9hoj4vhrz0b/eddypro.csv?dl=1 
